---

ansible_ssh_user: admin1
ansible_ssh_pass: Sph@era92

root_pass: Sph@era92

domain: 'test18.local'

Net:
  network: 192.168.1.0/24
  net: 192.168.1.0
  mask: 255.255.255.0
  gateway: 192.168.1.1
  bind:
    - 192.168.1.1
    - 77.88.8.8

#####################
### 0.2-Repo      ###
#####################
repo:
  # srv: srv-repo  # Имя сервера репозиториев
  # port: 8080     # Порт HTTP
  # name_iso:
        # - installation-1.8.1.12-29.08.24_15.37
        # - devel-1.8.1.12-29.08.24_15.37
        # - extended-1.8.1.12-29.08.24_15.37
  name_web:
    - dl.astralinux.ru/astra/stable/1.8_x86-64/main-repository
    - dl.astralinux.ru/astra/stable/1.8_x86-64/extended-repository
  dist: 1.8_x86-64
  res: contrib main non-free
  build: 1.8.2.7
  kernel: 6.12.11-1-generic
  live_cd: alse-1.8.1.UU1

####################
### 0.5-Time      ###
####################
ntp:
  timezone: Europe/Dublin
  srv: 192.168.1.1

####################
### 1.1-PXE      ###
####################
# Сервер PXE
# srv  - Имя сервера
# port - Порт веб сервера с пресидами
# dhcp - Диапазон адресов DHCP сервера
# pxe:
  # srv: zabbix01
  # port: 8090
  # dhcp:
    # - 210
    # - 219
  # grub: 12345678

####################
### 2.1-FreeIPA  ###
####################
# FreeIPA:
  # srv: 2ipa01
  # replica: 1ipa02
  # pass: Sph@era92

####################
### 3.1-Zabbix   ###
####################
# Сервер Zabbix
# Zabbix:
  # srv: 2moniroring01
  # port: 8085
  # db:
    # user: user_zabbix
    # password: P@ssw0rd
    # name: db_zabbix

######################
### 3.3-Xrdp       ###
######################
# srv - Список серверов xRdp
# group - Группа (FreeIPA) с правом доступа по протоколу rdp
# Xrdp:
  # srv:
   # - xrdp
  # group: rdpclients

# Cluster:
  # group: haclient
  # user: hacluster
  # pass: P@ssw0rd

########################
### 3.8-NFS          ###
########################
# nfs:
  # srv: nfs
  # path: /nfs_share
  # device: /dev/sdb1

######################
### 3.22-Ceph       ###
######################
# Ceph:
  #ver: 16.2.9
  # user: ceph-adm
  # password: Sph@era92
  # nodes:
    # - storage01
    # - storage02
    # - storage03
  # dev:
    # - 500G
  # net:
    # interface: ens19
    # network: 10.234.0.0/24 

########################
### 3.28-Registry    ###
########################
# registry:
  # srv: s04registry
  # path: /mnt/data

####################
### 6.1-GitLab   ###
####################
# Сервер GitLab
# GitLab:
  # srv: gitlab
  # path: /opt

####################
### 6.2-Prometheus   ###
####################
# Сервер Prometheus + Grafana
# Prometheus:
  # srv: monitoring
  # path: /opt


...