---

ansible_ssh_user: user
ansible_ssh_pass: 12345678

root_pass: 12345678

domain: 'test12.local'

Net:
  network: 192.168.1.0/24
  net: 192.168.1.0
  mask: 255.255.255.0
  gateway: 192.168.1.1
  bind:
    - 192.168.1.1
    - 77.88.8.8

#####################
### 0.2-Repo      ###
#####################
repo:
  name_web:
    - deb.debian.org/debian bookworm
    - security.debian.org/debian-security bookworm-security
    - deb.debian.org/debian bookworm-updates 
  dist:
  res: main non-free-firmware
  # build: 1.8.2.7
  # kernel: 6.12.11-1-generic
  # live_cd: alse-1.8.1.UU1

####################
### 0.5-Time      ###
####################
ntp:
  timezone: Europe/Dublin
  srv: 192.168.1.1

####################
### 6.3-Jenkins  ###
####################
# Сервер Jenkins
Jenkins:
  srv: jenkins
  path: /opt



...