---

# МосОблГаз

remote_user: s04admin
ansible_ssh_user: s04admin
ansible_ssh_pass: $04@dmin12%^
ansible_ssh_private_key_file: ./ssh/s04admin/id_rsa.pub

domain: 'mog.ent.local'

net:
  network: 10.4.151.0/24
  net: 10.4.151.0
  mask: 255.255.255.0
  gateway: 10.4.151.254
  bind: 10.4.151.15
  vlan:


####################
### 0.5-Time      ###
####################
ntp:
  timezone: Europe/Moscow
  srv:
    - 10.10.10.1


######################
### 3.22-Ceph       ###
######################
Ceph:
  user: ceph-adm
  password: Sph@era92
  nodes:
    - s04ceph1
    - s04ceph2
    - s04ceph3
  dev:
    - /dev/mapper/vg2-lv_cephosd 
    
  net:
    interface: ens19
    network: 10.4.237.0/24 


########################
### 3.28-Registry    ###
########################
registry:
  srv: s04registry
  path: /mnt/data
  port: 5000


########################
### 3.29-K8s          ###
########################
k8s:
  ver: '1.32'
  masters:
    - s04master1
    - s04master2
    - s04master3
  workers:
    - s04worker1
    - s04worker2
    - s04worker3
  keepalived_IP: 10.4.151.205
  haproxy_port: 8443
# подсеть выделенная для подов
  pod_subnet: 10.4.160.0/22
# подсеть выделенная для сервисов
  service_subnet: 10.4.164.0/24
# адрес внутреннего днс куба (первые 3 октета из подсети сервисов, последний - 10)
  core_dns: 10.4.164.10
  rwo_sc: csi-rwo-sc
  rwx_sc: csi-rwx-sc
  ceph_csi: 3  ## Количество провиженоров 'CephRBD' и 'CephFS'. Должно равняться количеству воркеров.
# Если равно '0' устанавливается ниже указанные провиженеры
  lvm_provisioner:    ## LVM RWO # Уcтанавливатся вместо 'CephRBD'
    namespace: csi-lvm-system
    device: /dev/sdb
    vg_name: vg01
  nfs_provisioner:    ## NFS RWX # Уcтанавливатся вместо 'CephFS'
    namespace: csi-nfs-system
    disk_size: 50Gi
    server_ip:
    path:


...