---

# МосОблГаз

remote_user: s04admin
ansible_ssh_user: s04admin
ansible_ssh_pass: $04@dmin12%^
ansible_ssh_private_key_file: ./ssh/s04admin/id_rsa.pub

domain: 'mog.ent.local'

Net:
  network: 10.4.151.0/24
  net: 10.4.151.0
  mask: 255.255.255.0
  gateway: 10.4.151.254
  bind:
    - 8.8.8.8
    - 10.4.151.15
    # - 10.4.250.15
    # - 10.4.250.16
  routes:
    - '10.4.164.0/24 10.4.151.208 11'
    - '10.4.164.0/24 10.4.151.209 12'
    - '10.4.164.0/24 10.4.151.210 13'
    - '10.4.164.0/24 10.4.151.211 14'
    - '10.4.164.0/24 10.4.151.212 15'
    - '10.4.164.0/24 10.4.151.213 16'

####################
### 0.5-Time     ###
####################
ntp:
  timezone: Europe/Moscow
  srv: 10.10.10.1

####################
### 2.1-FreeIPA  ###
####################
FreeIPA:
  pass: 'P@ssw0rd'
  srv: s04dc1
  repl: s04dc2      


####################
### 3.1-Zabbix   ###
####################
# Сервер Zabbix
Zabbix:
  srv: s04backup
  port: 8085
  db:
    user: user_zabbix
    password: P@ssw0rd
    name: db_zabbix
  agent: 2


####################
### 3.22-Ceph    ###
####################
Ceph:
  ver: 19.2.1
  nodes:
    - s04ceph1
    - s04ceph2
    - s04ceph3
  dev:
    - /dev/mapper/vg2-lv_cephosd
  net:
    interface: ens19 # 224
    network: 10.4.237.0/24
#   keepalived_IP: 10.4.151.204
#   dashboard_port: 8080

########################
### 3.27-PostgreSQL   ###
########################
PostgreSQL:
  etcd_srv:
    - s04etcd1
    - s04etcd2
    - s04etcd3
  pg_srv:
    - s04db1
    - s04db2
  device: /dev/sdb1
  # keepalived_IP: 10.150.0.110
  password: postgres


#####################
### 3.28-Nexus    ###
#####################
Nexus:
  srv: s04registry
  path: /opt/nexus


#####################
### 3.29-K8s      ###
#####################
k8s:
  ver: '1.32'
  masters:
    - s04master1
    - s04master2
    - s04master3
  workers:
    - s04worker1
    - s04worker2
    - s04worker3
  subdomain: emercore
  keepalived_IP: 10.4.151.205 ## Установка Keepalived на серверах masters
  # haproxy_port: 8443 ## Устанавливается HAProxy на серверах masters
  pod_subnet: 10.4.160.0/22 ## подсеть выделенная для подов
  service_subnet: 10.4.164.0/24 ## подсеть выделенная для сервисов
  core_dns: 10.4.164.10 ## адрес внутреннего днс куба (первые 3 октета из подсети сервисов, последний - 10)
  metallb_pool: 10.4.151.28-10.4.151.29 ## пул адресов для MetalLB
  rwo_sc: csi-rwo-sc
  rwx_sc: csi-rwx-sc
  ceph_csi: 1  ## Количество провиженоров 'CephRBD' и 'CephFS'. Должно равняться количеству воркеров. Если равно '0' устанавливается ниже указанные провиженеры
  lvm_provisioner:    ## LVM RWO # Уcтанавливатся вместо 'CephRBD'
    namespace: csi-lvm-system
    device: /dev/sdb
    vg_name: vg01
  nfs_provisioner:    ## NFS RWX # Уcтанавливатся вместо 'CephFS'
    namespace: csi-nfs-system
    disk_size: 50Gi
    server_ip:
    path:

...