---

# Шахтерск

remote_user: admin1
ansible_ssh_user: admin1
ansible_ssh_pass: Sph@era92
ansible_ssh_private_key_file: ./ssh/admin1/id_rsa.pub

domain: 'em.shahtersk.lan'

Net:
  network: 192.168.0.0/24
  net: 192.168.0.0
  mask: 255.255.255.0
  gateway: 192.168.0.1
  bind:
    - 192.168.0.1
    - 77.88.8.8
    - 8.8.8.8

####################
### 0.5-Time     ###
####################
ntp:
  timezone: Europe/Moscow
  srv:
    - 192.168.0.1

####################
### 2.1-FreeIPA  ###
####################
# FreeIPA:
  # pass: 'P@ssw0rd'
  # srv: s04dc1
  # repl: s04dc2      


####################
### 3.1-Zabbix   ###
####################
# Сервер Zabbix
# Zabbix:
  # srv: s04backup
  # port: 8085
  # db:
    # user: user_zabbix
    # password: P@ssw0rd
    # name: db_zabbix
  # agent: 2


####################
### 3.22-Ceph    ###
####################
# Ceph:
  # ver: 19.2.1
  # nodes:
    # - s04ceph1
    # - s04ceph2
    # - s04ceph3
  # dev:
    # - /dev/mapper/vg2-lv_cephosd
  # net:
    # interface: ens19 # 224
    # network: 10.4.237.0/24
#   keepalived_IP: 10.4.151.204
#   dashboard_port: 8080

#####################
### 3.28-Registry ###
#####################
# registry:
  # srv: s04registry
  # path: /mnt/data
  # port: 5000

#####################
### 3.29-K8s      ###
#####################
k8s:
  ver: '1.32'
  masters:
    - s04master1
    - s04master2
    - s04master3
  workers:
    - s04worker1
    - s04worker2
    - s04worker3
  keepalived_IP: 10.4.151.205 ## Установка Keepalived на серверах masters
  # haproxy_port: 8443 ## Устанавливается HAProxy на серверах masters
  pod_subnet: 10.4.160.0/22 ## подсеть выделенная для подов
  service_subnet: 10.4.164.0/24 ## подсеть выделенная для сервисов
  core_dns: 10.4.164.10 ## адрес внутреннего днс куба (первые 3 октета из подсети сервисов, последний - 10)
  rwo_sc: csi-rwo-sc
  rwx_sc: csi-rwx-sc
  ceph_csi: 1  ## Количество провиженоров 'CephRBD' и 'CephFS'. Должно равняться количеству воркеров. Если равно '0' устанавливается ниже указанные провиженеры
  lvm_provisioner:    ## LVM RWO # Уcтанавливатся вместо 'CephRBD'
    namespace: csi-lvm-system
    device: /dev/sdb
    vg_name: vg01
  nfs_provisioner:    ## NFS RWX # Уcтанавливатся вместо 'CephFS'
    namespace: csi-nfs-system
    disk_size: 50Gi
    server_ip:
    path:

...