---
- name: Create namespace for registry
  k8s:
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ registry_namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present

#- name: Create passwd
#  shell: kubectl create secret docker-registry secret --docker-server registry.{{ net_local_domain }} --docker-username registry --docker-password registry --dry-run=client -oyaml | grep dockerconfigjson | cut -d " " -f 4
#  register: registry_auth
#  run_once: true

#- name: Create auth for registry
#  k8s:
#    kubeconfig: "/home/{{ local_admin }}/.kube/config"
#    definition:
#      apiVersion: v1
#      data:
#        htpasswd: "{{ registry_auth.stdout }}"
#      kind: Secret
#      metadata:
#        creationTimestamp: null
#        name: registry-auth
#        namespace: "{{ registry_namespace }}"
#    state: present

- name: Create secret for registry
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/registry-auth.yaml') }}"

- name: Create cert for registry
  k8s:
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: registry-cert
        namespace: "{{ registry_namespace }}"
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ tls_crt }}"
        tls.key: "{{ tls_key }}"
    state: present

- name: Create svc for registry
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/registry-svc.yaml') }}"

- name: Create PVC for registry
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/registry-pvc.yaml') }}"

- name: Create PV for registry
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/registry-pv.yaml') }}"

- name: Create ingress for registry
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/registry-ing.yaml') }}"

- name: Create registry
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/registry.yaml') }}"