---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep DrWeb-client
  register: version
  ignore_errors: yes

#- name: Установка пакетов
#  apt:
#    name:
#    - astra-digsig-oldkeys
#    state: latest
#    update_cache: yes
#  when: version.stdout != relis

#- name: Копирование необходимых пакетов
#  copy:
#    src: DrWeb-client/
#    dest: /opt/distr/DrWeb-client/
#    mode: '0777'
#    directory_mode: yes
#  when: version.stdout != relis

#- name: Удалим сертификат сервера
#  file:
#    path: /opt/distr/DrWeb-client/drwcsd-certificate.pem
#    state: absent
#  when: version.stdout != relis  

#- name: Скачиваем сертификат сервера
#  get_url:
#    url: "https://{{ DrWeb_Server }}:9081/install/drwcsd-certificate.pem"
#    dest: //opt/distr/DrWeb-client/drwcsd-certificate.pem
#    validate_certs: no
# when: version.stdout != relis

- name: Отключение от сервера
  shell: drweb-ctl esdisconnect
  when: version.stdout != relis
  ignore_errors: yes

- name: Удаление старого клиента
  shell: 'cd /opt/drweb.com/bin && echo Y | ./uninst.sh'
  when: version.stdout != relis
  ignore_errors: yes

- name: Установка клиента FSTEK
  shell: cd /opt/distr/DrWeb-client/fstek && ./drweb-file-servers_11.1.0-fstek.run -- --non-interactive
  when: domain == 'in' and version.stdout != relis
  ignore_errors: yes

- name: Установка клиента МО
  shell: cd /opt/distr/DrWeb-client/mo && ./drweb-file-servers_11.1.0-mo.run -- --non-interactive
  when: ( domain == 'ns' or domain == 'ss' or domain == 'test' ) and version.stdout != relis
  ignore_errors: yes

- name: Подключение клиента к серверу
  shell: "drweb-ctl esconnect {{ DrWeb_Server }} --Newbie --Certificate /opt/distr/DrWeb-client/drwcsd-certificate.pem"
  when: version.stdout != relis

- name: Создание папки ключей
  file:
    state: directory
    path: "/etc/digsig/keys/legacy/keys"
  when: version.stdout != relis

- name: Загрузка сертификата антивирурса для работы в ЗПС
  copy:
    src: '/opt/drweb.com/share/doc/{{ item }}'
    dest: /etc/digsig/keys/legacy/keys/
    mode: 0444
    remote_src: yes
  with_items:
  - digsig.gost.gpg
  - digsig.primary_key_2010.gpg
  when: version.stdout != relis

- name: Инициализация установленных ключей
  shell: update-initramfs -u -k all
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  shell: "sed -i '/DrWeb-client/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  become: true
  when: version.stdout != relis
