---

- name: 3.22.2 | Проверка наличия 'Ceph'
  stat:
    path: /usr/bin/ceph
  register: ceph_result
  ignore_errors: yes

- name: 3.22.2 | Инсталляция 'ceph-deploy'
  apt:
    name:
      - python
      - ceph-deploy
      - ceph-mgr-dashboard
      - lvm2
  when: not ceph_result.stat.exists

...