---

- name: Проверка наличия файла '/etc/apt/sources.list.d/sources.list'
  stat:
    path: /etc/apt/sources.list.d/sources.list
  register: sources_result

- name: Создания локального репозитория
  block:

  - name: Создание папок репозиториев
    file:
      state: directory
      path: '{{ item }}'
      mode: 0755
    with_items:
    - /srv
    - /srv/iso
    - /srv/repo

  - name: Копирование ISO образов AstraLinux
    copy:
      src: '../../../../iso/AstraLinux/1.6/{{ item }}.iso'
      dest: '/srv/iso/'
      force: no
    with_items:
    - '{{ repo.name_iso }}'

  - name: Создание папок репозиториев
    file:
      state: directory
      path: '/srv/repo/{{ item }}'
      mode: 0755
    with_items:
    - '{{ repo.name_iso }}'

  - name: Монтирование образов ОС
    mount:
      path: '/srv/repo/{{ item }}'
      src: '/srv/iso/{{ item }}.iso'
      fstype: iso9660
      opts: ro,auto
      state: mounted
    with_items:
    - '{{ repo.name_iso }}'

  - name: Удаление содержимого файла '/etc/apt/sources.list'
    file:
      path: /etc/apt/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Удаление содержимого файла '/etc/apt/sources.list.d/sources.list'
    file:
      path: /etc/apt/sources.list.d/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Заполнение файла '/etc/apt/sources.list.d/sources.list'
    lineinfile:
      path: /etc/apt/sources.list.d/sources.list
      line: 'deb file:///srv/repo/{{ item}} {{ repo.dist }} {{ repo.res }}'
      state: present
    with_items:
    - '{{ repo.name_iso }}'

  when:
  - inventory_hostname == repo.srv 
  - not sources_result.stat.exists

- name: Проверка наличия файла '/etc/apache2-repo/sites-available/000-default.conf'
  stat:
    path: /etc/apache2-repo/sites-available/000-default.conf
  register: stat_result

- name: Настройка Apache2@repo
  block:

  - name: Инсталляция необходимых пакетов для сервера Apache
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: Удаление папок и файлов 'Apache2@repo'
    shell: '{{ item }}'
    with_items:
      - rm -rf /etc/apache2-repo
      - rm -rf /var/log/apache2-repo
      - rm -f /usr/local/sbin/*repo

  - name: Модифицируем файлы конфигурации 'Apache2@repo'
    shell: |
      sed -i "s/zero_if_notfound: no/zero_if_notfound: yes/g" /etc/parsec/mswitch.conf
      sh /usr/share/doc/apache2/examples/setup-instance repo
      sed -i "s/# AstraMode on/AstraMode off/g" /etc/apache2-repo/apache2.conf
      sed -i "s/Listen 80/Listen {{ repo.port }}/g" /etc/apache2-repo/ports.conf
      sed -i "s/;date.timezone =/date.timezone = {{ ntp.timezone }}/g" /etc/php/7.0/apache2/php.ini
      sed -i "s/post_max_size = 8M/post_max_size = 32M/g" /etc/php/7.0/apache2/php.ini
      sed -i "s/max_execution_time = 30/max_execution_time = 300/g" /etc/php/7.0/apache2/php.ini
      sed -i "s/max_input_time = 60/max_input_time = 300/g" /etc/php/7.0/apache2/php.ini

  - name: Очистка файла '/etc/apache2-repo/sites-available/000-default.conf'
    file:
      path: /etc/apache2-repo/sites-available/000-default.conf
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Добавление виртуального сервера
    blockinfile:
      dest: /etc/apache2-repo/sites-available/000-default.conf
      marker: '### repo ###'
      block: |
        <VirtualHost {{ hostvars[repo.srv].ansible_ssh_host }}:{{ repo.port }}>
           #ServerName {{repo.srv}}.{{ domain }}
           #ServerAlias repo
           ServerAdmin webmaster@localhost
           DocumentRoot /var/www/repo
        </VirtualHost>

  - name: Создание символьной ссылки на репозиторий
    file:
      src: /srv/repo
      dest: /var/www/repo
      state: link

  - name: Перезапуск службы 'Apache2@repo'
    service:
      name: apache2@repo
      enabled: yes
      state: restarted

  when:
  - inventory_hostname == repo.srv
  - not stat_result.stat.exists

- name: Подключение хостов к сетевому репозиторию
  block:

  - name: Удаление файла '/etc/apt/sources.list'
    file:
      path: /etc/apt/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Удаление файла '/etc/apt/sources.list.d/sources.list'
    file:
      path: /etc/apt/sources.list.d/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Заполняем файл '/etc/apt/sources.list.d/sources.list'
    lineinfile:
      path: /etc/apt/sources.list.d/sources.list
      line: 'deb http://{{ hostvars[repo.srv].ansible_ssh_host }}:{{ repo.port }}/{{ item}} {{ repo.dist }} {{ repo.res }}'
      state: present
    with_items:
    - '{{ repo.name_iso }}'

  when:
  - inventory_hostname != repo.srv
  - not sources_result.stat.exists

- name: Чтение версии установленного апдейта ОС
  shell: cat /etc/astra_update_version | grep 'Update 12'
  register: update_status
  ignore_errors: yes

- name: Обновление системы
  block:

  - name: Чтение версии установленного апдейта ОС
    shell: cat /etc/astra_update_version
    register: update_version_before
    ignore_errors: yes

  - name: Установка пакетов для обновления ОС
    apt:
      name:
      - astra-update
      - fly-astra-update
      state: latest
      update_cache: yes
    ignore_errors: yes

  - name: Обновление AstraLinux
    shell: 'astra-update -A -r'
#    shell: 'astra-update -A -T -K -r'
    ignore_errors: yes

  - name: Изменения файла 'etc/modprobe.d/blacklist-astra.conf'
    lineinfile:
      dest: /etc/modprobe.d/blacklist-astra.conf
      regexp: '{{ item.before }}'
      line: '{{ item.after }}'
    with_items:
    - { before: 'blacklist ast', after: '#blacklist ast'}
    - { before: 'blacklist mgag200', after: '#blacklist mgag200'}

  - name: Перезагрузка ОС
    reboot:
      msg: "Reboot"

  # - name: Установка нового ядра ОС
    # shell: |
      # set -e
      # pkgs=`dpkg -l 2> /dev/null | egrep "^ii\s*linux-image-[456]\.[[:digit:]]+\.[[:digit:]]+-[[:digit:]]+-" | cut -d " " -f3 | grep -v ^linux-image-$(uname -r | cut -d '-' -f1-2)`
      # [ -n "$pkgs" ] && apt remove $pkgs -y
      # rm -f /boot/old-*
    # ignore_errors: yes

  # - name: Перезагрузка ОС
    # reboot:
      # msg: "Reboot"

  # - name: Удаление старых ядер ОС
    # shell: apt -y autoremove
    # ignore_errors: yes

  when: update_status.stdout == ''

...