---

- name: Create namespace for logging
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "logging"
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present

- name: Добавление репозитория 'elastic' для helm
  kubernetes.core.helm_repository:
    name: elastic
    repo_url: "https://helm.elastic.co"

- name: Добавление репозитория 'bitnami' для helm
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Добавление репозитория 'fluent' для helm
  kubernetes.core.helm_repository:
    name: fluent
    repo_url: "https://fluent.github.io/helm-charts"

- name: Install templates cm
  kubernetes.core.k8s:
    state: present
    namespace: logging
    force: false
    kubeconfig: "~/.kube/config"
    definition: 
      - "{{ lookup('file', 'elasticsearch-ilm-and-index-templates.yaml') | from_yaml }}"

- name: Развертывание 'elasticsearch (19.5.6)'
  kubernetes.core.helm:
    name: elasticsearch
    release_namespace: logging
    chart_ref: bitnami/elasticsearch
    chart_version: 19.5.6
    values: "{{ lookup('file', 'chart_bitnami-elasticsearch_19.5.6_values.yaml') | from_yaml }}"

- name: Развертывание 'fluent-bit (0.21.5)'
  kubernetes.core.helm:
    name: fluent-bit
    release_namespace: logging
    chart_ref: fluent/fluent-bit
    chart_version: 0.21.5
    values: "{{ lookup('file', 'chart_fluent_values.yaml') | from_yaml }}"

- name: Развертывание 'kibana (10.2.11)'
  kubernetes.core.helm:
    name: kibana
    release_namespace: logging
    chart_ref: bitnami/kibana
    chart_version: 10.2.11
    values: "{{ lookup('file', 'chart_bitnami-kibana_10.2.11_values.yaml') | from_yaml }}"

...