---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep OSSec-client
  register: version
  ignore_errors: yes

- name: Установка необходимых пакетов
  apt:
    name:
    - ossec-hids-agent
    state: latest
    update_cache: yes
  when: version.stdout != relis
  ignore_errors: yes

- name: Настройка конфигурации /var/ossec/etc/ossec.conf
  lineinfile:
    dest: /var/ossec/etc/ossec.conf
    regexp: "<server-ip>"
    line: "    <server-ip> {{ ossec_srv }} <server-ip>"
  when: version.stdout != relis

- name: Перезапускаем службу 'ossec-hids-agent'
  shell: service ossec-hids-agent restart
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i '/OSSec-client/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  when: version.stdout != relis
  ignore_errors: yes
