---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep RebusSov-server
  register: version
  ignore_errors: yes

- name: Установка необходимых пакетов
  apt:
    update_cache: yes
    name:
    - libcrypto++6
    - insserv
    - libqtwebkit4
    - astra-digsig-oldkeys
    - libqt4-svg
    state: latest
  when: version.stdout != relis

- name: Копирование необходимых пакетов
  copy:
    src: rebus-sov/
    dest: /opt/distr/RebusSov-server/
    mode: '0777'
    force: yes
    directory_mode: yes
  when: version.stdout != relis

- name: Деинсталяция RebusSov
  shell: "/opt/distr/RebusSov-server/install -d"
  when: version.stdout != relis
  ignore_errors: yes

- name: Установка ключа
  copy:
    src: rebus-sov/cps.tver_pub_key.gpg
    dest: /etc/digsig/keys/legacy/keys/
    mode: '0444'
  when: version.stdout != relis

- name: update-initramfs
  shell: update-initramfs -u -k all
  when: version.stdout != relis

- name: Инсталяция RebusSov
  shell: "/opt/distr/RebusSov-server/install -i srv -a 127.0.0.1 -p 6669 -b /opt/distr/RebusSov-server/initial.zip"
  when: version.stdout != relis

- name: Модифицируем файл конфигурации
  shell: "sed 's/network-manager/networking/' /etc/init.d/ipsAgentd"
  when: version.stdout != relis  

- name: Login & Password
  debug:
    msg: "Login:OBI  Password:supervis"
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i '/RebusSov-server/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  when: version.stdout != relis
  ignore_errors: yes