---
# tasks file for staff_monitoring
- name: Create namespace for monitoring
  tags: [staff, monitoring]
  kubernetes.core.k8s:
    kubeconfig: "~/.kube/config"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "monitoring"
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present

- name: Add helm repo prometheus
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"


- name: Deploy prometheus monitoring
  kubernetes.core.helm:
    name: prometheus
    release_namespace: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 43.2.1
    values: "{{ lookup('file', 'chart_kube-prometheus-stack_values.yaml') | from_yaml }}"


- name: Install dashboards for grafana
  kubernetes.core.k8s:
    state: present
    namespace: monitoring
    force: false
    kubeconfig: "~/.kube/config"
    definition: 
      - "{{ lookup('file', 'grafana_dashboard_ceph-cephfs.yaml') | from_yaml }}"
      - "{{ lookup('file', 'grafana_dashboard_ceph-cluster.yaml') | from_yaml }}"
      - "{{ lookup('file', 'grafana_dashboard_elasticsearch-cluster.yaml') | from_yaml }}"
      - "{{ lookup('file', 'grafana_dashboard_postgresql_database.yaml') | from_yaml }}"
      - "{{ lookup('file', 'grafana_dashboard_rabbitmq-overview.yaml') | from_yaml }}"
      - "{{ lookup('file', 'grafana_dashboard_redis-operator.yaml') | from_yaml }}"
      - "{{ lookup('file', 'grafana_dashboard_redis-overview.yaml') | from_yaml }}"
      - "{{ lookup('file', 'Prometheus_PodMonitor_Postgres.yaml') | from_yaml }}"
      - "{{ lookup('file', 'PrometheusRule_rabbitmq-cluster-operator.yaml') | from_yaml }}"
      - "{{ lookup('file', 'rabbitmq-servicemonitor.yaml') | from_yaml }}"

