global:
  storageClass: {{ k8s.rwo_sc }}

fullnameOverride: "kibana"

clusterDomain: {{ domain }}

plugins:
  - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/8.5.3/kibanaPrometheusExporter-8.5.3.zip
ingress:
  enabled: false
  hostname: kibana.{{ domain }}
  ingressClassName: "nginx"

metrics:
  enabled: true
  
  serviceMonitor:
    enabled: true  
    interval: "5s"
    labels:
      release: prometheus

elasticsearch:
  hosts:
    - elasticsearch
  port: "9200"
