---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep KAV-workstation
  register: version
  ignore_errors: yes

- name: Копирование необходимых пакетов
  copy:
    src: 'kesl-astra_11.1.0-3013.mod_amd64.deb'
    dest: /opt/distr/KAV-workstation/
    mode: '0777'
    force: no
    directory_mode: yes
  when: version.stdout != relis

- name: Копирование конфигурации
  copy:
    src: '{{ domain }}.conf'
    dest: /opt/distr/KAV-workstation/
    mode: '0777'
    force: no
    directory_mode: yes
  when: version.stdout != relis

- name: Копирование лицензионного ключа
  copy:
    src: '5770D5E8.key'
    dest: /opt/distr/KAV-workstation/
    mode: '0777'
    force: no
    directory_mode: yes
  when: version.stdout != relis

- name: Установка необходимых пакетов
  apt:
    name:
    - astra-digsig-oldkeys
    state: latest
    update_cache: yes
  when: version.stdout != relis

- name: Инсталляция
  shell: "dpkg -i /opt/distr/KAV-workstation/kesl-astra_11.1.0-3013.mod_amd64.deb"
  when: version.stdout != relis

- name: Конфигурирование
  shell: "/opt/kaspersky/kesl/bin/kesl-setup.pl --autoinstall=/opt/distr/KAV-workstation/{{ domain }}.conf"
  when: version.stdout != relis

- name: Создание файла kaspersky_astra_pub_key.gpg
  copy:
    src: '/opt/kaspersky/kesl/shared/kaspersky_astra_pub_key.gpg'
    dest: '/etc/digsig/keys/legacy/kaspersky_astra_pub_key.gpg'
    mode: '0644'
  when: version.stdout != relis

- name: Обновите диски оперативной памяти
  become: true
  shell: "update-initramfs -u -k all"
  when: version.stdout != relis

- name: Запишем версию ПО если ее не разу не было (Install)
  become: true
  shell: "echo '{{ relis }}' >> /opt/distr/software.conf"
  when: version.stdout == ""
  ignore_errors: yes

- name: Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i 's/{{version.stdout}}/{{ relis }}/g' /opt/distr/software.conf"
  when: version.stdout != relis
  ignore_errors: yes
