---
- name: Проверка наличия файла '/root/.ssh/id_rsa'
  stat:
    path: /root/.ssh/id_rsa
  register: id_rsa_result

- name: Добавление прав root-у на доступ по ssh и соседние ключей
  block:
  
  - name: Внесение изменений в /etc/ssh/sshd_config
    lineinfile: 
      dest: /etc/ssh/sshd_config
      regexp: '^{{ item.src }}'
      insertbefore: BOF
      line: '{{ item.dest }}'
    loop:
      - { src: "#PermitRootLogin", dest: "PermitRootLogin yes" }

  - name: change password
    user:
      name: root
      state: present
      password: "{{ root_pass | password_hash('sha512') }}"

  - name: Перезапуск службы ssh
    service:
      name: ssh
      enabled: yes
      state: restarted

  - name: Инсталляция пакета 'sshpass'
    apt:
      name:
      - sshpass
      state: latest
      update_cache: yes

  - name: Удаление ssh ключей
    shell: rm -Rf /root/.ssh/id_rsa*
    ignore_errors: yes

  - name: Генерация ssh ключей '/root/.ssh/id_rsa'
    shell: echo -e "\n" | ssh-keygen -q -t rsa -f /root/.ssh/id_rsa -C "" -N ""
  
  when: not id_rsa_result.stat.exists

- name: Копирование ключей на соседние машины
  shell: |
    {% for item in ansible_play_batch %}
    sshpass -p '{{ root_pass }}' ssh-copy-id -f -i ~/.ssh/id_rsa.pub -o "StrictHostKeyChecking=no" root@{{ hostvars[item].ansible_ssh_host }}
    {% endfor %}
