---

- name: Проверка наличия файла '/etc/keepalived/keepalived.conf'
  stat:
    path: /etc/keepalived/keepalived.conf
  register: keepalived_result
  ignore_errors: yes

- name: Установка 'keepalived'
  block:

  - name: Установка пакета 'Keepalived'
    apt:
      update_cache: yes
      pkg:
      - keepalived

  - name: Очистка файла '/etc/keepalived/keepalived.conf'
    file:
      path: /etc/keepalived/keepalived.conf
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Получить список сетевых интерфейсов
    shell: |
      ip link show | grep BROADCAST | awk '{print $2}' | sed 's/.$//'
    register: device_list

  - name: Создание массива сетевых интерфейсов
    set_fact:
      interfaces: "{{ device_list.stdout_lines | list }}"

  - name: Получение количества элементов в списке интерфейсов
    set_fact:
      interfaces_length: "{{ interfaces | length }}"

  - name: Внесение изменений в файл '/etc/keepalived/keepalived.conf'
    blockinfile:
      path: /etc/keepalived/keepalived.conf
      create: yes
      state: present
      block: |
        vrrp_instance Virtual_IP {
          interface {{ interfaces[0] }}
          virtual_router_id 230
          state BACKUP
          priority {{ 255 - ansible_ssh_host.split('.')[3] | int }}
          advert_int 1
          unicast_src_ip primary_private_IP
          unicast_peer {
            secondary_private_IP
            }
          authentication {
            auth_type PASS
            auth_pass Keepalived_SecPassWord
            }
          virtual_ipaddress {
            {{ k8s.keepalived_IP }}/24 dev {{ interfaces[0] }} label {{ interfaces[0] }}:0
            }
          }

  - name: Внесение изменений в файл '/etc/keepalived/keepalived.conf'
    lineinfile:
      dest: /etc/keepalived/keepalived.conf
      regexp: 'state BACKUP'
      line: '  state MASTER'
    when: inventory_hostname == k8s.masters[0]

  - name: Запускаем службу 'Keepalived'
    service:
      name: keepalived
      state: restarted
      enabled: yes

  when:
    - not keepalived_result.stat.exists
    - inventory_hostname in k8s.masters

...