---

- name: Проверка наличия файла '/lib/systemd/system/kubelet.service.d/10-kubeadm.conf'
  stat:
    path: /lib/systemd/system/kubelet.service.d/10-kubeadm.conf
  register: kubernetes_result
  ignore_errors: yes

- name: Установка 'kubernetes'
  block:

  - name: Установка вспомогательных пакетов
    apt:
      update_cache: true
      package:
        - python3-pip
        - python3-kubernetes
        - bind9-utils
        - curl
        - htop
        - iftop
        - git
        - wget
        - apt-transport-https
        - ca-certificates
        - gpg
        - tar
        - net-tools

  - name: Установка модулей Python
    pip:
      executable: pip3
      extra_args: --no-warn-script-location --break-system-packages
      name:
        - ansible
        - ansible-core
        - ansible-lint
        - kubernetes
        - collection
        - docker

  - name: Загрузка публичного ключа подписи репозиториев 'Kubernetes'
    shell: |
      rm /etc/apt/keyrings/kubernetes-apt-keyring.gpg -f
      curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

  - name: Добавление репозиторя 'Kubernetes'
    shell: |
      echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

  - name: Загрузка публичного ключа подписи репозиториев 'Сri-O'
    shell: |
      rm /etc/apt/keyrings/cri-o-apt-keyring.gpg -f      
      curl -fsSL https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg

  - name: Добавление репозиторя 'Сri-O'
    shell: |
      echo 'deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/cri-o.list

  - name: Установка 'Kubernetes v1.31' и 'Сri-O v1.31' на мастере
    apt:
      update_cache: true
      state: present
      package:
        - kubelet
        - kubeadm
        - kubectl
        - cri-o
    when: inventory_hostname in k8s.masters

  - name: Установка 'Kubernetes v1.31' и 'Сri-O v1.31' на воркере
    apt:
      update_cache: true
      state: present
      package:
        - kubelet
        - kubeadm
        - cri-o
    when: inventory_hostname in k8s.workers

  - name: Запуск службы 'Сri-O'
    service: 
      name: crio
      state: restarted
      enabled: yes

  - name: Настройка имени домена в конфигурации 'kubelet'
    shell: sed -i "s/--cluster-domain=cluster.local/--cluster-domain={{ domain }}/" /lib/systemd/system/kubelet.service.d/10-kubeadm.conf

  - name: Настройка типа авторизации в конфигурации 'kubelet'
    shell: sed -i "s/KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook/KUBELET_AUTHZ_ARGS=--authentication-token-webhook=true --authorization-mode=Webhook/" /lib/systemd/system/kubelet.service.d/10-kubeadm.conf

  - name: Инсталляция диспетчера пакетов 'Helm v3.16.1'
    shell: |
      wget https://get.helm.sh/helm-v3.16.1-linux-amd64.tar.gz
      tar xvf helm-v3.16.1-linux-amd64.tar.gz
      sudo mv linux-amd64/helm /usr/local/bin
      rm helm-v3.16.1-linux-amd64.tar.gz
      rm -rf linux-amd64
    when: inventory_hostname in k8s.masters

  - name: Перезагрузка ОС
    reboot:
      msg: 'Reboot'

  when: not kubernetes_result.stat.exists

...

# https://github.com/helm/helm/releases