---
# helm repo add rabbitmq-operator https://charts.bitnami.com/bitnami
# helm repo list
# helm repo update
# helm search repo -l rabbitmq-operator/rabbitmq-cluster-operator | head -20
# helm show values rabbitmq-operator/rabbitmq-cluster-operator --version 4.3.24 > rabbitmq-operator.yaml

- name: Чтение статуса 'RabbitMQ'
  shell: kubectl get pods -n staff | grep 'rabbitmq' | grep 'Running'
  register: status_rabbitmq
  become: false
  ignore_errors: yes

- name:
  block:

  - name: Добавление репозитория 'rabbitmq-operator' для Helm
    kubernetes.core.helm_repository:
      name: rabbitmq-operator
      repo_url: https://charts.bitnami.com/bitnami
      force_update: true
    become: false

  - name: Развертывание 'rabbitmq-operator (4.3.24)'
    kubernetes.core.helm:
      name: rabbitmq-operator
      release_namespace: staff
      chart_ref: rabbitmq-operator/rabbitmq-cluster-operator
      chart_version: 4.3.24
      values: "{{ lookup('template', 'helm_charts/rabbitmq-operator.yaml') | from_yaml }}"
      force: true
    become: false

  when: status_rabbitmq.stdout == ''

...