---

- name: Проверка установки 'sshpass'
  command: which sshpass
  register: sshpass_check
  ignore_errors: yes

- name: Инсталляция пакета 'sshpass'
  dnf:
    name:
      - sshpass
  when: sshpass_check.rc != 0

- name:
  block:

#  - name: Внесение изменений в конфигурационныйе файл '/etc/ssh/ssh_config'
#    lineinfile:
#      dest: /etc/ssh/ssh_config
#      regexp: 'StrictHostKeyChecking'
#      line: '    StrictHostKeyChecking no'

  - name: Внесение изменений в конфигурационныйе файл '/etc/ssh/sshd_config'
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '{{ item.old }}'
      line: '{{ item.new }}'
    loop:
    - { old: "PubkeyAuthentication",            new: "PubkeyAuthentication yes        # разрешить аутентификацию по ключу" }
#    - { old: "PermitEmptyPasswords",            new: "PermitEmptyPasswords no         # запретить пустые пароли" }
#    - { old: "PasswordAuthentication",          new: "PasswordAuthentication no       # отключить вход по паролю" }
#    - { old: "PermitRootLogin",                 new: "PermitRootLogin yes             # отключить вход root" }

  - name: Перезапуск службы 'sshd'
    service:
      name: sshd
      state: restarted

...