---
- name: Firefox | Создадим файл версий установленного ПО
  file:
    path: /etc/software.conf
    state: touch

- name: Firefox | Чтение версии установленного ПО
  shell: cat /etc/software.conf | grep Firefox
  register: version
  ignore_errors: yes

- name: Firefox | Copy kerberos preferences
  copy:
    src: "kerberos.js"
    dest: "/usr/lib/firefox/browser/defaults/preferences/"
    owner: "root"
    group: "root"
    mode: '644'
  when: version.stdout != relis

- name: Firefox | Копирование сертификата
  copy:
    src: gca.crt
    dest: /usr/local/share/ca-certificates/
    mode: '0644'
  when: version.stdout != relis

- name: Firefox | Обновим список сертификатов
  shell: sudo update-ca-certificates
  when: version.stdout != relis

- name: Firefox | Копирование пакетов со шрифтами
  copy:
    src: deb
    dest: /tmp/Firefox
    mode: '700'
    force: no
    directory_mode: yes
  when: version.stdout != relis

- name: Firefox | Установка шрифтов
  shell: "{{item}}"
  loop:
    - 'apt --fix-broken install -y'
    - 'apt install ibus ibus-gtk3 -y'
    - 'dpkg -i /tmp/Firefox/deb/*.deb'
#    - 'echo "export GTK_IM_MODULE=ibus" >> ~/.bashrc'
#    - 'echo "export XMODIFIERS=@im=ibus" >> ~/.bashrc'
#    - 'echo "export QT_IM_MODULE=ibus" >> ~/.bashrc'
#    - 'echo "ibus-daemon -d -x -r" >> ~/.profile'
#    - 'echo "export GTK_IM_MODULE=ibus" >> /etc/skel/.bashrc'
#    - 'echo "export XMODIFIERS=@im=ibus" >> /etc/skel/.bashrc'
#    - 'echo "export QT_IM_MODULE=ibus" >> /etc/skel/.bashrc'
#    - 'echo "ibus-daemon -d -x -r" >> /etc/skel/.profile'
  when: version.stdout != relis

- name: Firefox | Запишем версию ПО если ее не разу не было (Install)
  become: true
  shell: "echo '{{ relis }}' >> /etc/software.conf"
  when: version.stdout == ""
  ignore_errors: yes

- name: Firefox | Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i 's/{{version.stdout}}/{{ relis }}/g' /etc/software.conf"
  when: version.stdout != relis
  ignore_errors: yes
