---

- name: Установка и настройка Zabbix сервер
  block:

  - name: Проверка наличия установленного Zabbix
    stat:
      path: /etc/zabbix/zabbix_server.conf.d/zabbix_server.conf
    register: zabbix_result


  - name: Установка и настройка Zabbix сервер
    block:

    - name: Инсталляция необходимых пакетов для сервера
      apt:
        name:
        - apache2
        - postgresql-9.6
        - postgresql-se-test-9.6
        - libapache2-mod-php7.0
        - php7.0-pgsql
        - ipmitool
        - zabbix-frontend-php
        - zabbix-server-pgsql
        - ldap-utils
        - iperf
        - snmp
        - snmpd
        - snmptt
        - snmptrapd
        state: latest
        update_cache: yes

    - name: Удаление папок и файлов
      shell: '{{ item }}'
      with_items:
      - rm -rf /etc/apache2-zabbix
      - rm -rf /var/log/apache2-zabbix
      - rm -f /usr/local/sbin/*zabbix

    - name: Модифицируем файл '/etc/default/snmptrapd'
      shell: sed -i "s/TRAPDRUN=no/TRAPDRUN=yes/g" /etc/default/snmptrapd

    - name: Изменение конфигурации SNMPTrap /etc/snmp/snmptrapd.conf
      blockinfile:
        dest: /etc/snmp/snmptrapd.conf
        marker: '### zabbix ###'
        block: |
          authCommunity log,execute,net public
          traphandle default /usr/sbin/snmptthandler

    - name: Изменение конфигурации SNMPTrap /etc/snmp/snmptt.ini
      blockinfile:
        dest: /etc/snmp/snmptt.ini
        marker: '### zabbix ###'
        block: |
          mode = daemon
          net_snmp_perl_enable = 1
          mibs_environment = ALL
          date_time_format = %H:%M:%S %Y/%m/%d
          log_enable = 1
          log_file = /var/log/snmptt/snmptt.log
          unknown_trap_log_enable = 1
          unknown_trap_log_file = /var/log/snmptt/snmpttunknown.log

    - name: Изменение конфигурации SNMPTrap /etc/snmp/snmptt.conf
      blockinfile:
        dest: /etc/snmp/snmptt.conf
        marker: '### zabbix ###'
        block: |
          EVENT general .* "General event" Normal
          FORMAT ZBXTRAP $aA $1 $2 $3

    - name: Модифицируем файлы конфигурации
      shell: |
        sed -i "s/zero_if_notfound: no/zero_if_notfound: yes/g" /etc/parsec/mswitch.conf
        sh /usr/share/doc/apache2/examples/setup-instance zabbix
        sed -i "s/# AstraMode on/AstraMode off/g" /etc/apache2-zabbix/apache2.conf
        sed -i "s/Listen 80/Listen {{ zabbix.port }}/g" /etc/apache2-zabbix/ports.conf
        sed -i "s/;date.timezone =/date.timezone = {{ ntp.timezone }}/g" /etc/php/7.0/apache2/php.ini
        sed -i "s/post_max_size = 8M/post_max_size = 32M/g" /etc/php/7.0/apache2/php.ini
        sed -i "s/max_execution_time = 30/max_execution_time = 300/g" /etc/php/7.0/apache2/php.ini
        sed -i "s/max_input_time = 60/max_input_time = 300/g" /etc/php/7.0/apache2/php.ini

    - name: Добавление виртуального сервера
      blockinfile:
        dest: /etc/apache2-zabbix/sites-available/000-default.conf
        marker: '### zabbix ###'
        block: |
          <VirtualHost {{ hostvars[zabbix.srv].ansible_ssh_host }}:{{ zabbix.port }}>
             ServerName zabbix.{{ domain }}
             ServerAlias zabbix
             ServerAdmin webmaster@localhost
             DocumentRoot /usr/share/zabbix
          </VirtualHost>

    - name: Внесение изменений в /etc/postgresql/9.6/main/pg_hba.conf
      shell: |
        sed -i '/Zabbix'/d /etc/postgresql/9.6/main/pg_hba.conf
        sed -i '/postgre/s/^/#/' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i '/is for Unix/i local	all		postgres				trust       # Настройки для Zabbix' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i '/0.0.0.0/s/^/#/' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i '/# IPv4/i local	all		all					trust       # Настройки для Zabbix' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i '/# IPv6/i host	zabbix		zabbix		127.0.0.1/32		trust       # Настройки для Zabbix' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i '/# IPv6/i host	all		all		{{ hostvars[zabbix.srv].ansible_ssh_host }}/24		trust       # Настройки для Zabbix' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i 's/##/#/g' /etc/postgresql/9.6/main/pg_hba.conf
        sed -i 's/max_connections = 100/max_connections = 512			    # Настройки для Zabbix/g' /etc/postgresql/9.6/main/postgresql.conf
        sed -i 's/shared_buffers = 128 MB/shared_buffers = 1GB			    # Настройки для Zabbix/g' /etc/postgresql/9.6/main/postgresql.conf

    - name: Предоставить пользователю postgres права читать мандатные метки и категории
      shell: |
        usermod -a -Gshadow postgres
        setfacl -d -mu:postgres:r /etc/parsec/macdb
        setfacl -R -mu:postgres:r /etc/parsec/macdb
        setfacl -mu:postgres:rx /etc/parsec/macdb
        setfacl -d -mu:postgres:r /etc/parsec/capdb
        setfacl -R -mu:postgres:r /etc/parsec/capdb
        setfacl -mu:postgres:rx /etc/parsec/capdb
        pdpl-user -l 0:0 zabbix

    - name: Перезапуск службы postgresql
      service:
        name: postgresql
        enabled: yes
        state: restarted

    - name: Создадим БД
      shell: |
        sudo -u postgres psql -c 'DROP DATABASE IF EXISTS zabbix;'
        sudo -u postgres psql -c 'DROP ROLE IF EXISTS zabbix;'
        sudo -u postgres psql -c 'CREATE DATABASE zabbix;'
        sudo -u postgres psql -c 'CREATE ROLE zabbix WITH LOGIN PASSWORD $$12345678$$;'
        sudo -u postgres psql -c 'GRANT ALL ON DATABASE zabbix to zabbix;'
        sudo zcat /usr/share/zabbix-server-pgsql/{schema,images,data}.sql.gz | sudo -u zabbix psql zabbix
        sed -i 's/# php_value date.timezone Europe\\/Riga/php_value date.timezone {{ ntp.timezone }}/g' /etc/apache2/conf-available/zabbix-frontend-php.conf
        ln -sf /etc/apache2/conf-available/zabbix-frontend-php.conf /etc/apache2/conf-enabled/zabbix-frontend-php.conf
      ignore_errors: yes

    - name: Перезапуск службы apache2@zabbix
      service:
        name: apache2@zabbix
        enabled: yes
        state: restarted

    - name: Копируем файл конфигурации zabbix_server_mniti.conf
      copy:
        src: zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf.d
        owner: root
        group: root
        mode: 0644

    - name: Копируем файл конфигурации PHP
      copy:
        src: zabbix.conf.php
        dest: /etc/zabbix
        mode: 0644

    - name: Включим службы и перезапустим службы
      service:
        name: '{{ item }}'
        state: restarted
        enabled: yes
      with_items:
      - snmpd
      - snmptt
      - snmptrapd
      - zabbix-server

    when: not zabbix_result.stat.exists

  - name: Проверка наличия файла '/etc/cron.d/backup_zabbix_cron'
    stat:
      path: /etc/cron.d/backup_zabbix_cron
    register: backup_result

  - name: Подготовка бекапа сервера Zabbix
    block:

    - name: Создадим папки для хранения бекапа
      file:
        state: directory
        mode: 0755
        recurse: yes
        path: '{{ zabbix.backup }}'


    - name: Копирование скриптов 'backup/restore'
      template:
        src: '{{ item }}.j2'
        dest: '/usr/local/bin/{{ item }}.sh'
        owner: root
        group: root
        mode: 0744
      with_items:
      - 'zabbix_backup'
      - 'zabbix_restore'

    - name: Создание политики лог-файла бекапа
      copy:
        src: backup_zabbix_logrotate.j2
        dest: /etc/logrotate.d/backup_zabbix_logrotate
        owner: root
        group: root
        mode: 0644

    - name: Создание расписания запуска бекапа
      copy:
        src: backup_zabbix_cron.j2
        dest: /etc/cron.d/backup_zabbix_cron
        owner: root
        group: root
        mode: 0644

    - name: Перезапуск службы Cron
      service:
        name: cron
        state: restarted

    when: not backup_result.stat.exists

  when: inventory_hostname == zabbix.srv



# Установка агента 'Zabbix'
- name: Проверка наличия установленного Zabbix агента
  stat:
    path: /etc/zabbix/zabbix_agentd.conf.d/zabbix_agent.conf
  register: zabbix_result

- name: Установка и настройка Zabbix агента
  block:

  - name: Установка необходимых пакетов
    apt:
      name:
      - zabbix-agent
      - smartmontools
      - iperf
      state: latest
      update_cache: yes

  - name: Добавляем пользователя zabbix как sudoers
    copy:
      src: zabbix
      dest: /etc/sudoers.d/
      mode: 0644

  - name: Копирование файла конфигурации
    copy:
      src: zabbix_agent.conf
      dest: /etc/zabbix/zabbix_agentd.conf.d/
      mode: 0644
      force: yes

  - name: Создадим папки для хранения скриптов
    file:
      state: directory
      mode: 0755
      recurse: yes
      path: /etc/zabbix/scripts

  - name: Копирование скриптов для шаблонов
    copy:
      src: '{{ item }}'
      dest: '/etc/zabbix/scripts/{{ item }}'
      force: yes
      mode: 0755
    with_items:
      - bacula_discovery.sh
      - bacula_check_job.sh
      - get_gpus_info.sh
      - bind_stats.py

  - name: Изменение zabbix_agent.conf
    shell: |
      sed -i 's/###HOSTNAME###/{{inventory_hostname}}.{{domain}}/g' /etc/zabbix/zabbix_agentd.conf.d/zabbix_agent.conf
      sed -i 's/1.1.1.1/{{ hostvars[zabbix.srv].ansible_ssh_host }}/g' /etc/zabbix/zabbix_agentd.conf.d/zabbix_agent.conf

  - name: Перезапуск служб
    service:
      name: zabbix-agent
      state: restarted
      enabled: yes

  when: not zabbix_result.stat.exists

...