---
- name: create folder
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  with_items:
  - "{{ Strom_fld }}"

- name: copy to etc
  copy:
    src: etc/init.d/recvmultiports
    dest: /etc/init.d/
    mode: '0766'

- name: copy to bin
  copy:
    src: usr/bin/RecvMultiPorts
    dest: /usr/bin/
    mode: '0766'

- name: template recvmultiports_cfg
  template:
    src: recvmultiports_cfg
    dest: /etc/recvmultiports_cfg
    mode: '0644'

- name: template scan_ports
  template:
    src: scan_ports
    dest: /etc/zftp/scan_ports.lst
    mode: '0644'

- name: autostart recvmultiports
  shell: update-rc.d recvmultiports defaults

- name: start service rcv
  service:
    name: recvmultiports
    state: restarted
