---
- name: Создание папки дистрибутивов
  file:
    path: /opt/distr/
    state: directory
    recurse: yes

- name: Изменим права доступа к папке
  shell: "chmod -R 777 /opt/distr"

- name: Создадим файл версий установленного ПО
  file:
    path: /opt/distr/software.conf
    mode: '0777'
    state: touch

- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep Astra-server
  register: version
  ignore_errors: yes

- name: Зададим имя хоста
  hostname:
    name: "{{ inventory_hostname }}.{{ domain }}"
    use: "systemd"
  when: version.stdout != relis

- name: Удалим файл hosts
  file:
    path: /etc/hosts
    state: "{{ item }}"
  with_items:
    - absent
    - touch
  when: version.stdout != relis

- name: Сздадим файл hosts
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0644
    owner: root
  when: version.stdout != relis

- name: Удалим файл sources.list
  file:
    path: /etc/apt/sources.list
    state: "{{ item }}"
  with_items:
    - absent
    - touch
  when: version.stdout != relis

- name: Сздадим файл sources.list
  copy:
    src: sources.list
    dest: /etc/apt/sources.list
    mode: 0644
    owner: root
  when: version.stdout != relis

- name: Сздадим файл aldpro
  copy:
    src: aldpro
    dest: /etc/apt/preferences.d/aldpro
    mode: 0644
    owner: root
  when: version.stdout != relis

- name: Обновим репозитории и OC
  shell: "{{ item }}"
  with_items:
    - astra-update -d
    - astra-update -A -T -r -n
    - astra-update -A -T -r
  when: version.stdout != relis

- name: Копирование файла interfaces
  template:
    src: interfaces
    dest: /etc/network/interfaces.d/interfaces
    owner: "root"
    group: "root"
    mode: "u=rw,g=r,o=r"
  when: version.stdout != relis

#- name: установка пакетов для создания bond0
#  apt:
#    name:
#    - ifenslave
#    state: latest
#    update_cache: yes
#  when: version.stdout != relis

- name: Удаление пакетов Network-Manager
  apt:
    name:
    - network-manager
    state: absent
    purge: yes
  when: version.stdout != relis

- name: Удалим файл resolv.conf
  file:
    path: /etc/resolv.conf
    state: "{{ item }}"
  with_items:
  - absent
  - touch
  when: version.stdout != relis
  
- name: Сздадим файл resolv.conf
  lineinfile:
    path: /etc/resolv.conf
    line: "{{ item }}"
  with_items:
    - nameserver {{ bind }}
    - search {{ domain }}
  when: version.stdout != relis

- name: Удаление лишних пакетов
  apt:
    autoremove: yes
  when: version.stdout != relis

- name: Перезагрузим хост
  reboot:
    reboot_timeout=300
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  shell: "sed -i '/Astra-server/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  when: version.stdout != relis



