---
- name: Инсталляция пакетов
  apt:
    name: '{{ pkgs }}'

- name: Внесение изменений в конфиг '/etc/iscsi/iscsid.conf'
  template:
    src: iscsid.conf.j2
    dest: /etc/iscsi/iscsid.conf

- name: Удаление имеющихся коннектов iSCSI
  file:
    state: absent
    path: '{{ item }}'
  with_items:
  - /etc/iscsi/nodes
  - /etc/iscsi/send_targets

- name: Сканированин iSCSI разделов на '{{ iscsi.ip }}'
  shell: |
    {% for item in iscsi.ip %}
    iscsiadm -m discovery -t st -p {{ item }}:3260
    {% endfor %}
    iscsiadm -m node -l
#   find /etc/iscsi/nodes/ -type f -exec sed -i 's/node.startup = manual/node.startup = automatic/g' {} \;
  ignore_errors: yes

- name: Перезапуск службы 'iscsid'
  service:
    name: iscsid
    state: restarted
    enabled: yes

- name: Копирование файла 'multipath.conf'
  copy:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
        
- name: Перезапуск службы 'multipathd'
  service:
    name: multipathd
    state: restarted
    enabled: yes

- name: Очистка кеша службы 'multipathd'
  shell: |
    multipath -F
    multipath -r

...