---
# tasks file for add_k8s_worker
- name: Get certificate hash
  shell: openssl x509 -in /etc/kubernetes/pki/ca.crt -pubkey -noout | openssl pkey -pubin -outform DER |openssl dgst -sha256| awk '{print $2}'
  register: k8s_certificate_hash
  tags: master_keys
  run_once: true
  become: true
  delegate_to: "{{ net_address_master01 }}"
  delegate_facts: true

- name: Get token
  shell: kubeadm token create
  register: k8s_join_token
  tags: master_keys
  run_once: true
  become: true
  delegate_to: "{{ net_address_master01 }}"
  delegate_facts: true

- name: Create pull config
  template:
    src: config.yml.j2
    dest: '/tmp/config.yml'
  delegate_to: "{{ item }}"
  run_once: true
  with_items:
     - '{{ net_address_worker01 }}'
     - '{{ net_address_worker02 }}'
     - '{{ net_address_worker03 }}'

- name: Pull images
  shell: kubeadm config images pull # --config /tmp/config.yml
  become: true
  become_method: sudo
  delegate_to: "{{ item }}"
  run_once: true
  ignore_errors: true
  with_items:
     - '{{ net_address_worker01 }}'
     - '{{ net_address_worker02 }}'
     - '{{ net_address_worker03 }}'

- name: Join workers
  shell: "kubeadm join kubernetes:6443 --token {{ k8s_join_token.stdout }} --discovery-token-ca-cert-hash sha256:{{ k8s_certificate_hash.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  run_once: true
  become: true
  become_method: sudo
  with_items:
     - '{{ net_address_worker01 }}'
     - '{{ net_address_worker02 }}'
     - '{{ net_address_worker03 }}'