---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "{{ k8s.rwo_sc }}"
provisioner: lvm.csi.metal-stack.io
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "linear"
