apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-provisioner-pvc
  namespace: "{{ k8s.nfs_provisioner.namespace }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ k8s.nfs_provisioner.disk_size }}
  storageClassName: {{ k8s.rwo_sc }}