---

# - name: Проверка наличия файла '/usr/local/bin/samba_client_demon.sh'
  # stat:
    # path: /usr/local/bin/samba_client_demon.sh
  # register: samba_client_demon_result

# - name: Развертывание клиентов Samba
  # block:

  # - name: Инсталляция пакетов (Samba) на клиентах кластера '{{ item.name }}'
    # apt:
      # name:
      # - cifs-utils
      # - libpam-mount

  # - name: Настройка конфигурационных файлов монтирования
    # shell: |
      # sed -i "/pam_mount.so/s/^/#/" /etc/pam.d/common-session
      # echo "session optional pam_mount.so" >> /etc/pam.d/login
      # echo "session optional pam_mount.so" >> /etc/pam.d/fly-dm

  # - name: Копирование конфигураций модуля автоматического монтирования
    # template:
      # src: pam_mount.j2
      # dest: /etc/security/pam_mount.conf.xml
      # force: yes

  # - name: Копирование скрипта демона
    # template:
      # src: samba_client_demon.j2
      # dest: /usr/local/bin/samba_client_demon.sh
      # mode: 0755
      # force: yes

  # - name: Копирование конфигурации демона
    # template:
      # src: samba_client_service.j2
      # dest: /etc/systemd/system/samba_client.service
      # mode: 0644
      # force: yes

  # - name: Перезагрузка systemd
    # shell: sudo systemctl daemon-reload

  # - name: Включим службу 'samba_client.service'
    # service:
      # name: samba_client.service
      # state: restarted
      # enabled: yes

  # when:
    # - not samba_client_demon_result.stat.exists

...