---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/gostsum/software.conf | grep gostsum
  register: version
  ignore_errors: yes

- name: Создание папки
  file:
    state: directory
    path: "/opt/distr/gostsum"
#  when: version.stdout != relis

- name: Удаление старых файлов
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - '/opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.files.txt'
  - '/opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.txt'
#  when: version.stdout != relis
  ignore_errors: yes

- name: Подсчёт контрольных сумм
  shell: "sudo gostsum --gost-2012 -r {{ item }} >> /opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.files.txt"
  with_items:
  - /boot/
  - /bin/
  - /sbin/
  - /etc/fstab
  - /etc/digsig/digsig_initramfs.conf
  - /etc/group
  - /etc/gshadow
  - /etc/init.d
  - /etc/inittab
  - /etc/network/interfaces
  - /etc/hosts.allow
  - /etc/hosts.deny
  - /etc/pam.d
  - /etc/passwd
  - /etc/rc0.d
  - /etc/rcl.d
  - /etc/rc2.d
  - /etc/гсЗ.d
  - /etc/rc4.d
  - /etc/rc5.d
  - /etc/rc6.d
  - /etc/rc.local
  - /etc/rcS.d
  - /etc/ssh
  - /etc/securetty
  - /etc/security
  - /opt/asm_stt3/bin
  - /opt/cprocsp/bin
  - /opt/cprocsp/lib
  - /opt/drweb.com/bin/
  - /opt/drweb.com/lib/
  - /opt/drwcs/
  - /opt/sgp/
  - /opt/kesl/
#  when: version.stdout != relis
  ignore_errors: yes

- name: Подсчёт контрольной суммы файла сумм
  shell: "gostsum --gost-2012 /opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.files.txt > /opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.txt"
#  when: version.stdout != relis
  ignore_errors: yes

- name: Запись результатов в папку ~/gostsum 
  fetch:
    src: "{{ item }}"
    dest: "~/gostsum/"
    flat: yes
  with_items:
  - '/opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.files.txt'
  - '/opt/distr/gostsum/{{ inventory_hostname }}.{{domain}}.txt'
#  when: version.stdout != relis
  ignore_errors: yes

- name: Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i '/gostsum/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
#  when: version.stdout != relis
  ignore_errors: yes
