---

- name: 3.29.12 | Получение количества элементов в списке 'workers'
  set_fact:
    workers_length: "{{ k8s.workers | default([]) | length }}"  

- name: 3.29.12 | Снимаем метку "отталкивания" подов
  shell: "kubectl taint nodes --all node-role.kubernetes.io/control-plane-"
  become: false
  when: workers_length == '0'

...