---

- name: 3.29.16 | Ping хоста '{{ item }}'
  shell: 'ping -c 1 {{ hostvars[item].ansible_ssh_host }} | grep Unreachable'
  register: ping_result
  ignore_errors: yes

- name: 3.29.16 | Хост доступен
  block:

  - name: 3.29.16 | Чтение статуса регистрации хоста '{{ item }}'
    shell: kubectl get nodes -A | grep '{{ item }}'
    register: status_reg
    become: false
    ignore_errors: yes

  - name: 3.29.16 | Хост не зарегистрирован
    block:

    - name: 3.29.16 | Получение хеша SSL ключа
      shell: openssl x509 -in /etc/kubernetes/pki/ca.crt -pubkey -noout | openssl pkey -pubin -outform DER | openssl dgst -sha256 | awk '{print $2}'
      register: k8s_certificate_hash
    
    - name: 3.29.16 | Получение токена кластера Kubernetes
      shell: kubeadm token create
      register: k8s_join_token

    - name: 3.29.16 | Создание 'config.yaml'
      template:
        src: config.j2
        dest: '/tmp/config.yaml'
      delegate_to: '{{ item }}'
       
    - name: 3.29.16 | Получение 'config.yaml'
      shell: kubeadm config images pull --config /tmp/config.yaml
      delegate_to: '{{ item }}'
    
    - name: 3.29.16 | Добавление воркера в кластер Kubernetes
      shell: "kubeadm join {{ hostvars[k8s.masters[0]].ansible_ssh_host }}:6443 --token {{ k8s_join_token.stdout }} --discovery-token-ca-cert-hash sha256:{{ k8s_certificate_hash.stdout }}"
      delegate_to: '{{ item }}'

    - name: 3.29.16 | Ожидание запуска воркера '{{ item }}'
      shell: |
        kubectl get nodes -A | grep '{{ item }}' | grep Ready
      register: result
      until: result.rc == 0
      retries: 60
      delay: 10
      become: false

    when: status_reg.stdout == ''

  when: ping_result.stdout == ''

...