---

- name: 3.29.33 | Чтение статуса 'rabbitmq-operator'
  shell: kubectl get pod -n staff | grep 'rabbitmq-operator' | grep 'Running'
  register: status_rabbitmq
  become: false
  ignore_errors: yes

- name:
  block:

  - name: 3.29.33 | Чтение namespace 'staff'
    shell: kubectl get namespace staff | grep 'Active'
    register: status_namespace
    become: false
    ignore_errors: yes

  - name: 3.29.33 | Создание пространства имен 'staff'
    kubernetes.core.k8s:
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: staff
          labels:
            pod-security.kubernetes.io/enforce: privileged
      state: present
    when: status_namespace.rc == 1

  - name: 3.29.33 | Развертывание из сетевого репозитория
    block:

    - name: 3.29.33 | Добавление репозитория 'bitnami' для Helm
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
####### repo_url: https://charts.bitnami.com/bitnami
        force_update: true
      become: false

    - name: 3.29.33 | Развертывание 'rabbitmq-operator v3.2.8'
      kubernetes.core.helm:
        name: rabbitmq-operator
        release_namespace: staff
        chart_ref: bitnami/rabbitmq-cluster-operator
        chart_version: 3.2.8
        values: "{{ lookup('template', 'Helm_Charts/rabbitmq-cluster-operator.yaml') | from_yaml }}"
        force: true
      become: false

    when: registry.srv is not defined

  - name: 3.29.33 | Развертывание из локального репозитория
    block:

    - name: 3.29.33 | Добавление локального репозитория 'registry-local'
      kubernetes.core.helm_repository:
        name: registry-local
        repo_url: http://{{ hostvars[registry.srv].ansible_ssh_host }}:{{ registry.port }}/helm
        force_update: true
      become: false

    - name: 3.29.33 | Развертывание 'rabbitmq-operator v3.2.8'
      kubernetes.core.helm:
        name: rabbitmq-operator
        release_namespace: staff
        chart_ref: registry-local/rabbitmq-cluster-operator
        chart_version: 3.2.8
        values: "{{ lookup('template', 'Helm_Charts/rabbitmq-cluster-operator.yaml') | from_yaml }}"
        force: true
      become: false

    when: registry.srv is defined

  - name: 3.29.31 | Ожидание запуска 'rabbitmq-operator'
    shell: |
      kubectl get pod -n staff | grep 'rabbitmq-operator' | grep 'Running'
    register: result
    until: result.rc == 0
    retries: 60
    delay: 10
    become: false

  when: status_rabbitmq.rc == 1

...