---

- name: 3.29.35 | Чтение статуса 'elasticsearch'
  shell: kubectl get pod -n logging | grep 'elasticsearch-data-0' | grep 'Running'
  register: status_elasticsearch
  become: false
  ignore_errors: yes

- name:
  block:

  - name: 3.29.35 | Чтение namespace 'logging'
    shell: kubectl get namespace logging | grep 'Active'
    register: status_namespace
    become: false
    ignore_errors: yes

  - name: 3.29.35 | Создание namespace 'logging'
    kubernetes.core.k8s:
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "logging"
          labels:
            pod-security.kubernetes.io/enforce: privileged
      state: present
    when: status_namespace.rc == 1

  - name: 3.29.35 | Подключение сетевых репозиториев
    block:

    - name: 3.29.35 | Чтение репозитория 'elasticsearch'
      shell: helm repo list | grep 'elasticsearch'
      register: status_repo_elasticsearch
      become: false
      ignore_errors: yes

    - name: 3.29.35 | Добавление репозитория 'elasticsearch' для Helm
      kubernetes.core.helm_repository:
        name: elasticsearch
        repo_url: https://helm.elastic.co
        force_update: true
      become: false
      when: status_repo_elasticsearch.rc == 1

    - name: 3.29.35 | Чтение репозитория 'bitnami'
      shell: helm repo list | grep 'bitnami'
      register: status_repo_bitnami
      become: false
      ignore_errors: yes

    - name: 3.29.35 | Добавление репозитория 'bitnami' для Helm
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
####### repo_url: https://charts.bitnami.com/bitnami
        force_update: true
      become: false
      when: status_repo_bitnami.rc == 1

    when: registry.srv is not defined

  - name: 3.29.35 | Подключение локального репозитория
    block:

    - name: 3.29.35 | Чтение репозитория 'registry-local'
      shell: helm repo list | grep 'registry-local'
      register: status_repo_registry_local
      become: false
      ignore_errors: yes

    - name: 3.29.35 | Добавление локального репозитория 'registry-local'
      kubernetes.core.helm_repository:
        name: registry-local
        repo_url: http://{{ hostvars[registry.srv].ansible_ssh_host }}:{{ registry.port }}/helm
        force_update: true
      become: false
      when: status_repo_registry_local.rc == 1

    when: registry.srv is defined

  - name: 3.29.35 | Создание 'elasticsearch-templates'
    kubernetes.core.k8s:
      state: present
      namespace: logging
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition: 
        - "{{ lookup('template', 'Helm_Charts/elasticsearch-templates.yaml') | from_yaml }}"
      force: true
    become: false

  - name: 3.29.35 | Развертывание 'elasticsearch v19.5.6'
    kubernetes.core.helm:
      name: elasticsearch
      release_namespace: logging
      chart_ref: bitnami/elasticsearch
      chart_version: 19.5.6
      values: "{{ lookup('template', 'Helm_Charts/elasticsearch.yaml') | from_yaml }}"
      force: true
    become: false
    when: registry.srv is not defined

  - name: 3.29.35 | Развертывание 'elasticsearch v19.5.6'
    kubernetes.core.helm:
      name: elasticsearch
      release_namespace: logging
      chart_ref: registry-local/elasticsearch
      chart_version: 19.5.6
      values: "{{ lookup('template', 'Helm_Charts/elasticsearch.yaml') | from_yaml }}"
      force: true
    become: false
    when: registry.srv is defined

  - name: 3.29.35 | Ожидание запуска 'elasticsearch-data'
    shell: |
      kubectl get pod -n logging | grep 'elasticsearch-data-0' | grep 'Running'
    register: result
    until: result.rc == 0
    retries: 120
    delay: 10
    become: false

  when: status_elasticsearch.rc == 1

- name: 3.29.35 | Чтение статуса 'fluent-bit'
  shell: kubectl get pod -n logging | grep 'fluent-bit-' | grep 'Running'
  register: status_fluent_bit
  become: false
  ignore_errors: yes

- name: 3.29.35 | Развертывание 'fluent-bit'
  block:

  - name: 3.29.35 | Чтение репозитория 'fluent'
    shell: helm repo list | grep 'fluent'
    register: status_repo_fluent
    become: false
    ignore_errors: yes

  - name: 3.29.35 | Добавление репозитория 'fluent' для Helm
    kubernetes.core.helm_repository:
      name: fluent
      repo_url: https://fluent.github.io/helm-charts
      force_update: true
    become: false
    when:
      - status_repo_fluent.rc == 1
      - registry.srv is not defined

  - name: 3.29.35 | Развертывание 'fluent-bit v0.21.5'
    kubernetes.core.helm:
      name: fluent-bit
      release_namespace: logging
      chart_ref: fluent/fluent-bit
      chart_version: 0.21.5
      values: "{{ lookup('template', 'Helm_Charts/fluent-bit.yaml') | from_yaml }}"
      force: true
    become: false
    when: registry.srv is not defined

  - name: 3.29.35 | Развертывание 'fluent-bit v0.21.5'
    kubernetes.core.helm:
      name: fluent-bit
      release_namespace: logging
      chart_ref: registry-local/fluent-bit
      chart_version: 0.21.5
      values: "{{ lookup('template', 'Helm_Charts/fluent-bit.yaml') | from_yaml }}"
      force: true
    become: false
    when: registry.srv is defined

  - name: 3.29.35 | Ожидание запуска 'fluent-bit'
    shell: |
      kubectl get pod -n logging | grep 'fluent-bit' | grep 'Running'
    register: result
    until: result.rc == 0
    retries: 60
    delay: 10
    become: false

  when: status_fluent_bit.rc == 1

- name: 3.29.35 | Чтение статуса 'kibana'
  shell: kubectl get pod -n logging | grep 'kibana-' | grep 'Running'
  register: status_kibana
  become: false
  ignore_errors: yes

- name: 3.29.35 | Развертывание 'kibana'
  block:

  - name: 3.29.35 | Развертывание 'kibana v10.2.11' из 'bitnami/kibana'
    kubernetes.core.helm:
      name: kibana
      release_namespace: logging
      chart_ref: bitnami/kibana
      chart_version: 10.2.11
      values: "{{ lookup('template', 'Helm_Charts/kibana.yaml') | from_yaml }}"
      force: true
    become: false
    when: registry.srv is not defined

  - name: 3.29.35 | Развертывание 'kibana v10.2.11' из 'registry-local/kibana'
    kubernetes.core.helm:
      name: kibana
      release_namespace: logging
      chart_ref: registry-local/kibana
      chart_version: 10.2.11
      values: "{{ lookup('template', 'Helm_Charts/kibana.yaml') | from_yaml }}"
      force: true
    become: false
    when: registry.srv is defined

  - name: 3.29.35 | Ожидание запуска 'kibana'
    shell: |
      kubectl get pod -n logging | grep 'kibana' | grep 'Running'
    register: result
    until: result.rc == 0
    retries: 60
    delay: 10
    become: false

  when: status_kibana.rc == 1

...