---

- name: Настройка узлов кластера
  block:
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/1. Configure_kernel.yaml'
    # - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/2. Install_HAProxy.yaml'
    # - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/3. Install_Keepalived.yaml'
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/4. Install_Kubernetes.yaml'
  when: inventory_hostname in k8s.masters or inventory_hostname in k8s.workers

- name: Создание кластера
  block:
    - import_tasks: 11. Creating_Cluster.yaml
  when: inventory_hostname == k8s.masters[0]

- name: Создание кластера без воркеров
  block:
    - import_tasks: 12. Remove_Taint.yaml 
  when: inventory_hostname in k8s.masters

- name: Регистрация узлов Masters
  include_tasks: 15. Adding_Master.yaml
  with_items: '{{ k8s.masters }}'
  when: inventory_hostname == k8s.masters[0]

- name: Регистрация узлов Workers
  include_tasks: 16. Adding_Worker.yaml
  with_items: '{{ k8s.workers }}'
  when: inventory_hostname == k8s.masters[0]

# - name: Обновление сертификатов кластера
  # block:
    # - import_tasks: 19. Renew_Certs.yaml
  # when: inventory_hostname in k8s.masters or inventory_hostname in k8s.workers

- name: Настройка 'kube-system'
  block:
    - import_tasks: 21. ks_Network_Calico.yaml
    - import_tasks: 22. ks_NodeLocalDNS.yaml
    # - import_tasks: 23. ks_Provisioner_Ceph.yaml
    - import_tasks: 24. ks_Provisioner_LVM.yaml
    - import_tasks: 25. ks_Provisioner_NFS.yaml
    ##### - import_tasks: K8s_Provisioner_NFS_Client.yaml
  when: inventory_hostname == k8s.masters[0]

- name: Регистрация сервисов в кластере
  block:
    - import_tasks: 31. Monitoring.yaml
    - import_tasks: 32. Postgres_Operator.yaml
    - import_tasks: 33. Rabbitmq_Operator.yaml
    - import_tasks: 34. Redis_Operator.yaml
    - import_tasks: 35. Logging.yaml
    ##### - import_tasks: Ingress.yaml
    ##### - import_tasks: Dashboard.yaml
  when: inventory_hostname == k8s.masters[0]

# - name: Развертывание Registry
  # block:
    # - import_tasks: 40. Registry.yaml
  # when: inventory_hostname in k8s.masters or inventory_hostname in k8s.workers

...