---

- name: Чтение статуса 'Postgres'
  shell: kubectl get pods -n staff | grep 'postgres-operator' | grep 'Running'
  register: status_postgres
  become: false
  ignore_errors: yes

- name:
  block:

  - name: Создание пространства имен 'staff'
    kubernetes.core.k8s:
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: staff
          labels:
            pod-security.kubernetes.io/enforce: privileged
      state: present

  - name: Развертывание из сетевого репозитория
    block:

    - name: Добавление репозитория 'postgres-operator'
      kubernetes.core.helm_repository:
        name: postgres-operator
        repo_url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
        force_update: true
      become: false

    - name: Развертывание 'postgres-operator v1.9.0'
      kubernetes.core.helm:
        name: postgres-operator
        release_namespace: staff
        chart_ref: postgres-operator/postgres-operator
        chart_version: 1.9.0
        values: "{{ lookup('template', 'Helm_Charts/postgres-operator.yaml') | from_yaml }}"
        force: true
      become: false

    when: registry.srv is not defined


  - name: Развертывание из локального репозитория
    block:

    - name: Добавление локального репозитория 'registry-local'
      kubernetes.core.helm_repository:
        name: registry-local
        repo_url: http://{{ hostvars[registry.srv].ansible_ssh_host }}:{{ registry.port }}/helm
        force_update: true
      become: false

    - name: Развертывание 'postgres-operator v1.9.0'
      kubernetes.core.helm:
        name: registry-local
        release_namespace: staff
        chart_ref: registry-local/postgres-operator
        chart_version: 1.9.0
        values: "{{ lookup('template', 'Helm_Charts/postgres-operator.yaml') | from_yaml }}"
        force: true
      become: false

    when: registry.srv is defined

  when: status_postgres.stdout == ''

...