apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph
stringData:
  adminID: admin
  adminKey: AQAHjdljADFAKhAA2vcSI2qH1U2Wo/qutVZuAA==
  userID: kube
  userKey: AQDIR9pjnYBFHxAAo6BlK1m2KNkU61dfmBfKKg==
