---

- name: Проверка наличия файла '/etc/apt/sources.list.d/sources.list'
  stat:
    path: /etc/apt/sources.list.d/sources.list
  register: sources_result

- name: Создания локального репозитория
  block:

  - name: Создание папок репозиториев
    file:
      state: directory
      path: '{{ item }}'
      mode: 0755
    with_items:
    - /srv
    - /srv/iso
    - /srv/repo
    
  - name: Копирование ISO образов AstraLinux
    copy:
      src: '../../../../iso/AstraLinux/1.7_x86-64/{{ item }}.iso'
      dest: '/srv/iso/'
      force: no
    with_items:
    - '{{ repo.name_iso }}'

  - name: Создание папок репозитория
    file:
      state: directory
      path: '/srv/repo/{{ item }}'
      mode: 0755
    with_items:
    - '{{ repo.name_iso }}'
    ignore_errors: yes
  
  - name: Монтирование образов ОС
    mount:
      path: '/srv/repo/{{ item }}'
      src: '/srv/iso/{{ item }}.iso'
      fstype: iso9660
      opts: ro,auto
      state: mounted
    with_items:
    - '{{ repo.name_iso }}'

  - name: Удаление содержимого файла '/etc/apt/sources.list'
    file:
      path: /etc/apt/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Создание файла '/etc/apt/sources.list.d/sources.list'
    file:
      path: /etc/apt/sources.list.d/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Заполнение файла '/etc/apt/sources.list.d/sources.list'
    lineinfile:
      path: /etc/apt/sources.list.d/sources.list
      line: 'deb file:///srv/repo/{{ item}} {{ repo.dist }} {{ repo.res }}'
      state: present
    with_items:
    - '{{ repo.name_iso }}'

  when:
  - inventory_hostname == repo.srv 
  - not sources_result.stat.exists

- name: Проверка наличия файла '/etc/apache2-repo/sites-available/000-default.conf'
  stat:
    path: /etc/apache2-repo/sites-available/000-default.conf
  register: stat_result

- name: Настройка Apache2@repo
  block:

  - name: Инсталляция сервера Apache
    apt:
      name:
      - apache2
      - libapache2-mod-php7.3
      state: latest
      update_cache: yes

  - name: Удаление папок и файлов 'Apache2@repo'
    shell: '{{ item }}'
    with_items:
      - rm -rf /etc/apache2-repo
      - rm -rf /var/log/apache2-repo
      - rm -f /usr/local/sbin/*repo

  - name: Модифицируем файлы конфигурации 'Apache2@repo'
    shell: |
      sed -i "s/zero_if_notfound: no/zero_if_notfound: yes/g" /etc/parsec/mswitch.conf
      sh /usr/share/doc/apache2/examples/setup-instance repo
      sed -i "s/# AstraMode on/AstraMode off/g" /etc/apache2-repo/apache2.conf
      sed -i "s/Listen 80/Listen {{ repo.port }}/g" /etc/apache2-repo/ports.conf
      sed -i "s/;date.timezone =/date.timezone = {{ ntp.timezone }}/g" /etc/php/7.3/apache2/php.ini
      sed -i "s/post_max_size = 8M/post_max_size = 32M/g" /etc/php/7.3/apache2/php.ini
      sed -i "s/max_execution_time = 30/max_execution_time = 300/g" /etc/php/7.3/apache2/php.ini
      sed -i "s/max_input_time = 60/max_input_time = 300/g" /etc/php/7.3/apache2/php.ini

  - name: Очистка файла '/etc/apache2-repo/sites-available/000-default.conf'
    file:
      path: /etc/apache2-repo/sites-available/000-default.conf
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Добавление виртуального сервера
    blockinfile:
      dest: /etc/apache2-repo/sites-available/000-default.conf
      marker: '### repo ###'
      block: |
        <VirtualHost {{ hostvars[repo.srv].ansible_ssh_host }}:{{ repo.port }}>
           #ServerName {{repo.srv}}.{{ domain }}
           #ServerAlias repo
           ServerAdmin webmaster@localhost
           DocumentRoot /var/www/repo
        </VirtualHost>

  - name: Создание символьной ссылки на репозиторий
    file:
      src: /srv/repo
      dest: /var/www/repo
      state: link

  - name: Перезапуск службы 'Apache2@repo'
    service:
      name: apache2@repo
      enabled: yes
      state: restarted

  when:
  - inventory_hostname == repo.srv
  - not stat_result.stat.exists
  
- name: Подключение к сетевому репозиторию
  block:

  - name: Удаление файла '/etc/apt/sources.list'
    file:
      path: /etc/apt/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Удаление файла '/etc/apt/sources.list.d/sources.list'
    file:
      path: /etc/apt/sources.list.d/sources.list
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Заполняем файл '/etc/apt/sources.list.d/sources.list'
    lineinfile:
      path: /etc/apt/sources.list.d/sources.list
      line: 'deb http://{{ hostvars[repo.srv].ansible_ssh_host }}:{{ repo.port }}/{{ item}} {{ repo.dist }} {{ repo.res }}'
      state: present
    with_items:
    - '{{ repo.name_iso }}'

  when:
  - inventory_hostname != repo.srv
  - not sources_result.stat.exists

- name: Чтение версии установленного апдейта ОС
  shell: cat /etc/astra/build_version | grep '1.7.5.16'
  register: update_status
  ignore_errors: yes

- name: Обновление системы
  block:

  - name: Обновление AstraLinux
    shell: 'astra-update -A -K -r -T'
    ignore_errors: yes

  - name: Перезагрузка ОС
    reboot:
      msg: "Reboot"

  when: update_status.stdout == ''  