---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep Astra-upgrade
  register: version
  ignore_errors: yes

- name: Установка необходимых пакетов
  apt:
    update_cache: yes
    name:
    - astra-update
    state: latest
  when:
   - repo == "mo"
   - version.stdout != relis

- name: Апдейт AstraLinux MO
  shell: astra-update -A -r
  when:
   - repo == "mo"
   - version.stdout != relis
  ignore_errors: yes

- name: Astra-update | Апдейт AstraLinux FSB
  shell: sudo -s && apt update && apt -y dist-upgrade && apt -f install
  when:
   - repo == "fsb"
   - version.stdout != relis
  ignore_errors: yes

- name: Изменения файла etc/modprobe.d/blacklist-astra.conf
  lineinfile:
    dest: /etc/modprobe.d/blacklist-astra.conf
    regexp: "{{ item.do }}"
    line: "{{ item.posle }}"
  with_items:
  - { do: 'blacklist ast', posle: '#blacklist ast'}
  - { do: 'blacklist mgag200', posle: '#blacklist mgag200'}
  when: version.stdout != relis

- name: Удаление лишних ядер
  apt:
    update_cache: yes
    name:
    - linux-image-4.15.3-1-generic
    - linux-image-4.15.3-1-hardened
    state: absent
  ignore_errors: yes
  when: version.stdout != relis

- name: Удаление пакетов которые больше не нужны
  apt:
    update_cache: yes
    autoremove: yes
    autoclean: yes
  when: version.stdout != relis

- name: update-initramfs
  shell: update-initramfs -u -k all
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  shell: "sed -i '/Astra-upgrade/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  ignore_errors: yes
