---

- name: Добавление репозитория 'bitnami' для helm
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"


- name: Развертывание 'rabbitmq-operator (3.2.8)'
  kubernetes.core.helm:
    name: rabbitmq-operator
    release_namespace: staff
    chart_ref: bitnami/rabbitmq-cluster-operator
    chart_version: 3.2.8
    values: "{{ lookup('file', 'chart_bitnami_rabbitmq-cluster-operator_3.2.8_values.yaml') | from_yaml }}"

...