---

- name: Если 'Nexus' сервер определен
  block:

  - name: Настройка сервера 'Nexus' с Herm репозиторием для Kubernetes'
    block:
      - include_tasks: '{{ ansible_distribution }}/Install_Docker.yaml'
      - include_tasks: 'Deploy.yaml'
    when: inventory_hostname == Nexus.srv

  when: Nexus.srv is defined

...