---

- name: Настройка сервера 'Nginx' с Herm репозиторием для Kubernetes'
  block:
    - include_tasks: '{{ ansible_distribution }}/Install_Docker.yaml'
    - include_tasks: 'Deploy.yaml'



    # - name: Выкачиваем контейнеры
      # shell: |
        # docker pull cr.fluentbit.io/fluent/fluent-bit:2.0.6
        
        # docker pull cr.fluentbit.io/fluent/cr.fluentbit.io/fluent/fluent-bit
        # docker pull docker.io/bitnami/kubectl:1.22
        # docker pull docker.io/bitnami/kibana:8.5.3-debian-11-r9
        # docker pull docker.io/bitnami/bitnami-shell:11-debian-11-r69
        # docker pull docker.io/bitnami/kibana:8.5.3


    # - name: Пакуем контейнеры
      # shell: |
        # docker save -o fluent-bit-2.0.6.tar cr.fluentbit.io/fluent/fluent-bit:2.0.6
        # docker save -o fluent-bit.tar cr.fluentbit.io/fluent/fluent-bit

        # docker save -o kubectl-1.22.tar docker.io/bitnami/kubectl:1.22
        # docker save -o kibana-8.5.3-debian-11-r9.tar docker.io/bitnami/kibana:8.5.3-debian-11-r9
        # docker save -o bitnami-shell-11-debian-11-r69.tar docker.io/bitnami/bitnami-shell:11-debian-11-r69
        # docker save -o kibana-8.5.3.tar docker.io/bitnami/kibana:8.5.3




# curl -OL http://10.4.151.216:5000/imgs/fluent-bit.tar
# curl -OL http://10.4.151.216:5000/imgs/fluent-bit-2.0.6.tar
# curl -OL http://10.4.151.216:5000/imgs/kubectl-1.22.tar
# curl -OL http://10.4.151.216:5000/imgs/kibana-8.5.3-debian-11-r9.tar
# curl -OL http://10.4.151.216:5000/imgs/bitnami-shell-11-debian-11-r69.tar


# skopeo copy docker-archive:./fluent-bit.tar containers-storage:cr.fluentbit.io/fluent/fluent-bit
# skopeo copy docker-archive:./fluent-bit-2.0.6.tar containers-storage:cr.fluentbit.io/fluent/fluent-bit:2.0.6
# skopeo copy docker-archive:./kubectl-1.22.tar containers-storage:docker.io/bitnami/kubectl:1.22
# skopeo copy docker-archive:./kibana-8.5.3-debian-11-r9.tar containers-storage:docker.io/bitnami/kibana:8.5.3-debian-11-r9
# skopeo copy docker-archive:./bitnami-shell-11-debian-11-r69.tar containers-storage:docker.io/bitnami/bitnami-shell:11-debian-11-r69









  when: inventory_hostname == Nexus.srv

...