---
# tasks file for install_crio
- name: Install dependencies
  apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
  become: true
  become_method: sudo

- name: Create directory for key
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
    owner: root
    group: root
  become: true
  become_method: sudo

- name: Add key crio repo
  shell: |
      curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ kubernetes_os }}/Release.key |\
      gpg --batch --yes --dearmor -o /usr/share/keyrings/libcontainers-archive-keyring.gpg
      curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes_version }}/{{ kubernetes_os }}/Release.key |\
      gpg --batch --yes --dearmor -o /usr/share/keyrings/libcontainers-crio-archive-keyring.gpg
  become: true
  become_method: sudo

- name: Add cri-o repo
  shell: |
      echo "deb [signed-by=/usr/share/keyrings/libcontainers-archive-keyring.gpg] \
      https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ kubernetes_os }}/ /" |\
      tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
      echo "deb [signed-by=/usr/share/keyrings/libcontainers-crio-archive-keyring.gpg] \
      https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ kubernetes_version }}/{{ kubernetes_os }}/ /" |\
      tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:{{ kubernetes_os }}.list
  become: true
  become_method: sudo

- name: Install crio-o
  apt:
    update_cache: true
    name:
      - cri-o-runc
      - cri-o
  become: true
  become_method: sudo

<<<<<<< HEAD
- name: Configuration copy
  template:
    src: registries.conf.j2
    dest: '/etc/containers/registries.conf'
=======
- name: registries configuration copy
  template:
    src: registries.j2
    dest: '/etc/containers/registries.d/{{ net_local_domain }}.conf'
>>>>>>> ec63-1
  become: true
  become_method: sudo

- name: Enable service cri-o
  systemd:
    name: crio.service
    state: restarted
    enabled: true
  become: true
  become_method: sudo
