---

- name: 0.5-Time | Чтение статуса часового пояса
  shell: cat /etc/timezone
  register: timezone_status

- name: 0.5-Time | Установка часового пояса '{{ ntp.timezone }}'
  shell: |
    timedatectl set-timezone {{ ntp.timezone }}
    timedatectl set-local-rtc 0
  when: timezone_status.stdout != ntp.timezone

- name: 0.5-Time | Чтение статуса конфигурирования NTP сервера
  shell: cat /etc/ntp.conf | grep '{{ ntp.srv }}'
  register: ntp_server_status
  ignore_errors: yes
  when: ntp.srv is defined

- name: 0.5-Time | Настройка NTP
  block:

  - name: 0.5-Time | Проверка установки 'ntp'
    command: which ntpq
    register: ntp_check
    ignore_errors: yes

  - name: 0.5-Time | Инсталляция пакета 'ntp'
    apt:
      name: ntp
      update_cache: yes
    when: ntp_check.rc != 0

  # - name: 0.5-Time | Создание файла '/etc/ntp.conf'
    # copy:
      # dest: '/etc/ntp.conf'
      # content: |
        # logfile /var/log/ntp
        # driftfile /var/lib/ntp/ntp.drift
        # leapfile /usr/share/zoneinfo/leap-seconds.list
        # statistics loopstats peerstats clockstats
        # filegen loopstats file loopstats type day enable
        # filegen peerstats file peerstats type day enable
        # filegen clockstats file clockstats type day enable
        # server 127.127.1.0
        # server {{ ntp.srv }} prefer
        # fudge 127.127.1.0 stratum 10
        # restrict 127.127.1.0 mask 255.255.255.255
        # restrict {{ Net.network.split("/")[0] }} mask {{ Net.mask }}
        # restrict -4 default kod notrap nomodify nopeer noquery limited
        # restrict -6 default kod notrap nomodify nopeer noquery limited
        # restrict source notrap nomodify noquery

  - name: Синхронизация времени
    shell: |
      echo server {{ ntp.srv }} prefer >> /etc/ntp.conf

  - name: Перезапуск службы NTP
    service:
      name: ntp
      enabled: yes
      state: restarted

  # - name: Синхронизация времени
    # shell: |
      # hwclock --systohc --utc
      # timedatectl set-local-rtc 0
      # ntpdate {{ ntp.srv }}

  when: ntp_server_status.rc != 0

...