---

- name: 3.22.4 | Проверка наличия 'Ceph'
  stat:
    path: /etc/ceph/ceph.conf
  register: ceph_result
  ignore_errors: yes
  when: inventory_hostname in Ceph.nodes

- name: 3.22.4 | Установка и настройка Ceph
  block:

  - name: 3.22.4 | Инсталляция служб Ceph на узлах кластера
    shell: '{{ item }}'
    loop:
      - ceph-deploy --username {{ ansible_ssh_user }} install {{ inventory_hostname }}
      # - ceph-deploy --username {{ ansible_ssh_user }} install --mon {{ inventory_hostname }}
      # - ceph-deploy --username {{ ansible_ssh_user }} install --osd {{ inventory_hostname }}
      # - ceph-deploy --username {{ ansible_ssh_user }} install --mgr {{ inventory_hostname }}
      # - ceph-deploy --username {{ ansible_ssh_user }} install --mds {{ inventory_hostname }}
      # - ceph-deploy --username {{ ansible_ssh_user }} install --cli {{ inventory_hostname }}
    become: no

  - name: 3.22.4 | Перезагрузка узлов кластера
    reboot:
      msg: 'Reboot'

  - name: 3.22.4 | Настройка 'Ceph' кластера
    block:

    - name: 3.22.4 | Создание нового кластера
      shell: '{{ item }}'
      loop:
        - ceph-deploy --username {{ ansible_ssh_user }} new --cluster-network {{ Ceph.net.network }} --public-network {{ Net.network }} {{ Ceph.nodes | join(' ') }}
      become: no

    - name: 3.22.4 | Инициализация мониторов
      shell: '{{ item }}'
      loop:
        - ceph-deploy --username {{ ansible_ssh_user }} --overwrite-conf mon create {{ Ceph.nodes | join(' ') }}
        # - ceph-deploy --username {{ ansible_ssh_user }} --overwrite-conf mon create-initial
        - sleep 30
      become: no

    - name: 3.22.4 | Обмен ключами
      shell: '{{ item }}'
      loop:
        - ceph-deploy --username {{ ansible_ssh_user }} gatherkeys {{ Ceph.nodes | join(' ') }}
      become: no

    - name: 3.22.4 | Регистрация MGR службы диспетчера Ceph на узлах кластера
      shell: '{{ item }}'
      loop:
        - ceph-deploy --username {{ ansible_ssh_user }} --overwrite-conf mgr create {{ Ceph.nodes | join(' ') }}
      become: no

# Удаление разметки Ceph в случае повторного инсталлирования
# sudo ceph-volume lvm zap /dev/vg2/lv_cephosd

    - name: 3.22.4 | Регистрация OSD на дисках узлов {{ Ceph.dev }} и добавление их в кластер
      shell: |
        ceph-deploy --username {{ ansible_ssh_user }} --overwrite-conf osd create --data {{ Ceph.dev }} {{ item }}
      with_items: '{{ Ceph.nodes }}'
      become: no



    - name: 3.22.4 | Назначение административной рабочей станции
      shell: '{{ item }}'
      loop:
        - ceph-deploy --username {{ ansible_ssh_user }} admin {{ Ceph.nodes | join(' ') }}
      become: no

    - name: 3.22.4 | Настройка безопасности
      shell: '{{ item }}'
      loop:
        - ceph config set mon auth_allow_insecure_global_id_reclaim false
        - ceph config set mon mon_warn_on_insecure_global_id_reclaim false
        - ceph config set mon mon_warn_on_insecure_global_id_reclaim_allowed false

    # - name: 3.22.4 | Выключение RESTful API
      # shell: '{{ item }}'
      # loop:
        # - ceph mgr module disable restful

    - name: 3.22.4 | Регистрация Metadata Server Daemon (MSD) - сервер метаданных
      shell: '{{ item }}'
      loop:
        - ceph-deploy --username {{ ansible_ssh_user }} --overwrite-conf mds create {{ Ceph.nodes | join(' ') }}
      become: no

    - name: 3.22.4 | Создаем пулы
      shell: '{{ item }}'
      loop:
        - ceph osd pool create kube 64 --autoscale-mode=on
        - ceph osd pool set kube min_size 1
        - ceph osd pool set kube size 3
        - ceph osd pool application enable kube rbd
        - rbd pool init kube
        - ceph auth get-or-create client.rbd mon 'allow r, allow command "osd blacklist"' osd 'allow rwx pool=kube' -o /etc/ceph/ceph.client.rbd.keyring
        - ceph osd pool create cephfs_data 64 --autoscale-mode=on
        - ceph osd pool set cephfs_data min_size 1
        - ceph osd pool set cephfs_data size 3
        - ceph osd pool create cephfs_metadata 64 --autoscale-mode=on
        - ceph osd pool set cephfs_metadata min_size 1
        - ceph osd pool set cephfs_metadata size 3
        - ceph fs new cephfs cephfs_metadata cephfs_data
        - ceph osd pool application enable cephfs_metadata cephfs
        # - ceph fs subvolumegroup create cephfs csi
        - ceph auth get-or-create client.fs mon 'allow r' mgr 'allow rw' mds 'allow rw' osd 'allow rw pool=cephfs_data, allow rw pool=cephfs_metadata' -o /etc/ceph/ceph.client.fs.keyring

    - name: Запись пароля в файл '/tmp/pwd.txt'
      copy:
        content: '{{ ansible_ssh_pass | string }}'
        dest: /tmp/pwd.txt

    - name: 3.22.4 | Установить 'dashboard'
      shell: '{{ item }}'
      loop:
        - ceph mgr module enable dashboard
        - ceph config set mgr mgr/dashboard/server_addr {{ Ceph.net.keepalived_IP }}
        - ceph config set mgr mgr/dashboard/server_port {{ Ceph.net.dashboard_port }}
        - ceph config set mgr mgr/dashboard/ssl_server_port 8443
        - ceph config set mgr mgr/dashboard/ssl false
        - ceph dashboard ac-user-create {{ ansible_ssh_user }} -i /tmp/pwd.txt administrator
        - ceph dashboard ac-user-set-password {{ ansible_ssh_user }} -i /tmp/pwd.txt
        - rm -rf /tmp/pwd.txt
      when:
        - Ceph.net.keepalived_IP is defined
        - Ceph.net.dashboard_port is defined

    - name: 3.22.4 | Копирование ключей в '/etc/ceph/'
      shell: '{{ item }}'
      loop:
        - cp /home/{{ ansible_ssh_user }}/ceph.*.keyring /etc/ceph/

    - name: 3.22.4 | Получение ключей 'Ceph'
      fetch:
        src: '/etc/ceph/ceph.{{ item }}.keyring'
        dest: /tmp
      loop:
        - 'bootstrap-mds'
        - 'bootstrap-osd'
        - 'bootstrap-mgr'
        - 'bootstrap-rgw'
        - 'client.admin'
        - 'mon'
        - 'client.admin'
        - 'client.fs'
        - 'client.rbd'
    when: inventory_hostname == Ceph.nodes[0]

  - name: 3.22.4 | Отправка ключей 'Ceph'
    copy:
      src: '/tmp/{{ Ceph.nodes[0] }}/etc/ceph/ceph.{{ item }}.keyring'
      dest: '/etc/ceph/ceph.{{ item }}.keyring'
    loop:
      - 'bootstrap-mds'
      - 'bootstrap-osd'
      - 'bootstrap-mgr'
      - 'bootstrap-rgw'
      - 'client.admin'
      - 'mon'
      - 'client.admin'
      - 'client.fs'
      - 'client.rbd'
    when: inventory_hostname != Ceph.nodes[0]

  - name: 3.22.4 | Создание папки монтирования CephFS
    file:
      state: directory
      path: '{{ item }}'
      mode: 0755
    with_items:
      - /mnt/CephFS

  - name: 3.22.4 | Создание ключа доступа пользователя 'admin'
    shell: |
      ceph auth get-key client.admin > /etc/ceph/secret.key

  - name: 3.22.4 | Монтирование CephFS
    mount:
      path: '/mnt/CephFS'
      src: '{{ hostvars[inventory_hostname].ansible_ssh_host }}:6789:/'
      fstype: ceph
      opts: 'name=admin,secretfile=/etc/ceph/secret.key,noatime,_netdev'
      state: mounted

  when:
    - not ceph_result.stat.exists

...