---

- name: Настройка узлов кластера
  block:
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/1. Network.yaml'  
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/2. Install_Ceph.yaml'
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/3. Install_Keepalived.yaml'
    - include_tasks: '4. Init_Ceph.yaml'
    
  when: inventory_hostname in Ceph.nodes

...