---

- name: Запускаем на серверах
  block:

  - name: Проверка наличия файла '/etc/auto.master.d/backup.nfs'
    stat:
      path: /etc/auto.master.d/backup.nfs
    register: nfs_result

  - name: Настройка NFS клиента
    block:
  
    - name: Инсталляция необходимых пакетов для клиентов
      apt:
        name:
        - nfs-common
        - autofs
        state: latest

    - name: Остановка служб
      service:
        name: '{{item}}'
        state:  stopped
      with_items:
      - autofs
      - nfs-common

    - name: Создадим папки '{{ backup.path }}' для хранения бекапа 
      file:
        state: directory
        mode: 0755
        recurse: yes
        path: '{{ backup.path }}'
      ignore_errors: yes

    - name: Cоздание папки '/etc/auto.master.d'
      file:
        path: '/etc/auto.master.d'
        state: directory
        mode: '0755'

    - name: Создание файла '/etc/auto.master.d/backup.autofs'
      template:
        src: backup.autofs.j2
        dest: /etc/auto.master.d/backup.autofs
        follow: yes

    - name: Создание файла '/etc/auto.master.d/backup.nfs'
      template:
        src: backup.nfs.j2
        dest: /etc/auto.master.d/backup.nfs
        follow: yes

    - name: Перезапуск службы autofs
      service:
        name: '{{item}}'
        state: restarted
        enabled: yes
      with_items:
      - autofs

    when: not nfs_result.stat.exists

  when: 
  - inventory_hostname != backup.srv
  - inventory_hostname in groups['srv']

...