---

- name: Запускаем на серверах
  block:

  - name: Проверить, установлен ли PostgreSQL 9.6
    stat:
      path: /etc/postgresql/9.6/main/postgresql.conf
    register: postgresql_installed

  - name: Создание заданий бекапа PostgreSQL
    block:

    - name: Проверка наличия файла '/etc/cron.d/postgresql_cron'
      stat:
        path: /etc/cron.d/postgresql_cron
      register: cron_result

    - name: Подготовка скриптов бекапа
      block:

      - name: Копирование скриптов 'backup/restore'
        template:
          src: '{{ item }}.j2'
          dest: '/usr/local/bin/{{ item }}.sh'
          owner: root
          group: root
          mode: 0744
        with_items:
        - 'postgresql_backup'
        - 'postgresql_restore'

      - name: Создание расписания запуска бекапа
        template:
          src: postgresql_cron.j2
          dest: /etc/cron.d/postgresql_cron
          owner: root
          group: root
          mode: 0644

      - name: Перезапуск службы Cron
        service:
          name: cron
          state: restarted

      when: not cron_result.stat.exists

    when:  postgresql_installed.stat.exists

  when: inventory_hostname in groups['srv']

...
