---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep Sobol
  register: version
  ignore_errors: yes

- name: Установка необходимых пакетов
  apt:
    update_cache: yes
    name:
    - libglade2-0
    state: latest
    update_cache: yes
  when: version.stdout != relis

- name: Копирование дистрибутива
  copy:
    src: sobol_4.3-13-astra1.6-20211008SE16-signed_test_amd64.deb
    dest: /opt/distr/Sobol/
    mode: '0777'
    directory_mode: yes
  when: version.stdout != relis

- name: Инсталляция
  shell: "dpkg -i /opt/distr/Sobol/sobol_4.3-13-astra1.6-20211008SE16-signed_test_amd64"
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  shell: "sed -i '/Sobol/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  become: true
  when: version.stdout != relis
