FileDaemon {
  Name = {{ inventory_hostname }}-fd
  FDport = 9102
  WorkingDirectory = /var/lib/bacula
  Pid Directory = /run/bacula
  Maximum Concurrent Jobs = 20
  Plugin Directory = /usr/lib/bacula
  FDAddress = {{ ansible_ssh_host }}
}

Director {
  Name = srv-tk-dir
  Password = "a9obYqJMXLLmmgZpebAbSf_tqVs6TKSpa"
}

Messages {
  Name = Standard
  director = {{ inventory_hostname }}-dir = all, !skipped, !restored
}

Director {
  Name = srv-tk-mon
  Password = "sAWTvV55nak4D4mInZNfCrdRAKw6ga_DX"
  Monitor = yes
}
