---

- name: 3.1.1 | Проверка установки 'PostgreSQL'
  command: which postgres
  register: postgres_check
  ignore_errors: yes

- name: 3.1.1 | Установка и настройка PostgreSQL
  block:

  - name: 3.1.1 | Инсталляция пакетов
    apt_rpm:
      name:
        - postgresql16-server
        - zabbix-server-pgsql
        - fping

  - name: 3.1.1 | Инсталляция системных баз данных
    shell: |
      /etc/init.d/postgresql initdb

  - name: 3.1.1 | Включаем и перезапускаем службу 'PostgreSQL'
    service:
      name: postgresql
      enabled: yes
      state: restarted

  - name: 3.1.1 | Создание БД '{{ Zabbix.db.name }}'
    shell: |
      sudo -u postgres psql -c "CREATE ROLE {{ Zabbix.db.user }} WITH NOSUPERUSER LOGIN PASSWORD '{{ Zabbix.db.password }}';"
      sudo -u postgres psql -c "CREATE DATABASE {{ Zabbix.db.name }} WITH OWNER {{ Zabbix.db.user }};"  
      sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE {{ Zabbix.db.name }} TO {{ Zabbix.db.user }};"
      export PGPASSWORD={{ Zabbix.db.password }}
      cat /usr/share/doc/zabbix-common-database-pgsql-*/{schema,images,data}.sql |  psql -h localhost {{ Zabbix.db.name }} {{ Zabbix.db.user }}
    become: no

  when: postgres_check.rc != 0

- name: 3.1.2 | Проверка установки 'httpd2'
  command: which httpd2
  register: httpd2_check
  ignore_errors: yes

- name: 3.1.2 | Установка Apache2
  block:

  - name: 3.1.2 | Инсталляция пакетов
    apt_rpm:
      name:
        - apache2
        - apache2-mod_php8.2
        - php8.2
        - php8.2-mbstring
        - php8.2-sockets
        - php8.2-gd
        - php8.2-xmlreader
        - php8.2-pgsql
        - php8.2-ldap
        - php8.2-openssl

  - name: 3.1.2 | Внесение изменений в конфигурационныйе файл '/etc/php/8.2/apache2-mod_php/php.ini'
    replace:
      path: /etc/php/8.2/apache2-mod_php/php.ini
      regexp: '^.*{{ item.src }}.*$'
      replace: '{{ item.dest }}'
    loop:
      - { src: "date.timezone",                 dest: "date.timezone = {{ ntp.timezone }}" }
      - { src: "post_max_size",                 dest: "post_max_size = 32M" }
      - { src: "max_execution_time",            dest: "max_execution_time = 600" }
      - { src: "max_input_time",                dest: "max_input_time = 600" }
      - { src: "memory_limit",                  dest: "memory_limit = 256M" }
      - { src: "always_populate_raw_post_data", dest: "always_populate_raw_post_data = -1" }

  - name: 3.1.2 | Перезапуск службы 'httpd2'
    service:
      name: httpd2
      enabled: yes
      state: restarted

  when: httpd2_check.rc != 0

- name: 3.1.3 | Проверка наличия установленного Zabbix сервера
  shell: cat /etc/zabbix/zabbix_server.conf | grep 'DBPassword={{ Zabbix.db.password }}'
  register: zabbix_result
  ignore_errors: yes

- name: 3.1.3 | Установка и настройка Zabbix сервера
  block:

  - name: 3.1.3 | Внесение изменений в конфигурационныйе файл '/etc/zabbix/zabbix_server.conf'
    replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '^.*{{ item.src }}.*$'
      replace: '{{ item.dest }}'
    loop:
      - { src: "DBHost=",     dest: "DBHost=localhost" }
      - { src: "DBName=",     dest: "DBName={{ Zabbix.db.name }}" }
      - { src: "DBUser=",     dest: "DBUser={{ Zabbix.db.user }}" }
      - { src: "DBPassword=", dest: "DBPassword={{ Zabbix.db.password }}" }

  - name: 3.1.3 | Перезапуск службы 'zabbix_pgsql'
    service:
      name: zabbix_pgsql
      enabled: yes
      state: restarted

  when: zabbix_result.stdout == ''

- name: 3.1.4 | Проверка наличия файла '/var/www/webapps/zabbix/ui/conf/zabbix.conf.php'
  stat:
    path: /var/www/webapps/zabbix/ui/conf/zabbix.conf.php
  register: web_result

- name: 3.1.4 | Установка веб-интерфейса Zabbix
  block:

  - name: 3.1.4 | Инсталляция пакетов веб-интерфейса Zabbix
    apt_rpm:
      name:
        - zabbix-phpfrontend-apache2 
        - zabbix-phpfrontend-php8.2

  - name: 3.1.4 | Включить аддоны в apache2
    file:
      src: /etc/httpd2/conf/addon.d/A.zabbix.conf
      dest: /etc/httpd2/conf/extra-enabled/A.zabbix.conf
      state: link
      force: yes

  - name: 3.1.4 | Внесение изменений в файл '/var/www/webapps/zabbix/ui/conf/zabbix.conf.php'
    blockinfile:
      path: /var/www/webapps/zabbix/ui/conf/zabbix.conf.php
      create: yes
      state: present
      marker: ""
      block: |
        <?php
        $DB['TYPE']      = 'POSTGRESQL';
        $DB['SERVER']    = 'localhost';
        $DB['PORT']      = '5432';
        $DB['DATABASE']  = '{{ Zabbix.db.name }}';
        $DB['USER']      = '{{ Zabbix.db.user }}';
        $DB['PASSWORD']  = '{{ Zabbix.db.password }}';
        $ZBX_SERVER_NAME = 'Zabbix';

  - name: 3.1.4 | Изменить права доступа к конфигурационному каталогу веб-интерфейса
    file:
      path: /var/www/webapps/zabbix/ui/conf
      owner: apache2
      group: apache2
      recurse: yes

  - name: 3.1.4 | Перезапуск службы 'httpd2'
    service:
      name: httpd2
      enabled: yes
      state: restarted

  when: not web_result.stat.exists

...