---
# Сброс пароля
# /opt/drwcs/bin/drwidbsh3 /var/opt/drwcs/database.sqlite
# update admins set password='qwerty' where login='admin';
# .exit

# - name: Удаление сервера
#   shell: |
#     ./etc/opt/drweb.com/software/drweb-esuite.remove
#     ./drweb-esuite-extra.remove
#   ignore_errors: yes
#   when: inventory_hostname == drweb.srv

# - name: Отключение от сервера
#   shell: drweb-ctl esdisconnect
#   ignore_errors: yes

# - name: Удаление старого клиента
#   shell: 'cd /opt/drweb.com/bin && echo Y | ./uninst.sh'
#   ignore_errors: yes

- name: Установка и настройка Dr.Web сервер
  block:

  - name: Проверка наличия установленного Dr.Web сервер
    stat:
      path: /etc/opt/drweb.com/software/drweb-esuite.remove
    register: drweb_server_result

  - name: Установка и настройка Dr.Web сервер
    block:

    - name: Копирование дистрибутива
      copy:
        src: '../../../../software/dr_web/{{ drweb.server_dist }}'
        dest: /tmp/
        mode: '0777'
        force: no

    - name: Создание конфигурации установки
      template:
        src: drweb-server-preseed.j2
        dest: /tmp/drweb-server-preseed

    - name: Установка сервера
      apt:
        name:
        - astra-digsig-oldkeys
        state: latest
        update_cache: yes

    - name: Установка сервера
      shell: /tmp/{{ drweb.server_dist }} -- --preseed /tmp/drweb-server-preseed

  # - name: Копирование дистрибутива Extra
    # copy:
      # src: '../../../../software/dr_web/{{ drweb.server_extra }}'
      # dest: /tmp/
      # mode: '0777'
      # force: no

    # - name: Установка Extra
      # shell: |
        # /tmp/{{ drweb_server_extra }}

    - name: Login & Password
      debug:
        msg: 'URL:https://{{ drweb.srv }}:9081  Login: {{ drweb.admin.user }}  Password: {{ drweb.admin.pass }}'

    - name: Перезагрузим сервер
      reboot:
        msg: 'Reboot'
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 60

    when: not drweb_server_result.stat.exists

  when: inventory_hostname == drweb.srv

- name: Проверка наличия установленного Dr.Web агента
  stat:
   path: /opt/drweb.com/bin/uninst.sh
  register: drweb_agent_result

- name: Установка и настройка Dr.Web агента
  block:

  - name: Установка пакетов
    apt:
      name:
      - astra-digsig-oldkeys
      state: latest
      update_cache: yes

  - name: Копирование дистрибутива WS
    copy:
      src: '../../../../software/dr_web/{{ drweb.agent_WS }}'
      dest: /tmp/
      mode: '0777'
      directory_mode: yes
      force: yes
    when: "'arm' in inventory_hostname"

  - name: Копирование дистрибутива FS
    copy:
      src: '../../../../software/dr_web/{{ drweb.agent_FS }}'
      dest: /tmp/
      mode: '0777'
      directory_mode: yes
      force: yes
    when: "'c' in inventory_hostname"

  - name: Скачиваем сертификат сервера
    get_url:
      url: 'https://{{ drweb.srv }}:9081/install/windows/drwcsd-certificate.pem'
      dest: /tmp/drwcsd-certificate.pem
      validate_certs: no

  - name: Установка клиента WS
    shell: cd /tmp && ./{{ drweb.agent_WS }} -- --non-interactive
    ignore_errors: yes
    when: "'arm' in inventory_hostname"

  - name: Установка клиента FS
    shell: cd /tmp && ./{{ drweb.agent_FS }} -- --non-interactive
    ignore_errors: yes
    when: "'c' in inventory_hostname"

  - name: Подключение клиента к серверу
    shell: 'drweb-ctl esconnect {{ drweb.srv }} --Newbie --Certificate /tmp/drwcsd-certificate.pem'

  - name: Создание папки ключей
    file:
      state: directory
      path: "/etc/digsig/keys/legacy/keys"

  - name: Загрузка сертификата антивирурса для работы в ЗПС
    copy:
      src: '/opt/drweb.com/share/doc/{{ item }}'
      dest: /etc/digsig/keys/legacy/keys/
      mode: 0444
      remote_src: yes
    with_items:
    - digsig.gost.gpg
    - digsig.primary_key_2010.gpg

  - name: Инициализация установленных ключей
    shell: update-initramfs -u -k all

  - name: Удаление лишних пакетов
    apt:
      autoremove: yes

  when: not drweb_agent_result.stat.exists

- name: Удаление файлов
  shell: rm /tmp/drw*
  ignore_errors: yes

...