astra-sumac-lock enable
astra-ulimits-control enable
#astra-nochmodx-lock enable
astra-ptrace-lock enable
astra-console-lock enable
astra-sysrq-lock enable
astra-commands-lock enable
astra-sudo-control enable
astra-swapwiper-control enable
astra-secdel-control enable
