---

- name: 3.22.2 | Проверка наличия 'Ceph'
  stat:
    path: /usr/bin/ceph
  register: ceph_result
  ignore_errors: yes

- name: 3.22.2 | Установка 'Ceph'
  block:

  - name: Отключение 'SELinux'
    shell: |
      setenforce 0
      sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

  - name: Перезагрузка ОС
    reboot:
      msg: 'Reboot'

  - name: 3.22.2 | Установка вспомогательных пакетов
    dnf:
      update_cache: true
      name:
        - python3
        - python3-pip
        - python3-devel 
        - python-argparse
        - htop
        - iftop
        - net-tools
        - snappy
        - leveldb
        - gdisk
        - gperftools-libs

  # - name: 3.22.2 | Подключение сетевого репозитория
    # block:

    # - name: 3.22.2 | Создаем файл '/etc/yum.repos.d/ceph.repo'
      # file:
        # path: /etc/yum.repos.d/ceph.repo
        # mode: 0644
        # state: touch

    # - name: 3.22.2 | Добавление репозитория 'Ceph v{{ Ceph.ver }}'
      # blockinfile:
        # path: /etc/yum.repos.d/ceph.repo
        # block: |
          # [ceph]
          # name=Ceph packages
          # baseurl=https://download.ceph.com/rpm-{{ Ceph.ver }}/el8/x86_64
          # enabled=1
          # priority=2
          # gpgcheck=1
          # gpgkey=https://download.ceph.com/keys/release.asc
          # [ceph-noarch]
          # name=Ceph noarch packages
          # baseurl=https://download.ceph.com/rpm-{{ Ceph.ver }}/el8/noarch
          # enabled=1
          # priority=2
          # gpgcheck=1
          # gpgkey=https://download.ceph.com/keys/release.asc

    # - name: 3.22.2 | Обновление репозиториев
      # dnf:
        # update_only: true
        # update_cache: true

    # when: Ceph.ver is defined

  - name: 3.22.2 | Инсталляция 'ceph-deploy'
    dnf:
      name:
        - ceph-deploy
        - ceph-mgr-dashboard

  when: not ceph_result.stat.exists

...