---
# tasks file for add_bond

- name: install ifenslave
  apt:
    update_cache: yes
    pkg:
      - ifenslave
      - ethtool
      - bridge-utils
      - lshw
  become: true
  become_method: sudo

- name: copy config bond0
  template: 
      src: bond0.j2
      dest: /etc/network/interfaces.d/{{ net_bond0_name }}
      owner: root
      group: root
      mode: '0644'
  become: true
  become_method: sudo
  when: net_bond == true

- name: copy config interfaces
  template: 
      src: interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
  become: true
  become_method: sudo
  when: net_bond == true

- name: copy config bond1
  template: 
      src: bond1.j2
      dest: /etc/network/interfaces.d/{{ net_bond1_name }}
      owner: root
      group: root
      mode: '0644'
  become: true
  become_method: sudo 
  when: iscsi_bond == true

- name: Restart service networking.service
  ansible.builtin.service:
    name: networking.service
    state: restarted
  become: true
  become_method: sudo