---

- name: Чтение статуса 'Logging'
  shell: kubectl get pods -n logging | grep 'elasticsearch' | grep 'Running'
  register: status_logging
  become: false
  ignore_errors: yes

- name:
  block:

  - name: Create namespace for logging
    kubernetes.core.k8s:
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "logging"
          labels:
            pod-security.kubernetes.io/enforce: privileged
      state: present

  - name: Добавление репозитория 'elasticsearch' для Helm
    kubernetes.core.helm_repository:
      name: elasticsearch
      repo_url: https://helm.elastic.co
      force_update: true
    become: false

  - name: Добавление репозитория 'bitnami' для Helm
    kubernetes.core.helm_repository:
      name: bitnami
      repo_url: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
      # repo_url:  https://charts.bitnami.com/bitnami
      force_update: true
    become: false

  - name: Добавление репозитория 'fluent' для Helm
    kubernetes.core.helm_repository:
      name: fluent
      repo_url: https://fluent.github.io/helm-charts
      force_update: true
    become: false

  - name: Создание 'elasticsearch-templates'
    kubernetes.core.k8s:
      state: present
      namespace: logging
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition: 
        - "{{ lookup('template', 'Helm_Charts/elasticsearch-templates.yaml') | from_yaml }}"
      force: true
    become: false

  - name: Развертывание 'elasticsearch v19.5.6'
    kubernetes.core.helm:
      name: elasticsearch
      release_namespace: logging
      chart_ref: bitnami/elasticsearch
      chart_version: 19.5.6
      values: "{{ lookup('template', 'Helm_Charts/elasticsearch.yaml') | from_yaml }}"
      force: true
    become: false

  - name: Развертывание 'fluent-bit v0.21.5'
    kubernetes.core.helm:
      name: fluent-bit
      release_namespace: logging
      chart_ref: fluent/fluent-bit
      chart_version: 0.21.5
      values: "{{ lookup('template', 'Helm_Charts/fluent-bit.yaml') | from_yaml }}"
      force: true
    become: false

  - name: Развертывание 'kibana v10.2.11'
    kubernetes.core.helm:
      name: kibana
      release_namespace: logging
      chart_ref: bitnami/kibana
      chart_version: 10.2.11
      values: "{{ lookup('template', 'Helm_Charts/kibana.yaml') | from_yaml }}"
      force: true
    become: false

  # when: status_logging.stdout == ''

...