---

- name: Проверка наличия файла '/var/lib/etcd/member/snap/db'
  stat:
    path: /var/lib/etcd/member/snap/db
  register: etcd_result

- name: Создания серверов
  block:

  - name: Установка пакетов 'etcd'
    dnf:
      update_cache: true
      name:
        - etcd
      state: latest

  - name: Удаление данных из '/var/lib/etcd/*'
    shell: rm -rf /var/lib/etcd/*

  - name: Внесение изменений в конфигурационныйе файл '/etc/etcd/etcd.conf'
    blockinfile:
      path: /etc/etcd/etcd.conf
      block: |
        ETCD_NAME="{{ inventory_hostname }}"
        ETCD_DATA_DIR="/var/lib/etcd"
        ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
        ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"
        ETCD_INITIAL_ADVERTISE_PEER_URLS="http://{{ hostvars[inventory_hostname].ansible_ssh_host }}:2380"
        ETCD_INITIAL_CLUSTER="{% for item in PostgreSQL.etcd_srv %}{{ item }}=http://{{ hostvars[item].ansible_ssh_host }}:2380,{% endfor %}"
        ETCD_INITIAL_CLUSTER_STATE="new"
        ETCD_INITIAL_CLUSTER_TOKEN="PatroniCluster"
        ETCD_ADVERTISE_CLIENT_URLS="http://{{ hostvars[inventory_hostname].ansible_ssh_host }}:2379"
        ETCD_ELECTION_TIMEOUT="5000"
        ETCD_HEARTBEAT_INTERVAL="1000"
        ETCD_ENABLE_V2="true"

  - name: Перезагрузка сервиса 'etcd' 
    service:
      name: etcd
      state: restarted
      enabled: yes

  - name: Внесение изменений в конфигурационныйе файл '/etc/etcd/etcd.conf'
    shell: |
      sleep 30
      sed -i 's/ETCD_INITIAL_CLUSTER_STATE="new"/ETCD_INITIAL_CLUSTER_STATE="existing"/g' /etc/etcd/etcd.conf

  - name: Перезагрузка сервиса 'etcd' 
    service:
      name: etcd
      state: restarted
      enabled: yes

  when: not etcd_result.stat.exists

...