---
# https://docs.percona.com/postgresql/15/solutions/ha-setup-yum.html#configure-patroni

- name: Проверка наличия файла '/etc/systemd/system/patroni.service'
  stat:
    path: /etc/systemd/system/patroni.service
  register: patroni_result

- name: Создания серверов
  block:

  - name: Установка пакетов 'patroni'
    dnf:
      update_cache: true
      name:
        - patroni-etcd
        - python3-pip
        - python3-devel
        - binutils
      state: latest

  - name: Установить права на папку '/etc/patroni'
    file:
      path: /etc/patroni/
      owner: postgres
      group: postgres
      mode: '0755'
      recurse: yes
      state: directory

  - name: Установить права на папку '/var/log/patroni'
    file:
      path: /var/log/patroni/
      owner: postgres
      group: postgres
      mode: '0755'
      recurse: yes
      state: directory

  - name: Копирование файла конфигурации '/etc/patroni/patroni.yaml'
    template:
      src: '{{ ansible_distribution }}/patroni.yaml.j2'
      dest: /etc/patroni/patroni.yaml
      mode: 0700
      owner: postgres
      group: postgres

  - name: Копирование файла сервиса '/etc/systemd/system/patroni.service'
    template:
      src: '{{ ansible_distribution }}/patroni.service.j2'
      dest: /etc/systemd/system/patroni.service
      mode: 0644
      owner: root

  - name: Перечитаем systemd daemon
    systemd:
      daemon_reload: yes

  - name: Перезагрузка сервиса 'patroni' 
    service:
      name: patroni
      state: restarted
      enabled: yes

  when: not patroni_result.stat.exists

...