apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ k8s.rwx_sc }}
provisioner: nfs.csi.k8s.io
parameters:
  server: {{ hostvars[nfs.srv].ansible_ssh_host }}
  share: {{ nfs.path }}/
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - vers=4.1
