---
# tasks file for staff_monitoring
- name: Create namespace staff
  tags: ['staff','ns']
  k8s:
    kubeconfig: "~/.kube/config"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "staff"
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present

- name: Add repo postgres operator
  kubernetes.core.helm_repository:
    name: postgres-operator-charts
    repo_url: "https://opensource.zalando.com/postgres-operator/charts/postgres-operator"

- name: Deploy postgres operator
  kubernetes.core.helm:
    name: postgres-operator
    release_namespace: staff
    chart_ref: postgres-operator-charts/postgres-operator
    chart_version: 1.9.0
    values: "{{ lookup('template', 'chart_postgres_operator_1_9_0_values.yaml') | from_yaml }}"
