---

apiVersion: v1
kind: Pod
metadata:
  name: csi-sanlock-lvm-init
  namespace: "{{ lvm_provisioner_namespace }}"
spec:
  containers:
    - name: init
      image: quay.io/aleofreddi/csi-sanlock-lvm-lvmctrld:v0.4.5
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sanlock daemon -w 0; lvmlockd --host-id 2000; bash"]
      stdin: true
      stdinOnce: true
      tty: true
      volumeMounts:
        - mountPath: /dev
          name: dev-dir
        - mountPath: /lib/modules
          name: modules-dir
          readOnly: true
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_MODULE
          drop:
            - ALL
  restartPolicy: Never

  volumes:
    - hostPath:
        path: /dev
        type: Directory
      name: dev-dir
    - hostPath:
        path: /lib/modules
        type: Directory
      name: modules-dir