---

- name: Чтение статуса конфигурации интерфейсов
  shell: cat /etc/network/interfaces.d/* | grep '{{ ansible_ssh_host }}'
  register: conf_status
  ignore_errors: yes

- name: Настройка сетевых интерфейсов
  block:

  - name: Получить список сетевых интерфейсов
    shell: |
      ip link show | grep BROADCAST | awk '{print $2}' | sed 's/.$//'
    register: device_list

  - name: Создание массива сетевых интерфейсов
    set_fact:
      interfaces: "{{ device_list.stdout_lines | list }}"

  - name: Получение количества элементов в списке интерфейсов
    set_fact:
      interfaces_length: "{{ interfaces | length }}"

  # - name: Вывод доступных сетевых интерфейсов
    # debug:
      # msg: "Доступные сетевые интерфейсы: ({{ interfaces_length }}) {{ interfaces }}"

  - name: Создание 'bond0' если количество интерфейсов отлично от одного
    block:

    - name: Установка пакетов для создания Bond0
      apt:
        name: ifenslave
        state: latest
    
    - name: Копирование файла '/etc/network/interfaces.d/interfaces для создания 'bond'
      template:
        src: bond.j2
        dest: /etc/network/interfaces.d/bond0
        owner: root
        group: root
        mode: 0644

    when: interfaces_length != '1'

  - name: Создание одиночного интерфейса если количество интерфейсов однин
    block:

    - name: Копирование файла '/etc/network/interfaces.d/{{ interfaces[0] }}'
      template:
        src: eth.j2
        dest: /etc/network/interfaces.d/{{ interfaces[0] }}
        owner: root
        group: root
        mode: 0644

    when: interfaces_length == '1'

  - name: Удаление файла '/etc/network/interfaces'
    file:
      path: /etc/network/interfaces
      state: absent

  - name: Копирование файла '/etc/network/interfaces'
    copy:
      src: interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 

  - name: Перезагрузим сервер
    reboot:
      msg: 'Reboot'

  - name: Удаление пакетов Network-Manager
    apt:
      name: network-manager
      state: absent
      purge: yes
    ignore_errors: yes

  - name: Удаление папки '/etc/NetworkManager'
    shell:  rm -rf /etc/NetworkManager
    ignore_errors: yes

  - name: Удаление файла resolv.conf
    file:
      path: /etc/resolv.conf
      state: '{{ item }}'
    with_items:
    - absent
    - touch

  - name: Создание файла resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      line: '{{ item }}'
    with_items:
    - nameserver {{ net.bind }}
    - search {{ domain }}

  - name: Изменения файла '/etc/default/grub'
    shell: |
      cat /etc/default/grub | grep GRUB_CMDLINE_LINUX_DEFAULT | grep ipv6.disable=0
      if [ $? != 0 ]; then
      sed -i "s/parsec.max_ilev=63/parsec.max_ilev=63 ipv6.disable=0/g" /etc/default/grub
      fi

  - name: Выключаем 'ipv6'
    sysctl:
      name: net.ipv6.conf.all.disable_ipv6
      value: 1
      sysctl_file: /etc/sysctl.d/999-astra.conf
      reload: true

  - name: Выключаем 'ipv6'
    sysctl:
      name: net.ipv6.conf.lo.disable_ipv6
      value: 0
      sysctl_file: /etc/sysctl.d/999-astra.conf
      reload: true

  - name: Обновление GRUB
    shell:  update-grub
    ignore_errors: yes
         
  when: conf_status.stdout.split('.')[0] == ''

...