---

- name: Проверка группы '{{ Xrdp.group }}' в домене
  become: true
  become_method: su
  become_user: admin
  command: ipa group-find {{ Xrdp.group }} | grep 'ID'
  vars:
    ansible_become_pass: '{{ FreeIPA.pass }}'
  ignore_errors: yes
  register: status_group

- name: Подготовка контроллера домена
  block:

  - name: Создание группы '{{ Xrdp.group }}' с правами доступа по протоколу 'rdp'
    become: true
    become_method: su
    become_user: admin
    shell: ipa group-add {{ Xrdp.group }} --desc="Пользователи Xrdp"
    vars:
      ansible_become_pass: '{{ FreeIPA.pass }}'
    ignore_errors: yes

  - name: Добавим пользователя 'admin' в группу '{{ Xrdp.group }}'
    become: true
    become_method: su
    become_user: admin
    shell: ipa group-add-member {{ Xrdp.group }} --users=admin
    vars:
      ansible_become_pass: '{{ FreeIPA.pass }}'
    ignore_errors: yes

  # - name: Добавление сервиса 'xrdp-sesman' на контроллере домена для серверов кластера '{{ item.name }}'
    # become: true
    # become_method: su
    # become_user: admin
    # command: sudo ipa service-add xrdp-sesman/{{ inventory_hostname }}.{{ domain }}
    # vars:
      # ansible_become_pass: '{{ FreeIPA.pass }}'
    # ignore_errors: yes

  # - name: Создание службы HBAC 'sesman-rule' на контроллере
    # become: true
    # become_method: su
    # become_user: admin
    # command: sudo ipa hbacsvc-add xrdp-sesman --desc=xrdp-sesman
    # vars:
      # ansible_become_pass: '{{ FreeIPA.pass }}'
    # ignore_errors: yes

  # - name: Создание правила 'xrdp-sesman-rule' на контроллере
    # become: true
    # become_method: su
    # become_user: admin
    # command: sudo ipa hbacrule-add xrdp-sesman-rule --desc=xrdp-sesman
    # vars:
      # ansible_become_pass: '{{ FreeIPA.pass }}'
    # ignore_errors: yes

  # - name: Добавление узлов в правило 'xrdp-sesman-rule'
    # become: true
    # become_method: su
    # become_user: admin
    # command: sudo ipa hbacrule-add-host xrdp-sesman-rule --hosts={{ Xrdp.srv | join(' ') }}
    # vars:
      # ansible_become_pass: '{{ FreeIPA.pass }}'
    # ignore_errors: yes

  # - name: Добавление пользователей в правило 'xrdp-sesman-rule'
    # become: true
    # become_method: su
    # become_user: admin
    # command: sudo ipa hbacrule-add-user xrdp-sesman-rule --groups={{ Xrdp.group }}
    # vars:
      # ansible_become_pass: '{{ FreeIPA.pass }}'
    # ignore_errors: yes

  # - name: Добавление сервиса 'xrdp-sesman' в правило 'xrdp-sesman-rule'
    # become: true
    # become_method: su
    # become_user: admin
    # command: sudo ipa hbacrule-add-service xrdp-sesman-rule --hbacsvcs=xrdp-sesman
    # vars:
      # ansible_become_pass: '{{ FreeIPA.pass }}'
    # ignore_errors: yes

  when:
    - status_group.stdout != ''

...