---
# tasks file for conf_sysctl
- name: Create config file modules
  file:
    path: "/etc/modules-load.d/k8s.conf"
    owner: root
    group: root
    mode: '0644'
    state: "touch"
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Edit conf for modules
  blockinfile:
    path: "/etc/modules-load.d/k8s.conf"
    block: |
          overlay
          br_netfilter
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Modprobe overlay
  modprobe:
    name: overlay
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Modprobe br_netfilter
  modprobe:
    name: br_netfilter
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Enable ip forward
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    reload: true
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Enable bridge-nf-call-iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    reload: true
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Enable bridge-nf-call-ip6tables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    reload: true
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

- name: Set fs.inotify.max_user_instances
  sysctl:
    name: fs.inotify.max_user_instances
    value: '524288'
    sysctl_file: "/etc/sysctl.d/k8s.conf"
    reload: true
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo