---

- name: Проверка наличия файла '/etc/ipa/default.conf'
  stat:
    path: /etc/ipa/default.conf
  register: freeipa_result

- name: Регистрация клиентов домена FreeIPA
  block:

  - name: Установка пакетов необходимых для подключения к контроллеру домена FreeIPA
    apt:
      name:
      - fly-admin-freeipa-client
      - astra-freeipa-client
      state: latest

  - name: Удаление лишних пакетов
    apt:
      autoremove: yes

  # - name: Отключение от домена FreeIPA
    # shell: astra-freeipa-client -U -y

  # - name: Перезагрузим сервер
    # reboot:
      # msg: 'Reboot'


  - name: Подключение к домену FreeIPA
    shell: astra-freeipa-client -d {{ domain }} -u admin -p {{ freeipa.pass }} -y

  - name: Перезагрузим сервер
    reboot:
      msg: 'Reboot'

  when:
  - not freeipa_result.stat.exists
  - inventory_hostname != freeipa.srv

...