---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ kubernetes_rwo_sc }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi-sanlock-lvm.csi.vleo.net
parameters:
  volumeGroup: {{ lvm_provisioner_vg_name }}
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true