---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep ALD_Pro-client
  register: version
  ignore_errors: yes

- name: Установка клиента домена
  shell: "DEBIAN_FRONTEND=noninteractive apt-get install -q -y aldpro-client"
  when: version.stdout != relis

- name: Настройка клиента домена
  shell: /opt/rbta/aldpro/client/bin/aldpro-client-installer -c {{ domain }} -u admin -p {{ pwdadmin }} -d {{ inventory_hostname }} -i -f
  when: version.stdout != relis

- name: Перезагрузим хост
  reboot:
    reboot_timeout=300
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  shell: "sed -i '/ALD_Pro-client/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  when: version.stdout != relis