---
# tasks file for install_keepalive
#- name: install keepalived apt doistr
#  apt:
#    update_cache: yes
#    pkg:
#    - keepalived
#  become: true
#  become_method: sudo
#  when: ansible_facts.os_family == 'Debian' or ansible_facts.os_family == 'Ubuntu'

- name: Install helm alt linux
  community.general.apt_rpm:
    update_cache: true
    pkg: "helm"
  become: true
  become_method: sudo
  when: ansible_facts.os_family == 'Altlinux'
