---

- name: Установка и настройка кластера Ceph
  block:

  - name: Проверка наличия 'ssh' ключа '/home/{{ ansible_ssh_user }}/.ssh/id_rsa'
    stat:
      path: /home/{{ ansible_ssh_user }}/.ssh/id_rsa
    register: ssh_result
    ignore_errors: yes

  - name: Настройка 'ssh' для пользователя {{ ansible_ssh_user }} на серверах кластера 'Ceph'
    block:

    - name: Инсталляция пакета 'sshpass'
      dnf:
        name:
        - sshpass

    - name: Внесение изменений в конфигурационныйе файл '/etc/ssh/ssh_config'
      lineinfile:
        dest: /etc/ssh/ssh_config
        regexp: 'StrictHostKeyChecking'
        line: '    StrictHostKeyChecking  no'

    - name: Перезапуск службы 'sshd'
      service:
        name: sshd
        enabled: yes
        state: restarted

    - name: Удаление ssh ключей
      shell: rm -Rf /home/{{ ansible_ssh_user }}/.ssh/id_rsa*
      ignore_errors: yes

    - name: Генерация ssh ключа '/home/{{ ansible_ssh_user }}/.ssh/id_rsa'
      shell: echo -e "\n" | ssh-keygen -q -t rsa -f /home/{{ ansible_ssh_user }}/.ssh/id_rsa -C "" -N ""
      become: no
  
    - name: Обмен ключами между узлами кластера
      shell: |
        {% for item in CephFS.nodes %}
        sshpass -p '{{ ansible_ssh_pass }}' ssh-copy-id -i /home/{{ ansible_ssh_user }}/.ssh/id_rsa.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ ansible_ssh_user }}@{{ hostvars[item].ansible_ssh_host }}
        {% endfor %}
      become: no

    when: not ssh_result.stat.exists

  - name: Проверка установки 'Ceph'
    stat:
      path: /etc/ceph/ceph.conf
    register: ceph_result
    ignore_errors: yes

  - name: Инсталляция 'Ceph' на узлах кластера
    block:

    - name: Настройка сетевого интерфейса '{{ CephFS.net.interface}}'
      nmcli:
        type: ethernet
        ifname: '{{ CephFS.net.interface }}'
        conn_name: '{{ CephFS.net.interface }}'
        ip4: '{{ CephFS.net.network.split(".")[0] }}.{{ CephFS.net.network.split(".")[1] }}.{{ CephFS.net.network.split(".")[2] }}.{{ hostvars[inventory_hostname].ansible_ssh_host.split(".")[3] }}/{{ CephFS.net.network.split("/")[1] }}'
        state: present

    - name: Перезапуск службы 'NetworkManager'
      service:
        name: NetworkManager
        state: restarted

    - name: Инсталляция пакетов 'Сeph'
      dnf:
        name:
        - ceph-deploy
        - ceph-mgr-dashboard

    - name: Инсталляция демонов 'Ceph' на узлах кластера
      shell: |
        ceph-deploy install {{ CephFS.nodes | join(' ') }}
      when: inventory_hostname == CephFS.nodes[0]
      become: no

    - name: Перезагрузка узлов кластера
      reboot:
        msg: 'Reboot'

    - name: Настройка кластера 'Ceph'
      block:

      - name: Создаем конфигурационный файл '/home/{{ ansible_ssh_user }}/ceph.conf'
        shell: |
          ceph-deploy --overwrite-conf new {{ CephFS.nodes | join(' ') }}
        become: no

      - name: Добавление сетей в конфигурацию кластера '/home/{{ ansible_ssh_user }}/ceph.conf'
        blockinfile:
          dest: '/home/{{ ansible_ssh_user }}/ceph.conf'
          block: |
            public_network = {{ net.network }}
            cluster_network = {{ CephFS.net.network }}
        become: no

      - name: Создание мониторов
        shell: |
          ceph-deploy --overwrite-conf mon create {{ CephFS.nodes | join(' ') }}
          sleep 10
        become: no

      - name: Обмен ключами
        shell: |
          ceph-deploy gatherkeys {{ CephFS.nodes | join(' ') }}
        become: no

      - name: Распространим конфигурации по нодам кластера
        shell: |
          ceph-deploy --overwrite-conf admin {{ CephFS.nodes | join(' ') }}
        become: no

      - name: Зарегистрировать службу диспетчера Ceph на узлах кластера
        shell: |
          ceph-deploy --overwrite-conf mgr create {{ CephFS.nodes | join(' ') }}
        become: no

      - name: Распространим конфигурации по нодам кластера
        shell: |
          ceph-deploy --overwrite-conf admin {{ CephFS.nodes | join(' ') }}
        become: no

      - name: Установка сервера метаданных MDS
        shell: |
          ceph-deploy --overwrite-conf mds create {{ CephFS.nodes | join(' ') }}
        become: no

      - name: Создание OSD на дисках узлов кластера и добавить их в кластер
        shell: |
          ceph-deploy --overwrite-conf osd create --data {{ CephFS.dev[0] }} {{ item }}
        with_items: '{{ CephFS.nodes }}'
        become: no

      - name: Копирование ключей в '/etc/ceph/'
        shell: |
          cp /home/{{ ansible_ssh_user }}/ceph.*.keyring /etc/ceph/

      - name: Установка параметров безопасности
        shell: |
          ceph config set mon auth_allow_insecure_global_id_reclaim false
          ceph config set mon mon_warn_on_insecure_global_id_reclaim false
          ceph config set mon mon_warn_on_insecure_global_id_reclaim_allowed false
          ceph mgr module disable restful

      - name: Создание пула 'kubernetes'
        shell: |
          ceph osd pool create kubernetes 64

      - name: Создание 'cephfs'
        shell: |
          ceph osd pool create k8sfs_data 64
          ceph osd pool create k8sfs_metadata 64
          ceph fs new cephfs k8sfs_metadata k8sfs_data

      - name: Создание клиента 'kubernetes'
        shell: |
          ceph auth add client.kubernetes mon 'allow r' osd 'allow rwx pool=kubernetes,allow rwx pool=k8sfs_data' mds 'allow rw'

      - name: Инициализация пула 'kubernetes'
        shell: |     
          rbd pool init kubernetes
 
      when: inventory_hostname == CephFS.nodes[0]

    when: not ceph_result.stat.exists

  when: inventory_hostname in CephFS.nodes

...












