---
- name: Create namespace for ceph provisioner
  tags: ['common','ns']
  k8s:
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ceph_namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present

- name: Create rbd config map
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-config-map.yaml') }}"

- name: Create rbd kms
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-kms-config.yaml') }}"

- name: Create rbd conf
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/ceph-conf.yaml') }}"

- name: Create rbd secret
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-secret-rbd.yaml') }}"


- name: Create rbd nodeplagin rbac
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-nodeplugin-rbac.yaml') }}"

- name: Create rbd provisioner rbac
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-provisioner-rbac.yaml') }}"

- name: Create rbd rbdplugin provisioner
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-rbdplugin-provisioner.yaml') }}"

- name: Create rbd rbdplugin 
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-rbdplugin.yaml') }}"

#- name: Create rbd nodeplagin psp
#  k8s:
#    state: present
#    force: no
#    kubeconfig: "/home/{{ local_admin }}/.kube/config"
#    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-nodeplugin-psp.yaml') }}"

#- name: Create rbd provisioner psp
#  k8s:
#    state: present
#    force: no
#    kubeconfig: "/home/{{ local_admin }}/.kube/config"
#    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csi-provisioner-psp.yaml') }}"

- name: Create rbd driver
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/rbd/csidriver.yaml') }}"

- name: Create rbd StorageClass
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/storageclass-rbd.yaml') }}"


####### cephfs
- name: Create cephfs secret
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/cephfs/csi-secret-cephfs.yaml') }}"

- name: Create cephfs provisioner rbac
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/cephfs/csi-provisioner-rbac.yaml') }}"

- name: Create cephfs nodeplugin rbac
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/cephfs/csi-nodeplugin-rbac.yaml') }}"

- name: Create cephfs plugin
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/cephfs/csi-cephfsplugin.yaml') }}"

- name: Create cephfs plugin provisioner
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/cephfs/csi-cephfsplugin-provisioner.yaml') }}"

- name: Create cephfs driver
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/cephfs/csidriver.yaml') }}"

- name: Create cephfs StorageClass
  k8s:
    state: present
    force: no
    kubeconfig: "/home/{{ local_admin }}/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/storageclass-cephfs.yaml') }}"





