---

- name: Проверка наличия файла '{{ repo.path }}'
  stat:
    path: '{{ repo.path }}'
  register: repo_result

- name:
  block:

  - name: Инсталляция 'docker' пакетов
    dnf:
      name:
      - docker-ce
      - docker-ce-cli
      - docker-compose
      - createrepo_c
      - dnf-utils

  - name: Создание папок репозиториев
    file:
      state: directory
      path: '{{ repo.path }}/nginx'
      mode: 0755

  - name: Создание файла 'docker-compose.yaml'
    template:
      src: docker-compose.j2
      dest: /tmp/docker-compose.yaml
      owner: root
      group: root
      mode: 0644

  - name: Создание файла 'nginx.conf'
    template:
      src: nginx.j2
      dest: '{{ repo.path }}/nginx/nginx.conf'
      owner: root
      group: root
      mode: 0644

  - name: Перезапуск службы 'docker'
    service:
      name: docker
      enabled: yes
      state: restarted

  - name: Запуск 'docker-compose'
    shell: |
      cd /tmp && docker-compose up -d

  - name: Создание файла '/etc/yum.repos.d/redos8_base_src.repo'
    template:
      src: redos.j2
      dest: '/etc/yum.repos.d/redos8_base_src.repo'
      owner: root
      group: root
      mode: 0644

  - name: Создание файла 'repo.sh'
    template:
      src: repo.j2
      dest: /tmp/repo.sh
      owner: root
      group: root
      mode: 0744

  # - name: Запуск 'helm.sh'
    # shell: |
      # cd /tmp
      # ./repo.sh

  when:
    - inventory_hostname == repo.srv 
    - not repo_result.stat.exists

# - name: Проверка наличия файла '/etc/apache2-repo/sites-available/000-default.conf'
  # stat:
    # path: /etc/apache2-repo/sites-available/000-default.conf
  # register: stat_result

# - name: Настройка Apache2@repo
  # block:

  # - name: Обновление репозиториев
    # apt:
      # update_cache: yes

  # - name: Получение версии 'PHP'
    # shell: |
      # apt-cache show php | grep Depends | awk '{print substr($2,4)}'
    # register: tmp

  # - name: Запись доступной версии 'PHP' в переменную 'php_version'
    # set_fact:
      # php_version: '{{ tmp.stdout_lines[0] }}'

  # - name: Инсталляция сервера 'Apache'
    # apt:
      # name:
      # - apache2
      # - libapache2-mod-php{{ php_version }}
      # state: latest
      # update_cache: yes

  # - name: Удаление папок и файлов 'Apache2@Repo'
    # shell: '{{ item }}'
    # with_items:
      # - rm -rf /etc/apache2-repo
      # - rm -rf /var/log/apache2-repo
      # - rm -f /usr/local/sbin/*repo

  # - name: Модифицируем файлы конфигурации 'Apache2@Repo'
    # shell: |
      # sed -i "s/zero_if_notfound: no/zero_if_notfound: yes/g" /etc/parsec/mswitch.conf
      # sh /usr/share/doc/apache2/examples/setup-instance repo
      # sed -i "s/# AstraMode on/AstraMode off/g" /etc/apache2-repo/apache2.conf
      # sed -i "s/Listen 80/Listen {{ repo.port }}/g" /etc/apache2-repo/ports.conf
      # sed -i "s/;date.timezone =/date.timezone = {{ ntp.timezone }}/g" /etc/php/{{ php_version }}/apache2/php.ini
      # sed -i "s/post_max_size = 8M/post_max_size = 32M/g" /etc/php/{{ php_version }}/apache2/php.ini
      # sed -i "s/max_execution_time = 30/max_execution_time = 300/g" /etc/php/{{ php_version }}/apache2/php.ini
      # sed -i "s/max_input_time = 60/max_input_time = 300/g" /etc/php/{{ php_version }}/apache2/php.ini

  # - name: Очистка файла '/etc/apache2-repo/sites-available/000-default.conf'
    # file:
      # path: /etc/apache2-repo/sites-available/000-default.conf
      # state: '{{ item }}'
    # with_items:
    # - absent
    # - touch

  # - name: Добавление виртуального сервера 'Apache2@Repo'
    # blockinfile:
      # dest: /etc/apache2-repo/sites-available/000-default.conf
      # marker: '### repo ###'
      # block: |
        # <VirtualHost {{ hostvars[repo.srv].ansible_ssh_host }}:{{ repo.port }}>
           # ServerName {{repo.srv}}.{{ domain }}
           # ServerAlias repo
           # ServerAdmin webmaster@localhost
           # DocumentRoot /var/www/repo
        # </VirtualHost>

  # - name: Создание символьной ссылки на репозиторий
    # file:
      # src: /srv/repo
      # dest: /var/www/repo
      # state: link

  # - name: Перезапуск службы 'Apache2@Repo'
    # service:
      # name: apache2@repo
      # enabled: yes
      # state: restarted

  # when:
  # - inventory_hostname == repo.srv
  # - not stat_result.stat.exists
  
# - name: Подключение к сетевому репозиторию
  # block:

  # - name: Удаление файла '/etc/apt/sources.list'
    # file:
      # path: /etc/apt/sources.list
      # state: '{{ item }}'
    # with_items:
    # - absent
    # - touch

  # - name: Удаление файла '/etc/apt/sources.list.d/sources.list'
    # file:
      # path: /etc/apt/sources.list.d/sources.list
      # state: '{{ item }}'
    # with_items:
    # - absent
    # - touch

  # - name: Заполняем файл '/etc/apt/sources.list.d/sources.list'
    # lineinfile:
      # path: /etc/apt/sources.list.d/sources.list
      # line: 'deb http://{{ hostvars[repo.srv].ansible_ssh_host }}:{{ repo.port }}/{{ item}} {{ _repo.dist }} {{ _repo.res }}'
      # state: present
    # with_items:
    # - '{{ _repo.name_iso }}'

  # - name: Обновление репозиториев
    # apt:
      # update_cache: yes

  # when:
  # - inventory_hostname != repo.srv
  # - not sources_result.stat.exists

...