---

- name: Проверка наличия файла '/etc/systemd/system/patroni.service'
  stat:
    path: /etc/systemd/system/patroni.service
  register: patroni_result

- name: Создания серверов
  block:

  - name: Установка пакетов 'python3'
    apt:
      update_cache: yes
      name:
        - python3
        - python3-pip
        - python3-dev
        - libpq-dev
        - curl
        - etcd-client
      state: latest

  - name: Установка 'patroni[etcd]'
    pip:
      executable: pip3
      extra_args: --no-warn-script-location
      name:
        - patroni[etcd]
        - psycopg2
        - psycopg2-binary
        - python-etcd
        # - wheel

  - name: Копирование файла конфигурации '/etc/patroni.yaml'
    template:
      src: '{{ ansible_distribution }}/patroni.yaml.j2'
      dest: /etc/patroni.yaml
      mode: 0700
      owner: postgres
      group: postgres

  - name: Копирование файла сервиса '/etc/systemd/system/patroni.service'
    template:
      src: '{{ ansible_distribution }}/patroni.service.j2'
      dest: /etc/systemd/system/patroni.service
      mode: 0644
      owner: root

  - name: Перечитаем systemd daemon
    systemd:
      daemon_reload: yes

  - name: Перезагрузка сервиса 'patroni' 
    service:
      name: patroni
      state: restarted
      enabled: yes

  when: not patroni_result.stat.exists

...