---
# tasks file for add_k8s_cluster

- name: cluster configuration copy
  template:
    src: cluster_config.yaml.j2
    dest: '/tmp/cluster_config.yaml'
  tags: k8s_config


- name: pull images
  shell: kubeadm config images pull
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo
  ignore_errors: yes

- name: initialize the cluster
  shell: kubeadm init --upload-certs --config /tmp/cluster_config.yaml >> ~/cluster_initialized.txt
  register: init_cluster
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo
  ignore_errors: yes

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: cluster configuration copy
  copy:
    src: '/etc/kubernetes/admin.conf'
    dest: '/home/{{ local_admin }}/.kube/config'
    remote_src: yes
    owner: '{{ local_admin }}'
  tags: k8s_config
  become: "{{ 'no' if ansible_user == 'root' else 'yes' }}"
  become_method: sudo

