---

- name: Чтение статуса 'Prometheus'
  shell: kubectl get pods -n monitoring | grep 'prometheus-prometheus-prometheus-0' | grep 'Running'
  register: status_prometheus
  become: false
  ignore_errors: yes

- name:
  block:

  - name: Создание пространства имен для 'Monitoring'
    kubernetes.core.k8s:
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: monitoring
          labels:
            pod-security.kubernetes.io/enforce: privileged
      state: present

  - name: Добавление репозитория 'prometheus' для Helm
    kubernetes.core.helm_repository:
      name: prometheus
      repo_url: https://prometheus-community.github.io/helm-charts
      force_update: true
    become: false

  - name: Развертывание 'Prometheus v43.2.1'
    kubernetes.core.helm:
      name: prometheus
      release_namespace: monitoring
      chart_ref: prometheus/kube-prometheus-stack
      chart_version: 43.2.1
      values: "{{ lookup('template', 'Helm_Charts/kube-prometheus-stack.yaml') | from_yaml }}"
      force: true
    become: false

  - name: Ожидаем запуска контейнера 'Prometheus'
    ansible.builtin.pause:
      minutes: 2

  - name: Установка панелей инструментов для Grafana
    kubernetes.core.k8s:
      state: present
      namespace: monitoring
      force: true
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        - "{{ lookup('file', 'grafana/grafana_dashboard_ceph-cephfs.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/grafana_dashboard_ceph-cluster.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/grafana_dashboard_elasticsearch-cluster.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/grafana_dashboard_postgresql_database.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/grafana_dashboard_rabbitmq-overview.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/grafana_dashboard_redis-operator.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/grafana_dashboard_redis-overview.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/Prometheus_PodMonitor_Postgres.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/PrometheusRule_rabbitmq-cluster-operator.yaml') | from_yaml }}"
        - "{{ lookup('file', 'grafana/rabbitmq-servicemonitor.yaml') | from_yaml }}"
    become: false

  when: status_prometheus.stdout == ''

...