---

- name: Проверка наличия файла '/usr/local/bin/k8s_renew_cert.sh'
  stat:
    path: /usr/local/bin/k8s_renew_cert.sh
  register: renew_cert_result

- name:
  block:

  - name: Копирование скрипта демона
    copy:
      src: renew_cert.j2
      dest: /usr/local/bin/k8s_renew_cert.sh
      mode: 0755
      force: yes

  - name: Создание задания на обновление сертификатов кластера
    cron:
      name: Renew_Certs_Kubernetes
      job: /usr/local/bin/k8s_renew_cert.sh
      minute: "0"
      hour: "0"
      day: "*"
      month: "*"
      weekday: "*"
      user: root

  when:
    - not renew_cert_result.stat.exists

...