---

- name: Проверка наличия 'ssh' ключа '/home/{{ ansible_ssh_user }}/.ssh/id_rsa'
  stat:
    path: /home/{{ ansible_ssh_user }}/.ssh/id_rsa
  register: ssh_result
  ignore_errors: yes

- name: Генерация ssh ключа пользователя '{{ ansible_ssh_user }}'
  user:
    name: '{{ ansible_ssh_user }}'
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  become: no
  when: not ssh_result.stat.exists

...