---

- name: Проверка наличия файла '/root/.ssh/id_rsa'
  stat:
    path: /root/.ssh/id_rsa
  register: id_rsa_result

- name: Генерация ssh ключа пользователя 'root'
  user:
    name: root
    state: present
    password: "{{ root_pass | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  when:
    - not id_rsa_result.stat.exists
    - root_pass is defined

...