---

- name: Создание прав sudo пользователю '{{ ansible_ssh_user }}'
  shell: |
    echo "{{ ansible_ssh_user }} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/{{ ansible_ssh_user }}
    chmod 0440 /etc/sudoers.d/{{ ansible_ssh_user }}

...