---

- name: Чтение статуса часового пояса
  shell: cat /etc/timezone
  register: timezone_status

- name: Установка часового пояса '{{ ntp.timezone }}'
  timezone:
    name: '{{ ntp.timezone }}'
  when: timezone_status.stdout != ntp.timezone


- name: Проверка наличия файла '/etc/chrony/chrony.conf'
  stat:
    path: /etc/chrony/chrony.conf
  register: chrony_status

- name: Настройка 'Chrony'
  block:

  - name: Удаление пакета 'ntp'
    apt:
      name:
      - ntp
      - ntpdate
      autoremove: yes
      purge: true

  - name: Установка пакета 'chrony'
    apt:
      name: chrony
      state: latest

  - name: Создание файла '/etc/chrony/chrony.conf' на сервере времени
    template:
      src: chrony_s.j2
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
    when: inventory_hostname == ntp.srv

  - name: Создание файла '/etc/chrony/chrony.conf' на клиентах
    template:
      src: chrony_c.j2
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
    when: inventory_hostname != ntp.srv

  - name: Перезапуск службы 'chrony'
    service:
      name: chrony
      enabled: yes
      state: restarted

  when: not chrony_status.stat.exists

...