---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep PXE-server
  register: version
  ignore_errors: yes

- name: Создание папки /srv
  file:
    path: /srv/iso
    state: directory
    recurse: yes
  when: version.stdout != relis

- name: Копирование iso-образов
  copy:
    src: "files/AstraLinux/"
    dest: "/srv/iso/"
    force: no
  when: version.stdout != relis    

- name: PXE-server | get names
  find:
    paths: "/srv/iso/"
    patterns: "*.iso"
  register: found_isos
  when: version.stdout != relis    

- name: PXE-server | Создание папки /repo
  file:
    state: directory
    path: "/srv/repo/"
  when: version.stdout != relis    

- name: PXE-server | Создание папок 
  file:
    state: directory
    path: "/srv/repo/{{ item.path.split('/')[3].split('.')[0] }}"
  with_items:
  - "{{ found_isos.files }}"
  when: version.stdout != relis    

- name: PXE-server | Монтируем репозитории
  mount:
    state: mounted
    path: "/srv/repo/{{ item.path.split('/')[3].split('.')[0] }}"
    src: "{{ item.path }}"
    fstype: iso9660
    opts: ro
  with_items:
  - "{{ found_isos.files }}"
  when: version.stdout != relis    

- name: PXE-server | Удалим файл sources.list
  file:
    path: /etc/apt/sources.list
    state: "{{ item }}"
  with_items:
  - absent
  - touch
  when: version.stdout != relis    

- name: PXE-server | Сздадим файл sources.list
  lineinfile:
    path: /etc/apt/sources.list
    line: "deb file:///srv/repo/{{item}} smolensk contrib main non-free"
    state: present
  with_items:
  - ['mo','mo-dev','mo-update', 'mo-dev-update']
  when: version.stdout != relis
 
- name: PXE-server | Установка пакетов
  apt:
    name:
    - astra-update
    - fly-astra-update
    state: latest
    update_cache: yes
  when: version.stdout != relis

- name: PXE-server | Чтение версии установленного апдейта
  shell: cat /etc/astra_update_version
  register: update_version
  ignore_errors: yes
  when: version.stdout != relis

- name: PXE-server | Апдейт AstraLinux
  shell: astra-update -A -r
  when: version.stdout != relis

- name: PXE-server | Изменения файла etc/modprobe.d/blacklist-astra.conf
  lineinfile:
    dest: /etc/modprobe.d/blacklist-astra.conf
    regexp: "{{ item.do }}"
    line: "{{ item.posle }}"
  with_items:
  - { do: 'blacklist ast', posle: '#blacklist ast'}
  - { do: 'blacklist mgag200', posle: '#blacklist mgag200'}
  when: version.stdout != relis

- name: PXE-server | Чтение текущей версии ОС
  shell: cat /etc/astra_update_version
  register: update_new_version
  ignore_errors: yes
  when: version.stdout != relis

- name: PXE-server | Перезагрузка ОС
  reboot:
    msg: "Reboot"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 60
  when: update_new_version.stdout != update_version.stdout
  ignore_errors: yes  

- name: PXE-server | Установка Apache
  apt:
    update_cache: yes
    name:
    - apache2
    - tftpd-hpa
    state: latest
  when: version.stdout != relis    

- name: PXE-server | Изменим конфигурацию Apache
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '#AstraMode'
    line: AstraMode off
    state: present
  when: version.stdout != relis    

- name: PXE-server | 000-default.conf
  copy:
    src: ./000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
    force: no
  when: version.stdout != relis    

- name: PXE-server | Перезагрузка Apache
  service:
    name: apache2
    enabled: yes
    state: restarted
  when: version.stdout != relis    
  
- name: PXE-server | Создание папки /srv/tftp
  file:
    state: directory
    path: "/srv/tftp/"
  when: version.stdout != relis    

- name: PXE-server | copy uefi pxe files
  unarchive:
    src: netinst.tar.gz
    dest: /srv/tftp
    mode: '0777'
  when: version.stdout != relis    

- name: PXE-server | create symlink
  file:
    src: "/srv/repo"
    dest: "/var/www/html/repo"
    state: link
    force: yes
  when: version.stdout != relis    

- name: PXE-server | create tftp/
  file:
    state: directory
    path: "/srv/tftp/{{ item.path.split('/')[3].split('.')[0].split('-')[0] }}"
  with_items: "{{ found_isos.files }}"
  when: item.path.split('/')[3].split('.')[0] | length < 5 and version.stdout != relis    

- name: PXE-server | copy initrd 
  copy:
    src: "/srv/repo/{{ item.path.split('/')[3].split('.')[0] }}/netinst/initrd.gz"
    dest: "/srv/tftp/{{ item.path.split('/')[3].split('.')[0] }}"
    remote_src: yes
    directory_mode: yes
  with_items: "{{ found_isos.files }}"
  when: item.path.split('/')[3].split('.')[0] | length < 5 and version.stdout != relis    

- name: PXE-server | copy linux
  copy:
    src: "/srv/repo/{{ item.path.split('/')[3].split('.')[0] }}/netinst/linux"
    dest: "/srv/tftp/{{ item.path.split('/')[3].split('.')[0] }}"
    remote_src: yes
    directory_mode: yes
  with_items: "{{ found_isos.files }}"
  when: item.path.split('/')[3].split('.')[0] | length < 5 and version.stdout != relis    

- name: PXE-server | copy grub.cfg
  copy:
    src: ./grub.cfg
    dest: /srv/tftp/debian-installer/amd64/grub/grub.cfg
  when: version.stdout != relis    

- name: PXE-server | user md5 for passwords in preseed
  shell: "openssl passwd -1 {{ user_pass }}"
  register: user_pass_preseed
  when: version.stdout != relis    

- name: PXE-server | root md5 for passwords in preseed
  shell: "openssl passwd -1 {{ root_pass }}"
  register: root_pass_preseed
  when: version.stdout != relis    

- name: PXE-server | root md5 for passwords in preseed
  shell: "openssl passwd -1 {{ grub_pass }}"
  register: grub_pass_preseed
  when: version.stdout != relis    

- name: PXE-server | create directory
  file:
    path: /srv/repo/update
    state: directory
  when: version.stdout != relis    

- name: PXE-server | create update service
  template:
    src: update.service
    dest: "/srv/repo/update/update.service"
    mode: '0444'
  when: version.stdout != relis    

- name: PXE-server | create update.sh fsb
  template:
    src: 'update_fsb'
    dest: '/srv/repo/update/{{ item }}'
    mode: '0444'
  loop: "{{ query('inventory_hostnames', 'FSB') }}"
  when: version.stdout != relis    

- name: PXE-server | create update.sh
  template:
    src: 'update_mo'
    dest: '/srv/repo/update/{{ item }}'
    mode: '0444'
  loop: "{{ query('inventory_hostnames', 'MO') }}"
  when: version.stdout != relis    

- name: PXE-server | copy preseed.cfg
  template:
    src: preseed_fsb
    dest: "/srv/tftp/fsb/preseed{{ item }}.cfg"
    mode: '0444'
  loop: "{{ query('inventory_hostnames', 'FSB') }}"
  when: version.stdout != relis    

- name: PXE-server | copy preseed.cfg
  template:
    src: preseed_mo
    dest: "/srv/tftp/mo/preseed{{ item }}.cfg"
    mode: '0444'
  loop: "{{ query('inventory_hostnames', 'MO') }}"
  when: version.stdout != relis    

- name: PXE-server | add block
  blockinfile:
    path: /srv/tftp/debian-installer/amd64/grub/grub.cfg
    state: present
    block: |
      # Установка Astra Linux SE Смоленск
      menuentry 'Install Astra Linux SE Smolensk {{ repo | upper }} {{ item }}' {
      set background_color=black
      linux    /fsb/linux modprobe.blacklist=evbug debian-installer/allow_unauthenticated=true auto=true priority=critical debian-installer/locale=en_US console-keymaps-at/keymap=ru hostname=srv astra-license/license=true url=tftp://{{ ansible_ssh_host }}/fsb/preseed{{ item }}.cfg interface=auto netcfg/dhcp_timeout=60
      initrd   /fsb/initrd.gz
      }
    marker: "# {{ repo | upper }} {{ item }}"
  loop: "{{ query('inventory_hostnames', 'FSB') }}"
  when: version.stdout != relis    

- name: PXE-server | add block
  blockinfile:
    path: /srv/tftp/debian-installer/amd64/grub/grub.cfg
    state: present
    block: |
      # Установка Astra Linux SE Смоленск
      menuentry 'Install Astra Linux SE Smolensk {{ repo | upper }} {{ item }}' {
      set background_color=black
      linux    /mo/linux modprobe.blacklist=evbug debian-installer/allow_unauthenticated=true auto=true priority=critical debian-installer/locale=en_US console-keymaps-at/keymap=ru hostname=srv astra-license/license=true url=tftp://{{ ansible_ssh_host }}/mo/preseed{{ item }}.cfg interface=auto netcfg/dhcp_timeout=60
      initrd   /mo/initrd.gz
      }
    marker: "# {{ repo | upper }} {{ item }}"
  loop: "{{ query('inventory_hostnames', 'MO') }}"
  when: version.stdout != relis    

- name: PXE-server | Запишем версию ПО если ее не разу не было (Install)
  become: true
  shell: "echo '{{ relis }}' >> /etc/software.conf"
  when: version.stdout == ""
  ignore_errors: yes

- name: PXE-server | Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i 's/{{version.stdout}}/{{ relis }}/g' /etc/software.conf"
  when: version.stdout != relis
  ignore_errors: yes
