Storage {
  Name = bacula-sd
  SDPort = 9103
  WorkingDirectory = "/var/lib/bacula"
  Pid Directory = "/run/bacula"
  Maximum Concurrent Jobs = 1
  SDAddress = {{ bacula_server }}
}

Director {
  Name = bacula-dir
  Password = "pVsoRW6_Q8SxeCSaKRnqYkuswI8Q3tFg4"
}

Director {
  Name = bacula-mon
  Password = "ZSP06nhO4KpyxW7XKBjeOatGf9MTL_ADD"
  Monitor = yes
}

Device {
  Name = Device-BackUP
  Media Type = File
  Archive Device = /opt/backup
  LabelMedia = yes;
  Random Access = Yes;
  AutomaticMount = yes;
  RemovableMedia = no;
  AlwaysOpen = no;
  Maximum Concurrent Jobs = 5
}

Messages {
  Name = Standard
  director = bacula-dir = all
}
