FileDaemon {
  Name = bacula-fd
  FDport = 9102
  WorkingDirectory = /var/lib/bacula
  Pid Directory = /run/bacula
  Maximum Concurrent Jobs = 20
  Plugin Directory = /usr/lib/bacula
  FDAddress = {{ bacula_server }}
}

Director {
  Name = bacula-dir
  Password = "a9obYqJMXLLmmgZpebAbSf_tqVs6TKSpa"
}

Messages {
  Name = Standard
  director = bacula-dir = all, !skipped, !restored
}

Director {
  Name = bacula-mon
  Password = "sAWTvV55nak4D4mInZNfCrdRAKw6ga_DX"
  Monitor = yes
}
