---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: "{{ registry_namespace }}"
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
#---
#kind: Endpoints
#apiVersion: v1
#metadata:
# name: registry
#subsets:
# - addresses:
#     - ip: 10.252.253.214
#   ports:
#     - port: 5000
