---

- name: Настройка узлов кластера
  block:
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/Network.yaml'
    - include_tasks: '{{ ansible_distribution }}/{{ ansible_distribution_version }}/Install_Ceph.yaml'
    - include_tasks: 'Init_Ceph.yaml'
  when: inventory_hostname in Ceph.nodes

...