---

- name: 3.29.3 | Проверка наличия файла '/etc/keepalived/keepalived.conf'
  stat:
    path: /etc/keepalived/keepalived.conf
  register: keepalived_result
  ignore_errors: yes

- name: 3.29.3 | Установка 'keepalived'
  block:

  - name: 3.29.3 | Установка пакета 'Keepalived'
    dnf:
      name:
        - keepalived
        - curl

  - name: 3.29.3 | Очистка файла '/etc/keepalived/keepalived.conf'
    file:
      path: /etc/keepalived/keepalived.conf
      state: '{{ item }}'
    with_items:
      - absent
      - touch

  - name: 3.29.3 | Внесение изменений в файл '/etc/keepalived/keepalived.conf'
    blockinfile:
      path: /etc/keepalived/keepalived.conf
      create: yes
      state: present
      marker: ""
      block: |
        vrrp_script check_apiserver {
          script "/etc/keepalived/check_apiserver.sh"
          interval 10
          timeout 10
          fall 1
          rise 2
        }
        vrrp_instance Virtual_IP {
          interface {{ ansible_default_ipv4.interface }}
          virtual_router_id 230
          state BACKUP
          priority {{ 250 - k8s.masters.index(inventory_hostname)*10 }}
          advert_int 1
          unicast_src_ip primary_private_IP
          unicast_peer {
            secondary_private_IP
          }
          authentication {
            auth_type PASS
            auth_pass Keepalived_SecPassWord
          }
          virtual_ipaddress {
            {{ k8s.keepalived_IP }}/24 dev {{ ansible_default_ipv4.interface }} label {{ ansible_default_ipv4.interface }}:0
          }
          track_script {
            check_apiserver
          }
        }

  - name: 3.29.3 | Внесение изменений в файл '/etc/keepalived/keepalived.conf'
    lineinfile:
      dest: /etc/keepalived/keepalived.conf
      regexp: 'state BACKUP'
      line: '  state MASTER'
    when: inventory_hostname == k8s.masters[0]

  - name: 3.29.3 | Создаем конфигурацию '/etc/keepalived/check_apiserver.sh'
    copy:
      src:  'check_apiserver.sh.j2'
      dest: '/etc/keepalived/check_apiserver.sh'
      mode: 0755

  - name: 3.29.3 | Запускаем службу 'Keepalived'
    service:
      name: keepalived
      state: restarted
      enabled: yes

  when:
    - inventory_hostname in k8s.masters
    - not keepalived_result.stat.exists
    - k8s.keepalived_IP is defined
...