---

- name: Проверка наличия файла '/etc/modules-load.d/k8s.conf'
  stat:
    path: /etc/modules-load.d/k8s.conf
  register: modules_result
  ignore_errors: yes

- name: Настройка параметров ядра при загрузке
  block:

  - name: Создание файла '/etc/sysctl.d/999-cve-2019-14899.conf'
    copy:
      dest: '/etc/sysctl.d/999-cve-2019-14899.conf'
      content: |
        net.ipv4.conf.default.rp_filter=0
        net.ipv4.conf.all.rp_filter=0

  - name: Создание файла '/etc/sysctl.d/k8s.conf'
    copy:
      dest: '/etc/sysctl.d/k8s.conf'
      content: |
        net.ipv4.ip_local_reserved_portss=30000-32767
        net.bridge.bridge-nf-call-arptables=1
        net.bridge.bridge-nf-call-iptables=1
        net.bridge.bridge-nf-call-ip6tables=1
        net.ipv4.ip_forward=1
        fs.inotify.max_user_instances=524288
        vm.swappiness=0

  - name: Создание файла '/etc/modules-load.d/k8s.conf'
    copy:
      dest: '/etc/modules-load.d/k8s.conf'
      content: |
        overlay
        br_netfilter

  - name: Подгружаем модуль ядра 'overlay'
    modprobe:
      name: overlay

  - name: Подгружаем модуль ядра 'br_netfilter'
    modprobe:
      name: br_netfilter

  - name: Отключаем 'swap'
    shell: |
      sed -i '/swap/s/^/#/' /etc/fstab

  - name: Перезагрузка ОС
    reboot:
      msg: 'Reboot'

  when: not modules_result.stat.exists

...