---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep DrWeb-server
  register: version
  ignore_errors: yes

- name: Установка пакетов
  apt:
    name:
    - astra-digsig-oldkeys
    state: latest
    update_cache: yes
  when: version.stdout != relis

- name: Копирование необходимых пакетов
  copy:
    src: DrWeb-server/
    dest: /opt/distr/DrWeb-server/
    mode: '0777'
    directory_mode: yes
    force: yes
  when: version.stdout != relis

- name: Создание конфига установки
  template:
    src: preseed
    dest: /opt/distr/DrWeb-server
  when: version.stdout != relis

- name: Установка сервера
  shell: cd /opt/distr/DrWeb-server && ./drweb-11.00.2-201901123-esuite-server-unix-linux-x86_64.tar.gz.run -- --preseed /opt/distr/DrWeb-server/preseed
  when: version.stdout != relis

#- name: Установка Extra дополнений
#  shell: cd /opt/distr/DrWeb-server && ./drweb-11.00.2-201905070-esuite-extra-unix-linux-all.tar.gz.run
#  when: version.stdout != relis

- name: Перзапуск сервиса
  service:
    name: drwcsd
    enabled: yes
    state: restarted
  when: version.stdout != relis

- name: Login & Password
  debug:
    msg: "Login:admin  Password:{{DrWeb_Password}}"
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  shell: "sed -i '/DrWeb-server/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  become: true
  when: version.stdout != relis
