---

- name: Проверка наличия файла '/etc/modules-load.d/k8s.conf'
  stat:
    path: /etc/modules-load.d/k8s.conf
  register: modules_result
  ignore_errors: yes

- name: Настройка параметров ядра при загрузке
  block:

  - name: Создаем файл '/etc/modules-load.d/k8s.conf'
    file:
      path: /etc/modules-load.d/k8s.conf
      mode: 0644
      state: touch

  - name: Заполняем файл '/etc/modules-load.d/k8s.conf'
    blockinfile:
      path: /etc/modules-load.d/k8s.conf
      block: |
        overlay
        br_netfilter

  - name: Подгружаем модуль ядра 'overlay'
    modprobe:
      name: overlay

  - name: Подгружаем модуль ядра 'br_netfilter'
    modprobe:
      name: br_netfilter

  - name: Включаем 'ip forward'
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true

  - name: Включаем 'bridge-nf-call-iptables'
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true

  - name: Включаем 'bridge-nf-call-ip6tables'
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true

  - name: Включаем 'net.ipv4.ip_forward'
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true

  - name: Устанавливаем значение 'fs.inotify.max_user_instances'
    sysctl:
      name: fs.inotify.max_user_instances
      value: 524288
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true

  - name: Запрет 'swap'
    sysctl:
      name: vm.swappiness
      value: 0
      sysctl_file: /etc/sysctl.d/k8s.conf
      reload: true

  when: not modules_result.stat.exists

...