---

- name: Проверка наличия файла '/home/{{ ansible_ssh_user }}/.kube/config'
  stat:
    path: /home/{{ ansible_ssh_user }}/.kube/config
  register: result
  ignore_errors: true

- name: Создание кластера 'Kubernetes'
  block:

  - name: Создаем конфигурацию кластера 'Kubernetes'
    template:
      src: cluster_config.yaml.j2
      dest: '/tmp/cluster_config.yaml'

  - name: Инициализируем кластер 'Kubernetes'
    shell: kubeadm init --upload-certs --config /tmp/cluster_config.yaml >> /tmp/cluster_initialized.txt
    register: init_cluster
    ignore_errors: true

  - name: Создаем директорию '/home/{{ ansible_ssh_user }}/.kube'
    file:
      path: '/home/{{ ansible_ssh_user }}/.kube'
      state: directory
      mode: 0755

  - name: Копируем конфигурацию кластера в домашний каталог администратора '{{ ansible_ssh_user }}'
    copy:
      src: '/etc/kubernetes/admin.conf'
      dest: '/home/{{ ansible_ssh_user }}/.kube/config'
      remote_src: true

  when: not result.stat.exists

...