---

- name: Настройка узлов кластера
  block:
    - import_tasks: Configure_kernel.yaml
    # - import_tasks: Install_Keepalived.yaml
    # - import_tasks: Install_HAProxy.yaml
    - import_tasks: Install_Kubernetes.yaml
  when: inventory_hostname in k8s.masters or inventory_hostname in k8s.workers

- name: Создание кластера
  block:
    - import_tasks: K8s_Creating_Cluster.yaml
    # - import_tasks: K8s_Remove_Taint.yaml 
  when: inventory_hostname == k8s.masters[0]

- name: Регистрация узлов Masters
  include_tasks: K8s_Adding_Master.yaml
  with_items: '{{ k8s.masters }}'
  when: inventory_hostname == k8s.masters[0]

- name: Регистрация узлов Workers
  include_tasks: K8s_Adding_Worker.yaml
  with_items: '{{ k8s.workers }}'
  when: inventory_hostname == k8s.masters[0]

- name: Добавление провайдеров в кластер
  block:
    - import_tasks: K8s_Adding_Network.yaml
    - import_tasks: K8s_Adding_NodeLocalDNS.yaml
    # - import_tasks: K8s_Adding_CephFS.yaml
    - import_tasks: K8s_Adding_Provisioners_LVM.yaml
    - import_tasks: K8s_Adding_Provisioners_NFS.yaml
  when: inventory_hostname == k8s.masters[0]

- name: Регистрация сервисов в кластере
  block:
    - import_tasks: Staff_Operator_Postgres.yaml
    - import_tasks: Staff_Monitoring.yaml
    - import_tasks: Staff_Logging.yaml
    - import_tasks: Staff_Operator_Rabbitmq.yaml
    - import_tasks: Staff_Operator_Redis.yaml
  when: inventory_hostname == k8s.masters[0]







# - import_tasks: K8s_untain_master.yml 
# - import_tasks: K8s_Add_Provisioners_LVM_sanlock
...

# watch kubectl get pods -A -o wide
# watch kubectl get nodes -A
# kubectl exec -it <pod-name> -n <namespace> -- sh
# https://github.com/astefanutti/kubebox
# https://k8slens.dev/download