---

- name: Чтение статуса 'Redis'
  shell: kubectl get pods -n staff | grep 'redis' | grep 'Running'
  register: status_redis
  become: false
  ignore_errors: yes

- name:
  block:

  - name: Создание пространства имен 'staff'
    kubernetes.core.k8s:
      kubeconfig: '/home/{{ ansible_ssh_user }}/.kube/config'
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: staff
          labels:
            pod-security.kubernetes.io/enforce: privileged
      state: present

  - name: Добавление репозитория 'redis-operator' для Helm
    kubernetes.core.helm_repository:
      name: redis-operator
      repo_url: https://spotahome.github.io/redis-operator
      force_update: true
    become: false

  - name: Развертывание 'redis-operator v3.2.7'
    kubernetes.core.helm:
      name: redis-operator
      release_namespace: staff
      chart_ref: redis-operator/redis-operator
      chart_version: 3.2.7
      values: "{{ lookup('file', 'helm_charts/redis_operator.yaml') | from_yaml }}"
      force: true
    become: false

  when: status_redis.stdout == ''

...