---

- name: Проверка наличия интерфейса 'bond0'
  shell: nmcli con | grep bond0
  register: bond0_status
  ignore_errors: yes

- name: Создание 'bond0' если его нет
  block:

  - name: Получить список сетевых интерфейсов
    shell: "nmcli dev status | grep ethernet | awk '{print $1}'"
    register: device_list

  - name: Создание массива сетевых интерфейсов
    set_fact:
      interfaces: "{{ device_list.stdout_lines | list }}"

  - name: Получение количества элементов в списке интерфейсов
    set_fact:
      list_length: "{{ interfaces | length }}"

  - name: Создание 'bond0' если количество интерфейсов отлично от одного
    block:

    - name: Получить список имен сетевых интерфейсов
      shell: |
        nmcli con show | grep ethernet | awk '{print substr($0, 1, match($0, "  ") - 1)}'
      register: name_list

    - name: Создание массива имен сетевых интерфейсов
      set_fact:
        names: "{{ name_list.stdout_lines | list }}"

    - name: Получить список имен сетевых интерфейсов
      shell: |
        nmcli connection delete "bond0"
        nmcli connection add type bond con-name "bond0" ifname bond0
        nmcli connection modify "bond0" bond.options "mode=active-backup"
        nmcli connection modify "bond0" ipv4.addresses '10.10.20.111/24'
        nmcli connection modify "bond0" ipv4.method manual
        nmcli connection modify "bond0" ipv4.gateway '10.10.20.1'
        nmcli connection modify "bond0" ipv4.dns "8.8.8.8 8.8.4.4"
        nmcli connection modify "bond0" ipv4.dns-search "rrr.ru"
        nmcli connection modify "bond0" ipv6.method  disabled

    - name: Добавление интерфейсов в 'bond0'
      shell: 'nmcli connection add type ethernet slave-type bond con-name bond0-if-{{ item }} ifname {{ item }} master bond0'
      with_items: '{{ interfaces }}'

    - name: Включаем 'bond0'
      shell: 'nmcli connection up "bond0"'

    - name: Перезагрузка ОС
      reboot:
        msg: 'Reboot'

    - name: Удаление интерфейсов
      shell: 'nmcli connection delete "{{ item }}"'
      with_items: '{{ names }}'

    when: list_length != '1'

  when: bond0_status.stdout == ''

...