---
# tasks file for init_ceph_astra
# для этого плэйбука необходим пользователь ceph-adm включёный в группу sudo
# и настроен резолвинг нод по имени
- name: Install ceph mon osd
  shell: |
     ceph-deploy --username ceph-adm install --mon --osd ceph01 ceph02 ceph03

#reboot

- name: Install ceph mgr
  shell: |
     ceph-deploy --username ceph-adm install --mgr ceph01 ceph02 ceph03

- name: Create ceph cluster
  shell: |
     ceph-deploy --username ceph-adm new ceph01 ceph02 ceph03

- name: Initial mon
  shell: |
     ceph-deploy --overwrite-conf --username ceph-adm mon create-initial 

- name: Create mgr
  shell: |
     ceph-deploy --overwrite-conf --username ceph-adm mgr create ceph01 ceph02 ceph03

- name: Create osd
  shell: |
     ceph-deploy --overwrite-conf --username ceph-adm osd create --data {{ ceph_disk }} ceph01
     ceph-deploy --overwrite-conf --username ceph-adm osd create --data {{ ceph_disk }} ceph02
     ceph-deploy --overwrite-conf --username ceph-adm osd create --data {{ ceph_disk }} ceph03

- name: Install mds
  shell: |
     ceph-deploy --username ceph-adm install --mds ceph01 ceph02 ceph03

- name: "copy ceph.client.admin.keyring"
  shell: |
     cp ceph.client.admin.keyring /etc/ceph/
     chown root:root /etc/ceph/ -R
     chmod 0644 /etc/ceph/ -R
  become: true
  become_method: sudo

- name: Create mds
  shell: |
     ceph-deploy --overwrite-conf --username ceph-adm mds create ceph01 ceph02 ceph03

- name: insecure allow
  shell: |
     ceph config set mon auth_allow_insecure_global_id_reclaim false
  become: true
  become_method: sudo

- name: create poll kubebernetes
  shell: |
     ceph osd pool create kubernetes 64
  become: true
  become_method: sudo

- name: create cephfs
  shell: |     
     ceph osd pool create k8sfs_data 64
     ceph osd pool create k8sfs_metadata 64
     ceph fs new k8sfs k8sfs_metadata k8sfs_data
  become: true
  become_method: sudo
     
- name: add client kube
  shell: |     
     ceph auth add client.kubernetes mon 'allow r' osd 'allow rwx pool=kubernetes,allow rwx pool=k8sfs_data' mds 'allow rw'
  become: true
  become_method: sudo

- name: init pool
  shell: |     
     rbd pool init kubernetes
  become: true
  become_method: sudo