---

- name: Создание пространства имен для 'NFS provisioner'
  k8s:
    kubeconfig: "~/.kube/config"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ nfs_provisioner_namespace }}"
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present

- name: Создание NFS provisioner PVC
  k8s:
    state: present
    force: no
    kubeconfig: "~/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/nfs_pvc.yaml') }}"

#- name: Create NFS provisioner PSP
#  k8s:
#    state: present
#    force: no
#    kubeconfig: "~/.kube/config"
#    definition: "{{ lookup('template', '{{ role_path }}/files/nfs_psp.yaml') }}"

- name: Создание NFS provisioner RBAC
  k8s:
    state: present
    force: no
    kubeconfig: "~/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/nfs_rbac.yaml') }}"

- name: Создание NFS provisioner deployment
  k8s:
    state: present
    force: no
    kubeconfig: "~/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/nfs_deployment.yaml') }}"

- name: Создание NFS provisioner StorageClass
  k8s:
    state: present
    force: no
    kubeconfig: "~/.kube/config"
    definition: "{{ lookup('template', '{{ role_path }}/files/nfs_storageclass.yaml') }}"

...