---

- name: Чтение статуса ARMABI
  shell: cat /etc/postgresql/9.6/main/pg_hba.conf | grep ArmAbi
  register: current_status
  ignore_errors: yes

- name: Установка сервера ARMABI
  block:

  - name: Установка пакетов необходимых для инсталяции сервера 'АБИ'
    apt:
      name:
      - freeipa-admintools
      - astra-digsig-oldkeys
      - postgresql-astra
      - postgresql-se-test-9.6
      - pgadmin3
      state: latest
      update_cache: yes

  - name: Создание скрипта '/tmp/adduserdbarmabi.sh' создающего пользователея '{{ armabi.user }}' в домене FreeIPA администратора БД
    template:
      src: adduserdbarmabi.j2
      dest: /tmp/adduserdbarmabi.sh
      mode: 0777
      owner: root
    delegate_to: '{{ freeipa.srv }}'

  - name: Обнулить значения уровней и категорий
    shell: |
      useradd -M -N {{ armabi.user }}
      usermac -z {{ armabi.user }}
    ignore_errors: yes
    
  - name: Добавим пользователя '{{ armabi.user }}' в домен FreeIPA администратора БД
    become: true
    become_method: su
    become_user: admin
    command: '/tmp/adduserdbarmabi.sh'
    vars:
      ansible_become_pass: '{{ freeipa.pass }}'
    ignore_errors: yes  
    delegate_to: '{{ freeipa.srv }}'

  - name: Задаем пароль локальному пользователю '{{ armabi.user }}'
    vars:
      mypassword: '{{ armabi.pass }}'
    user:
      name: '{{ armabi.user }}'
      state: present
      password: "{{ mypassword | password_hash('sha512') }}"

  - name: Копирование файлов для инсталяции сервера 'АБИ'
    copy:
      src: ../../../../software/arm_abi/PsArmAbi/supply/armabi.scheme
      dest: /tmp/armabi.scheme
      force: yes

  - name: Внесение изменений в конфигурационные файлы
    shell: |
      sed -i '/ArmAbi'/d /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '86 a local     {{ armabi.db }}     {{ armabi.user }}                              pam        # Настройки для ArmAbi' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '87 a host      {{ armabi.db }}     {{ armabi.user }}           127.0.0.1/32       pam        # Настройки для ArmAbi' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '88 a host      {{ armabi.db }}     {{ armabi.user }}           {{ hostvars[armabi.arm[0]].ansible_ssh_host }}/24     pam      # Настройки для ArmAbi' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '89 a host      {{ armabi.db }}     {{ armabi.user }}           {{ hostvars[armabi.arm[1]].ansible_ssh_host }}/24     pam      # Настройки для ArmAbi' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '90 a host      {{ armabi.db }}     {{ armabi.user }}           {{ armabi.ip }}/24     pam      # Настройки для ArmAbi' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i 's/localhost/*/g' /etc/postgresql/9.6/main/postgresql.conf
      sudo -u postgres dropdb {{ armabi.db }}
      sudo -u postgres dropuser {{ armabi.user }}
      sudo -u postgres createuser {{ armabi.user }}
      sudo -u postgres createdb -O {{ armabi.user }} {{ armabi.db }}
      usermod -a -G shadow postgres
      setfacl -d -m u:postgres:r /etc/parsec/macdb
      setfacl -R -m u:postgres:r /etc/parsec/macdb
      setfacl -m u:postgres:rx /etc/parsec/macdb
      setfacl -d -m u:postgres:r /etc/parsec/capdb
      setfacl -R -m u:postgres:r /etc/parsec/capdb
      setfacl -m u:postgres:rx /etc/parsec/capdb
      sed -i 's/$DBADMIN/{{ armabi.user }}/g' /tmp/armabi.scheme
    ignore_errors: yes
    
  - name: Перезапуск службы 'postgresql'
    service:
      name: postgresql
      enabled: yes
      state: restarted

  - name: Создание скрипта '/tmp/armabi/createdbarmabi.sh' создающего базу данных '{{ armabi.db }}'
    template:
      src: createdbarmabi.j2
      dest: /tmp/createdbarmabi.sh
      mode: 0777
      owner: root

  - name: Создание базы данных '{{ armabi.db }}'
    command: /tmp/createdbarmabi.sh

  - name: Создание скрипта '/tmp/adduseradminarmabi.sh' создающего пользователя '{{ armabi.admin.user }}' в домене FreeIPA
    template:
      src: adduseradminarmabi.j2
      dest: /tmp/adduseradminarmabi.sh
      mode: 0777
      owner: root
    delegate_to: '{{ freeipa.srv }}'
  
  - name: Добавим пользователя '{{ armabi.admin.user }}' в домен FreeIPA
    become: true
    become_method: su
    become_user: admin
    command: '/tmp/adduseradminarmabi.sh'
    vars:
      ansible_become_pass: '{{ freeipa.pass }}'
    ignore_errors: yes  
    delegate_to: '{{ freeipa.srv }}'

  - name: Удаление лишних пакетов
    apt:
      autoremove: yes

  - name: Перезагрузим сервер
    reboot:
      msg: 'Reboot'
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 60

  when: current_status.stdout == ''

...