---

- name: Проверка наличия файла /var/ossec/etc/ossec.conf
  stat:
    path: /var/ossec/etc/ossec.conf
  register: ossec_result

# - name: Удаление OSSEC сервера
  # block:

  # - name: Удаление службы 'ossec'
    # shell: '{{ item }}'
    # with_items:
      # - systemctl stop ossec
      # - systemctl disable ossec
      # - sudo apt remove ossec-hids-server
      # - sudo -u postgres dropdb {{ ossec.db }}
      # - sudo -u postgres dropuser {{ ossec.user }}
      # - deluser {{ ossec.user }}
    # ignore_errors: yes

  # - name: Удаление пользователя '{{ ossec.user }}' администратора БД OSSEC в домен FreeIPA
    # become: true
    # become_method: su
    # become_user: admin
    # command: 'ipa user-del {{ ossec.user }}'
    # vars:
      # ansible_become_pass: '{{ freeipa.pass }}'
    # ignore_errors: yes  
    # delegate_to: '{{ freeipa.srv }}'

- name: Установка OSSEC сервера
  block:

  - name: Установка необходимых пакетов
    apt:
      name:
      - freeipa-admintools
      - astra-digsig-oldkeys
      - postgresql-astra
      - postgresql-se-test-9.6
      - pgadmin3
      state: latest
      update_cache: yes

  - name: Копирование 'deb' пакетов
    copy:
      src: '../../../../software/arm_abi/PsArmAbi/supply/{{ item }}'
      dest: /tmp/
      force: yes
    with_items:
    - GEOIP_DA.DEB
    - LIBSSL1_.DEB
    - OSSEC_HI.DEB

  - name: Установка 'deb' пакетов
    apt:
      deb: '/tmp/{{ item }}'
    with_items:
    - GEOIP_DA.DEB
    - LIBSSL1_.DEB
    - OSSEC_HI.DEB  

  - name: Копирование файла 'ossec-hids-server'
    copy:
      src: '../../../../software/arm_abi/PsArmAbi/supply/ossec-hids-server'
      dest: /etc/init.d/
      force: yes
      mode: 0755

  - name: Копирование файла 'ossec.service'
    copy:
      src: '../../../../software/arm_abi/PsArmAbi/supply/ossec.service'
      dest: /lib/systemd/system/
      force: yes
      mode: 0644

  - name: Перезапуск сервисов 'ossec-hids-server'
    shell: |
      update-rc.d
      ossec-hids-server remove
      systemctl daemon-reload
      systemctl enable ossec
      systemctl start ossec

  - name: Добавим пользователя '{{ ansible_ssh_user }}' в группу 'ossec'
    user:
      name: '{{ ansible_ssh_user }}'
      groups: ossec
      append: yes

  - name: Создание дирректорий для хранения лог-файлов
    file:
      path: '{{ item }}'
      state: directory
      mode: 0775
    with_items:
    - /var/ossec/logs
    - /var/ossec/logs/alerts/

  - name: Создание скрипта для исправления прав на папки резервных копий журнала ежедневно
    copy:
      src: ../../../../software/arm_abi/PsArmAbi/supply/ossec-fix
      dest: /etc/cron.daily/
      force: yes
      mode: 0755

  - name: Копируем настройки 'OSSEC'
    copy:
      src: '../../../../software/arm_abi/PsArmAbi/supply/{{ item.src }}'
      dest: '{{ item.dest }}'
      owner: root
      group: ossec
      force: yes
    loop:
    - { src: ossec.conf, dest: /var/ossec/etc/ }
    - { src: decoder.xml, dest: /var/ossec/etc/ }
    - { src: auth.xml, dest: /var/ossec/rules/}
    - { src: sshd_rules.xml, dest: /var/ossec/rules/ }
    - { src: afick.xml, dest: /var/ossec/rules/ }
    - { src: fly-dm.xml, dest: /var/ossec/rules/ }
    - { src: abi_rules.xml, dest: /var/ossec/rules/ }
    - { src: drweb_rules.xml, dest: /var/ossec/rules/ }
    - { src: ossec.schema, dest: /tmp/ }
    - { src: signature.sql, dest: /tmp/ }

  - name: Создаем задание для рестарта 'OSSEC' при перезапуске
    copy:
      src: ../../../../software/arm_abi/PsArmAbi/supply/ossec
      dest: /etc/cron.d/
      owner: root
      group: root
      force: yes
      mode: 0644

  - name: Создаем скрип '/tmp/adduserdbossec.sh' создающий пользователя администратора БД OSSEC '{{ ossec.user }}' в домене FreeIPA
    template:
      src: adduserdbossec.j2
      dest: /tmp/adduserdbossec.sh
      mode: 0777
      owner: root
    delegate_to: '{{ freeipa.srv }}'

  - name: Обнулить значения уровней и категорий
    shell: |
      useradd -M -N {{ ossec.user }}
      usermac -z {{ ossec.user }}
    ignore_errors: yes
    
  - name: Добавление пользователя '{{ ossec.user }}' администратора БД OSSEC в домен FreeIPA
    become: true
    become_method: su
    become_user: admin
    command: /tmp/adduserdbossec.sh
    vars:
      ansible_become_pass: '{{ freeipa.pass }}'
    ignore_errors: yes  
    delegate_to: '{{ freeipa.srv }}'

  - name: Задаем пароль локальному пользователю '{{ ossec.user }}'
    vars:
      mypassword: '{{ ossec.pass }}'
    user:
      name: '{{ ossec.user }}'
      state: present
      password: "{{ mypassword | password_hash('sha512') }}"

  - name: Настройка 'PostgreSQL'
    shell: |
      sed -i '/OSSEC'/d /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '86 a local     all     {{ ossec.user }}                           pam    # Настройки для OSSEC' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '87 a host      all     {{ ossec.user }}        127.0.0.1/32       pam    # Настройки для OSSEC' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '88 a host      all     {{ ossec.user }}        {{ hostvars[ossec.srv].ansible_ssh_host }}/24    pam    # Настройки для OSSEC' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '89 a host      all     {{ ossec.user }}        {{ hostvars[armabi.srv].ansible_ssh_host }}/24    pam    # Настройки для OSSEC' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '90 a host      all     {{ ossec.user }}        {{ armabi.ip }}/24    pam    # Настройки для OSSEC' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i 's/localhost/*/g' /etc/postgresql/9.6/main/postgresql.conf
      sudo -u postgres dropdb {{ ossec.db }}
      sudo -u postgres dropuser {{ ossec.user }}
      sudo -u postgres createuser {{ ossec.user }}
      sudo -u postgres createdb -O {{ ossec.user }} {{ ossec.db }}
      usermod -a -G shadow postgres
      setfacl -d -m u:postgres:r /etc/parsec/macdb
      setfacl -R -m u:postgres:r /etc/parsec/macdb
      setfacl -m u:postgres:rx /etc/parsec/macdb
      setfacl -d -m u:postgres:r /etc/parsec/capdb
      setfacl -R -m u:postgres:r /etc/parsec/capdb
      setfacl -m u:postgres:rx /etc/parsec/capdb
    ignore_errors: yes

  - name: Перезапуск службы 'postgresql'
    service:
      name: postgresql
      enabled: yes
      state: restarted

  - name: Создание скрипта '/tmp/createdbossec.sh' создающего базу данных '{{ ossec.db }}'
    template:
      src: createdbossec.j2
      dest: /tmp/createdbossec.sh
      mode: 0777
      owner: root

  - name: Создание базы данных '{{ ossec.db }}'
    command: /tmp/createdbossec.sh

  - name: Внесение изменений в '/var/ossec/etc/ossec.conf'
    shell: |
      sed -i '3 a <database_output>' /var/ossec/etc/ossec.conf
      sed -i '4 a <hostname>127.0.0.1</hostname>' /var/ossec/etc/ossec.conf
      sed -i '5 a <username>{{ ossec.user }}</username>' /var/ossec/etc/ossec.conf
      sed -i '6 a <password>{{ ossec.pass }}</password>' /var/ossec/etc/ossec.conf
      sed -i '7 a <database>{{ ossec.db }}</database>' /var/ossec/etc/ossec.conf
      sed -i '8 a <type>postgresql</type>' /var/ossec/etc/ossec.conf
      sed -i '9 a </database_output>' /var/ossec/etc/ossec.conf
      sed -i 's/1310001/131001/g' /var/ossec/rules/parsec.xml

  - name: Копируем настройки 'OSSEC'
    copy:
      src: ../../../../software/arm_abi/PsArmAbi/supply/10-ossec-syslog.conf
      dest: /etc/rsyslog.d/
      force: yes

  - name: Перезагрузим службы
    shell: |
      /var/ossec/bin/ossec-control enable database
      /etc/init.d/rsyslog restart
      /var/ossec/bin/ossec-control restart
      /etc/init.d/rsyslog restart
      systemctl daemon-reload
      systemctl enable ossec
      systemctl restart ossec
      /var/ossec/bin/ossec-control restart

  - name: Удаление лишних пакетов
    apt:
      autoremove: yes

  - name: Перезагрузим сервер
    reboot:
      msg: 'Reboot'
      connect_timeout: 5
      reboot_timeout: 600
      pre_reboot_delay: 0
      post_reboot_delay: 60

  when:
  - not ossec_result.stat.exists

...