---
- name: Очистка конфигурации
  tags:
  - clear
  - never
  block:

  - name: Удаление пакетов для PXE и DHCP серверов
    apt:
      autoremove: yes
      purge: true
      state: absent
      name:
      - isc-dhcp-server
      - fly-admin-dhcp
      - pxelinux
      - syslinux
      - tftpd-hpa

  - name: Удаление файлов конфигураций
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - /etc/dhcp/dhcpd.conf
    - /etc/default/isc-dhcp-server
    - /srv/tftp

  when: inventory_hostname == pxe.srv

- name: Создания PXE сервера
  block:

  - name: Проверка наличия файла /etc/dhcp/dhcpd.conf
    stat:
      path: /etc/dhcp/dhcpd.conf
    register: dhcpd_result

  - name: Создания сервера DHCP
    block:

    - name: Установка пакетов для DHCP сервера
      apt:
        update_cache: yes
        name:
        - isc-dhcp-server
        - fly-admin-dhcp
        state: latest

    - name: Внесение изменений в файл '/etc/default/isc-dhcp-server'
      lineinfile:
        dest: /etc/default/isc-dhcp-server
        regexp: INTERFACESv4=""
        line: INTERFACESv4="bond0"
      when: interfaces.split(',')|length != 1

    - name: Внесение изменений в файл '/etc/default/isc-dhcp-server'
      lineinfile:
        dest: /etc/default/isc-dhcp-server
        regexp: INTERFACESv4=""
        line: INTERFACESv4="{{ interfaces }}"
      when: interfaces.split(',')|length == 1

    - name: Конфигурирование dhcp-server
      template:
        src: dhcpd.j2
        dest: /etc/dhcp/dhcpd.conf
        mode: 0644
        owner: root
        force: yes

    - name: Перезагрузка dhcp
      service:
        name: isc-dhcp-server
        state: restarted
        enabled: yes

    when: not dhcpd_result.stat.exists

  - name: Проверка наличия файла '/srv/tftp/linux'
    stat:
      path: /srv/tftp/linux
    register: linux_result

  - name: Создания сервера PXE
    block:

    - name: Установка пакетов для PXE сервера
      apt:
        name:
        - pxelinux
        - syslinux
        - tftpd-hpa
        state: latest
        update_cache: yes

    - name: Копирование файлов загрузчиков Legacy
      shell: |
        cp /srv/repo/mo/netinst/linux /srv/tftp/
        cp /srv/repo/mo/netinst/initrd.gz /srv/tftp/
        cp /usr/lib/PXELINUX/pxelinux.0 /srv/tftp/
        cp /usr/lib/syslinux/modules/bios/{chain.c32,ldlinux.c32,libcom32.c32,libutil.c32,menu.c32} /srv/tftp/

    - name: Копирование файлов загрузчиков UEFI
      unarchive:
        src: netinst.tar.gz
        dest: /srv/tftp
        mode: '0777'

    - name: Создание папки '/srv/tftp/pxelinux.cfg' для меню загрузчика Legacy
      file:
        state: directory
        path: /srv/tftp/pxelinux.cfg

    - name: copy default с меню загрузчика Legacy
      copy:
        src: default.j2
        dest: /srv/tftp/pxelinux.cfg/default

    - name: Создание папки '/srv/tftp/preseeds' с конфигурациями серверов
      file:
        state: directory
        path: /srv/tftp/preseeds

    - name: Создание файлов 'hosts.preseed' с конфигурациями серверов
      template:
        src: preseed_srv.j2
        dest: '/srv/tftp/preseeds/{{ item }}.preseed'
        mode: 0444
      loop: "{{ query('inventory_hostnames', 'srv') }}"

    - name: Создание файлов 'hosts.preseed' с конфигурациями АРМов
      template:
        src: preseed_arm.j2
        dest: '/srv/tftp/preseeds/{{ item }}.preseed'
        mode: 0444
      loop: "{{ query('inventory_hostnames', 'arm') }}"

    - name: Модификация файлов 'hosts.preseed'
      shell: |
        VAR_IP={{ hostvars[item].ansible_ssh_host }}
        VAR_SED=s/127.127.127.127/$VAR_IP/g
        sed -i "$VAR_SED" /srv/tftp/preseeds/{{ item }}.preseed
      loop: "{{ query('inventory_hostnames', 'all') }}"

    - name: Создание меню PXE загрузчика Legacy
      blockinfile:
        path: /srv/tftp/pxelinux.cfg/default
        state: present
        block: |
          # Установка Astra Linux SE Смоленск на хост {{ item }}.{{ domain }} ###
          LABEL netinstall
             MENU LABEL Install ALSE 1.6 Smolensk '{{ item }}.{{ domain }}'
             kernel linux
             append initrd=initrd.gz modprobe.blacklist=evbug auto=true priority=critical debian-installer/locale=en_US console-keymaps-at/keymap=ru hostname=alse16 domain={{ domain }} astra-license/license=true url=tftp://{{ hostvars[pxe.srv].ansible_ssh_host }}/preseeds/{{ item }}.preseed interface=auto netcfg/dhcp_timeout=60 astra_install=1 vga=788 debian-installer/allow_unauthenticated=true nomodeset
        marker: "###"
      loop: "{{ query('inventory_hostnames', 'all') }}"

    - name: Создание меню PXE загрузчика UEFI
      blockinfile:
        path: /srv/tftp/debian-installer/amd64/grub/grub.cfg
        state: present
        block: |
          ### Установка Astra Linux SE Смоленск на хост {{ item }}.{{ domain }} ###
          menuentry 'Install ALSE 1.6 Smolensk {{ item }}.{{ domain }}' {
            set background_color=black
            linux linux modprobe.blacklist=evbug debian-installer/allow_unauthenticated=true auto=true priority=critical debian-installer/locale=en_US console-keymaps-at/keymap=ru hostname=alse16 domain={{ domain }} astra-license/license=true url=tftp://{{ hostvars[pxe.srv].ansible_ssh_host }}/preseeds/{{ item }}.preseed interface=auto netcfg/dhcp_timeout=60
            initrd initrd.gz
          }
        marker: "###"
      loop: "{{ query('inventory_hostnames', 'all') }}"

    - name: Перезапуск служб
      service:
        name: tftpd-hpa
        state: restarted
        enabled: yes

    when: not linux_result.stat.exists

  when: inventory_hostname == pxe.srv

...