apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-templates
  namespace: logging
data:
  execution-script.sh: |
    curl -XPUT "http://elasticsearch:9200/_index_template/ceph" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/ceph-index-patterns.json
    curl -XPUT "http://elasticsearch:9200/_index_template/staff" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/staff-index-patterns.json
    curl -XPUT "http://elasticsearch:9200/_index_template/kube-system" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/kube-system-index-patterns.json
    curl -XPUT "http://elasticsearch:9200/_index_template/logging" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/logging-index-patterns.json
    curl -XPUT "http://elasticsearch:9200/_index_template/monitoring" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/monitoring-index-patterns.json
    curl -XPUT "http://elasticsearch:9200/_ilm/policy/default-10d" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/default-10d-ilm-policy.json
    curl -XPUT "http://elasticsearch:9200/_index_template/emercore" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/emercore-index-patterns.json
    curl -XPUT "http://elasticsearch:9200/_ilm/policy/emercore-3d" -H 'Content-Type: application/json' -d @/etc/elasticsearch-templates/emercore-14d-ilm-policy.json
  emercore-index-patterns.json: |
    {
      "index_patterns": ["emercore-*"],
      "priority": 150,
      "data_stream": {},
      "template": {
        "settings": {
          "index.lifecycle.name": "emercore-14d" 
        }
      }
    }
  staff-index-patterns.json: |
    {
      "index_patterns": ["staff-*"],
      "priority": 110,
      "data_stream": {},
      "template": {
        "settings": {
          "index.lifecycle.name": "default-10d" 
        }
      }
    }
  ceph-index-patterns.json: |
    {
      "index_patterns": ["ceph-*"],
      "priority": 110,
      "data_stream": {},
      "template": {
        "settings": {
          "index.lifecycle.name": "default-10d" 
        }
      }
    }
  kube-system-index-patterns.json: |
    {
      "index_patterns": ["kube-system-*"],
      "priority": 1100,
      "data_stream": {},
      "template": {
        "settings": {
          "index.lifecycle.name": "default-10d" 
        }
      }
    }
  logging-index-patterns.json: |
    {
      "index_patterns": ["logging-*"],
      "priority": 110,
      "data_stream": {},
      "template": {
        "settings": {
          "index.lifecycle.name": "default-10d" 
        }
      }
    }
  monitoring-index-patterns.json: |
    {
      "index_patterns": ["monitoring-*"],
      "priority": 110,
      "data_stream": {},
      "template": {
        "settings": {
          "index.lifecycle.name": "default-10d" 
        }
      }
    }
  emercore-14d-ilm-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_primary_shard_size": "15gb",
                "max_age": "14d"
              }
            }
          },
          "delete": {
            "min_age": "1d",
            "actions": {
              "delete": {
                "delete_searchable_snapshot": true
              }
            }
          }
        }
      }
    }
  default-10d-ilm-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "rollover": {
                "max_primary_shard_size": "5gb",
                "max_age": "10d"
              }
            }
          },
          "delete": {
            "min_age": "1d",
            "actions": {
              "delete": {
                "delete_searchable_snapshot": true
              }
            }
          }
        }
      }
    }

