fullnameOverride: "elasticsearch"
clusterDomain: {{ domain }}

master:
  replicaCount: "{% if k8s.workers | default([]) | length > 1 %}2{% else %}1{% endif %}"
  extraVolumes:
    - name: elasticsearch-templates
      configMap:
        name: elasticsearch-templates
  extraVolumeMounts:
    - name: elasticsearch-templates
      mountPath: /etc/elasticsearch-templates
      readOnly: true
  persistence:
    storageClass: {{ k8s.rwo_sc }}
    size: 1Gi

data:
  replicaCount: "{% if k8s.workers | default([]) | length > 1 %}2{% else %}1{% endif %}"
  persistence:
    storageClass: {{ k8s.rwo_sc }}
    size: 100Gi

coordinating:
  replicaCount: "{% if k8s.workers | default([]) | length > 1 %}2{% else %}1{% endif %}"
  
ingest:
  enabled: false

metrics:
  enabled: true
  extraArgs:
    - --es.cluster_settings
    - --es.indices
    - --es.indices_settings
    - --es.indices_mappings
    - --es.aliases
    - --es.shards
    - --es.data_stream
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
  prometheusRule:
    enabled: true