global:
  # imageRegistry: "dockerreg.sphaera.ru"
  # imagePullSecrets:
  # - dockerreg-sphaera-ru
  storageClass: {{ k8s.rwo_sc }}
fullnameOverride: "rabbitmq-operator"
clusterDomain: {{ domain }}
clusterOperator:
  metrics:
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
