---

- name: install all
  hosts: all
  become: yes
  vars_files:
  - vars/dsp.yml
#  - vars/sgk.yml
  - vars/passwords.yml
  #strategy: free
  roles:
# 0. Первичная настройка хостов
  - 0.0-GetVersion
  - 0.1-HostName
  - 0.2-Repo
  - 0.3-Update
  - 0.4-Networks
  - 0.5-Time
    #- 0.6-MultiPath
    #- 0.7-NVidia ( не сделано )
#    - 0.8-SSH_Key
# 1. Установка первичных серверов и служб
  #- 1.1-PXE
    # - 1.2-RDP
# 2. Установка контроллера домена и подключение клиентов
    #- 2.2-FreeIPA
# 3. Установка серверов и служб
    #- 3.1-Bakula ( не сделано )
    #- 3.2-Zabbix
    #- 3.3-Clusters
    #- 3.4-Cups ( не сделано )
    #- 3.5-Backup
    #- 3.10-CephFS
    #- 3.11-Docker ( не сделано )
  - 3.12-K8s
# 4. Настройка безопасности хостов
# 5. Установка ОПО
    #- 5.3-Termidesk
# 6. Установка серверной части СПО
# 7. Резерв
# 8. Настройка безопасности
# 9. Сервисные плейбуки
    #- 9.1-GostSum
    #- 9.9-ShutDown
    #- 9.9-ShutDown

#### Не сделано #######################################
    #- 0.3-NetworkManager (  )
    #- 0.6-iSCSI ( не сделано )
    #- 4.1-drweb ( не сделано )
    #- 4.2-ksl ( не сделано )
    #- 5.1-armabi ( не сделано )
    #- 5.2-kpsgp ( не сделано )
    #- 8.1-szi ( не сделано )

    #- 9.8-logclear ( не сделано )

...