---

- name: Чтение статуса часового пояса
  shell: cat /etc/timezone
  register: timezone_status

- name: Установка часового пояса '{{ ntp.timezone }}'
  timezone:
    name: '{{ ntp.timezone }}'
  when: timezone_status.stdout != ntp.timezone

- name: Чтение статуса конфигурирования 'Chrony'
  shell: cat /etc/chrony/chrony.conf | grep 'Ansible'
  register: chrony_status
  ignore_errors: yes

- name: Настройка 'Chrony'
  block:

  - name: Удаление пакета 'ntp'
    apt:
      name:
      - ntp
      - ntpdate
      autoremove: yes
      purge: true

  - name: Установка пакета 'chrony'
    apt:
      name: chrony
      state: latest

  - name: Создание файла '/etc/chrony/chrony.conf'
    template:
      src: chrony.j2
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
    when: inventory_hostname == ntp.srv


  - name: Создание файла '/etc/chrony/chrony.conf'
    template:
      src: chrony2.j2
      dest: /etc/chrony/chrony.conf
      owner: root
      group: root
      mode: 0644
    when: inventory_hostname != ntp.srv

  - name: Перезапуск службы 'chrony'
    service:
      name: chrony
      enabled: yes
      state: restarted

  when: chrony_status.stdout == ''

...