---

- name: Чтение DNS серверов в файле '/etc/NetworkManager/conf.d/dns.conf'
  shell: cat /etc/NetworkManager/conf.d/dns.conf | grep '{{ Net.bind | join(',') }}'
  register: dns_status
  ignore_errors: yes

- name: Настройка 'dns.conf'
  block:

  - name: Останавливаем  службу 'firewalld' 
    service:
      name: firewalld
      state: stopped
      enabled: false
    ignore_errors: yes

  - name: Создаем конфигурацию '/etc/NetworkManager/conf.d/dns.conf'
    shell: |
      echo -e "[global-dns-domain-*]\nservers = {{ Net.bind | join(',') }}\n" > /etc/NetworkManager/conf.d/dns.conf
      rm -f /etc/resolv.conf

  - name: Перезапуск службы 'NetworkManager'
    service:
      name: NetworkManager
      state: restarted

  when:
    - dns_status.stdout == ''

- name: Создание первого интерфейса если ..............................
  block:

  - name: Получить имя активного интерфейса
    shell: |
      ip -o -4 addr show | grep "{{ hostvars[inventory_hostname].ansible_ssh_host }}" | awk '{print $2}'  
    register: device_name

  - name: Настройка сетевого интерфейса '{{ device_name.stdout }}'
    nmcli:
      type: ethernet
      conn_name: '{{ device_name.stdout }}'
      ip4: '{{ hostvars[inventory_hostname].ansible_ssh_host }}/{{ Net.network.split("/")[1] }}'
      gw4: '{{ Net.gateway }}'
      dns4 : '{{ Net.bind | join(",") }}'
      dns4_search: '{{ domain }}'
      state: present

  - name: Настройка сетевого интерфейса '{{ device_name.stdout }}'
    shell: |
      nmcli connection modify "{{ device_name.stdout }}" ipv6.method  disabled

  - name: Перезапуск службы 'NetworkManager'
    service:
      name: NetworkManager
      state: restarted

  # when: ...............................

...