apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: ceph-csi
  pass_credentials_all: false
  password: ""
  url: https://ceph.github.io/csi-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: postgres-operator-charts
  pass_credentials_all: false
  password: ""
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: bitnami
  pass_credentials_all: false
  password: ""
  url: https://charts.bitnami.com/bitnami
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: redis-operator
  pass_credentials_all: false
  password: ""
  url: https://spotahome.github.io/redis-operator
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: prometheus-community
  pass_credentials_all: false
  password: ""
  url: https://prometheus-community.github.io/helm-charts
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: elastic
  pass_credentials_all: false
  password: ""
  url: https://helm.elastic.co
  username: ""
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: fluent
  pass_credentials_all: false
  password: ""
  url: https://fluent.github.io/helm-charts
  username: ""
