---

- name: Обновление репозиториев AltLinux
  shell: apt-get update

- name: Обновление AltLinux
  shell: apt-get dist-upgrade -y

- name: Обновление ядра AltLinux
  shell: update-kernel -t un-def -y

- name: Перезагрузка ОС
  reboot:
    msg: "Reboot"
  when: ansible_distribution_version != '10.4'

...