# Системный администратор
local_admin: admin1
password_local_admin: P@ssw0rd


# если есть выделенные воркеры, то включаем
worker_nodes: false
# включить для создания бонда для iscsi
iscsi_bond: false
# включить для создания bond0
net_bond: false
# задаём какой рантайм нужно использовать (роль написано только для crio) 
# runtime: crio, docker, conteinerd
runtime: 'crio'
# flannel, calico or calico_bgp
cni: 'calico_bgp'

### Перезагрузка системы
reboot_system: 1
# 1 - перезагрузить систему (система требует пезагрузки после первичной настройки).
# 0 - отключить перезагрузку

# переменная для тесовых сред состоящих из одной ноды 
single_node: true

### Net
# это звготовка для автомаьтческого создания ВМ
net_master_name_pefix: master0
# net_worker_name_pefix: worker0

# net_dns_server: '10.150.0.1'
net_dns_server_forward: '10.1.11.1'
# net_repo_server: "repo01"
# net_repo_server_ip: '10.163.17.108'
net_local_domain: 'demo01.ec.lan'

# address
net_address_master01: '10.1.11.200'

### Kubernetes
kubernetes_version: "1.28"
kubernetesVersion: "1.28.8"
kubernetes_version_full: "1.28.8-00"
kubernetes_version_cri_tools: "1.28.8-00"
kubernetes_rwo_sc: csi-lvm
kubernetes_rwx_sc: "csi-nfs"
kubernetes_pod_subnet: "10.230.0.0/22"
kubernetes_service_subnet: "10.232.0.0/24"
kubernetes_coredns_svc: "10.232.0.10"
kubernetes_registry: "registry.altlinux.org/k8s-p10"

# monitoring storage size
storage_size_prometheus: "15G"

# logging

# NFS Provisioner
nfs_provisioner_namespace: "csi-nfs"
nfs_provisioner_disk_size: "50Gi"
# nfs_provisioner_portal_ip: "10.150.0.200:3260"
# nfs_provisioner_iqn_target: "iqn.2023-09.com.hac:alt.target01"
# nfs_provisioner_iqn_lun: "2"

# LVM Provisioner
lvm_provisioner_namespace: "csi-lvm-system"
# lvm_provisioner_disk: "/dev/disk/by-id/scsi-33000000100000001"
lvm_provisioner_vg_name: "vg01"
lvm_provisioner_device_pattern: "/dev/sdb"

# Ingress
ingress_nodes:
  - master01
