---

- name: Запускаем на Backup сервере
  block:

  - name: Проверка наличия установленного NFS сервер
    shell: cat /etc/exports | grep '{{ backup.path }}'
    register: conf_status
    ignore_errors: yes
    register: nfs_result

  - name: Настройка NFS сервера
    block:

    - name: Инсталляция необходимых пакетов для сервера
      apt:
        update_cache: yes
        name:
        - nfs-kernel-server
        state: latest

    - name: Остановка служб
      service:
        name: '{{item}}'
        state:  stopped
      with_items:
      - nfs-server
      ignore_errors: yes

    - name: Создадим папки '{{ backup.path }}' для хранения бекапа 
      file:
        state: directory
        mode: 0777
        recurse: yes
        path: '{{ backup.path }}/log'

    - name: Создание папок для серверов
      file:
        state: directory
        mode: 0777
        recurse: yes
        path: '{{ backup.path }}/{{ item }}'
      loop: "{{ query('inventory_hostnames', 'srv') }}"

    - name: Внесение дополнений в файл '/etc/exports'
      lineinfile:
        path: /etc/exports
        line: '{{ backup.path }} *(rw,insecure,no_subtree_check,all_squash,anonuid=1000,anongid=1000)'

    - name: Создание политики лог-файла бекапа
      template:
        src: backup_logrotate.j2
        dest: /etc/logrotate.d/backup_logrotate
        owner: root
        group: root
        mode: 0644

    - name: Перезапуск служб
      service:
        name: '{{ item }}'
        enabled: yes
        state: restarted
      with_items:
      - nfs-server
      - cron

    when: nfs_result.stdout.split('.')[0] == ''

  when: inventory_hostname == backup.srv

...