---

- name: Чтение статуса часового пояса
  shell: cat /etc/timezone
  register: timezone_status

- name: Установка часового пояса '{{ ntp.timezone }}'
  timezone:
    name: '{{ ntp.timezone }}'
  when: timezone_status.stdout != ntp.timezone

- name: Настройка NTP сервера
  block:

  - name: Чтение статуса конфигурирования NTP сервера
    shell: cat /etc/ntp.conf | grep '{{ ntp.ntp_out }}'
    register: ntp_server_status
    ignore_errors: yes

  - name: Настройка NTP сервера
    block:

    - name: Создание файла '/etc/ntp.conf'
      template:
        src: ntp_s.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644

    - name: Перезапуск службы NTP
      service:
        name: ntp
        enabled: yes
        state: restarted

    - name: Синхронизация апаратного времени с системным
      shell: |
        hwclock --systohc
        timedatectl set-local-rtc true

    when: ntp_server_status.stdout == ''

  - name: Синхронизация времени
    shell: |
      ntpdate {{ ntp.ntp_out }}
      hwclock --systohc --utc
      timedatectl set-local-rtc true

  when: inventory_hostname == ntp.srv

- name: Настройка NTP клиента
  block:

  - name: Чтение статуса конфигурирования NTP клиента
    shell: cat /etc/ntp.conf | grep '{{ ntp.ntp_int }}'
    register: ntp_client_status
    ignore_errors: yes

  - name: Настройка NTP клиента
    block:

    - name: Создание файла '/etc/ntp.conf'
      template:
        src: ntp_c.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644

    - name: Перезапуск службы NTP
      service:
        name: ntp
        enabled: yes
        state: restarted

    when: ntp_client_status.stdout == ''

  - name: Синхронизация времени
    shell: |
      ntpdate {{ ntp.ntp_int }}
      hwclock --systohc --utc
      timedatectl set-local-rtc true

  when: inventory_hostname != ntp.srv

...