---
- name: create folder
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
  with_items: 
  - "{{ strom_fld }}"

- name: copy scan etc
  copy:
    src: etc/init.d/scansendservice
    dest: /etc/init.d/
    mode: '0766'

- name: copy scan bin
  copy:
    src: usr/bin/ScanSendService
    dest: /usr/bin/
    mode: '0766'

- name: template scansend_cfg
  template:
    src: scansend_cfg
    dest: /etc/scansend_cfg
    mode: '0644'

- name: template scan_folder
  template:
    src: scan_folder
    dest: /etc/zftp/scan_folder.lst
    mode: '0644'

- name: autostart scansendservice
  shell: update-rc.d scansendservice defaults

- name: start service scan
  service:
    name: scansendservice
    state: restarted
