---
- name: Чтение версии установленного ПО
  shell: cat /opt/distr/software.conf | grep Digsig
  register: version
  ignore_errors: yes

- name: Добавление открытого ключа
  copy:
    src: "{{ item }}"
    dest: /etc/digsig/keys/
    mode: '0444'
  with_items:
  - mniti_pub.key
  ignore_errors: yes
  when: version.stdout != relis

- name: Добавление ключа для подписи
  copy:
    src: "{{ item }}"
    dest: /opt/distr/Digsig/
    mode: '0444'
  with_items:
  - mniti_secret.gpg
  when: version.stdout != relis

- name: Импорт ключа
  shell: "gpg --import --pinentry-mode=loopback --passphrase={{ mniti_pass_gpg }} /opt/distr/Digsig/mniti_secret.gpg"
  ignore_errors: yes
  when: version.stdout != relis

- name: Поиск неподписаных приложений
  shell: "{{ item }}"
  with_items:
   - rm /opt/distr/Digsig/bsign.sh
   - cat /var/log/messages | grep "DIGSIG" | grep "NOT SIGNED" |sed 's|.*path=|###|' | sed -r 's/ .+//' | sort | uniq >> /opt/distr/Digsig/bsign.sh
   - cat /var/log/messages | grep "DIGSIG" | grep "VERIFICATION" |sed 's|.*path=|###|' | sed -r 's/ .+//' | sort | uniq >> /opt/distr/Digsig/bsign.sh
   - sed -i '/###|###|/d' /opt/distr/Digsig/bsign.sh
   - sed -i 's/###/{{ bsign }} /g' /opt/distr/Digsig/bsign.sh
   - chmod 777 /opt/distr/Digsig/bsign.sh
  ignore_errors: yes
#  when: version.stdout != relis

- name: Подписание файлов прочтенных из messages
  shell: cd /opt/distr/Digsig && ./bsign.sh
  ignore_errors: yes
#  when: version.stdout != relis

- name: Удаление messages
  file:
    path: /var/log/messages
    state: absent
#  when: version.stdout != relis

- name: Перезагрузка syslog
  service:
    name: syslog
    state: restarted
#  when: version.stdout != relis

- name: Подписание набора файлов
  shell: '{{ bsign }} {{ bsign_files }}'
  ignore_errors: yes
  when: version.stdout != relis

- name: Подписание набора библиотeк
  shell: '{{ bsign }} -i {{ bsign_paths }}'
  ignore_errors: yes
  when: version.stdout != relis

- name: Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i '/Digsig/d' /opt/distr/software.conf && echo '{{ relis }}' >> /opt/distr/software.conf"
  when: version.stdout != relis
  ignore_errors: yes
