---

- name: Проверка наличия файла '/home/{{ ansible_ssh_user }}/.kube/config'
  stat:
    path: /home/{{ ansible_ssh_user }}/.kube/config
  register: result
  ignore_errors: true

- name: Создание кластера 'Kubernetes'
  block:

  - name: Инициализируем кластер 'Kubernetes'
    shell: |
      kubeadm config images pull
      kubeadm init \
      --upload-certs \
      --pod-network-cidr={{ k8s.pod_subnet }} \
      --service-cidr={{ k8s.service_subnet }} \
      --service-dns-domain={{ domain }} \
      --cri-socket=unix:///var/run/crio/crio.sock \
      --control-plane-endpoint={{ k8s.keepalived_IP }}:{{ k8s.haproxy_port}} \
      --apiserver-advertise-address={{ hostvars[k8s.masters[0]].ansible_ssh_host }} \
      --apiserver-bind-port=6443 \
      --node-name={{ inventory_hostname }}.{{ domain }} \
      --image-repository=registry.k8s.io

  - name: Создаем директорию '/home/{{ ansible_ssh_user }}/.kube'
    file:
      path: '/home/{{ ansible_ssh_user }}/.kube'
      state: directory
      mode: 0755

  - name: Копируем конфигурацию кластера в домашний каталог администратора '{{ ansible_ssh_user }}'
    copy:
      src: '/etc/kubernetes/admin.conf'
      dest: '/home/{{ ansible_ssh_user }}/.kube/config'
      remote_src: true

  when: not result.stat.exists

...
