---

- name: Проверка наличия 'Ceph'
  stat:
    path: /usr/bin/ceph
  register: ceph_result
  ignore_errors: yes

- name: Установка 'Ceph'
  block:

  - name: Установка вспомогательных пакетов
    dnf:
      update_cache: true
      name:
      - python3
      - python3-pip
      - python3-devel 
      - htop
      - iftop
      - net-tools
      - snappy
      - leveldb
      - gdisk
      - python-argparse
      - gperftools-libs

  - name: Установка модулей Python
    pip:
      executable: pip3
      extra_args: --no-warn-script-location
      name:
      - ansible
      - ansible-core

  # - name: Создаем файл '/etc/yum.repos.d/ceph.repo'
    # file:
      # path: /etc/yum.repos.d/ceph.repo
      # mode: 0644
      # state: touch

  # - name: Добавление репозитория 'Ceph v{{ Ceph.ver }}'
    # blockinfile:
      # path: /etc/yum.repos.d/ceph.repo
      # block: |
        # [ceph]
        # name=Ceph packages
        # baseurl=https://download.ceph.com/rpm-{{ Ceph.ver }}/el8/x86_64
        # enabled=1
        # priority=2
        # gpgcheck=1
        # gpgkey=https://download.ceph.com/keys/release.asc
        
        # [ceph-noarch]
        # name=Ceph noarch packages
        # baseurl=https://download.ceph.com/rpm-{{ Ceph.ver }}/el8/noarch
        # enabled=1
        # priority=2
        # gpgcheck=1
        # gpgkey=https://download.ceph.com/keys/release.asc

  - name: Обновление репозиториев
    dnf:
      update_only: true
      update_cache: true

  - name: Инсталляция пакетов 'Сeph'
    dnf:
      name:
      - ceph-deploy
      - ceph-mgr-dashboard

  when: not ceph_result.stat.exists

...