---

- name: Проверка интерфейса '{{ Ceph.net.interface }}'
  shell: |
    cat /etc/NetworkManager/system-connections/{{ Ceph.net.interface }}.nmconnection | grep '{{ Ceph.net.network.split(".")[0] }}.{{ Ceph.net.network.split(".")[1] }}.{{ Ceph.net.network.split(".")[2] }}.{{ hostvars[inventory_hostname].ansible_ssh_host.split(".")[3] }}/{{ Ceph.net.network.split("/")[1] }}'
  register: interface_result
  ignore_errors: yes

- name: Создание интерфейса
  block:

  - name: Настройка сетевого интерфейса '{{ Ceph.net.interface}}'
    nmcli:
      type: ethernet
      ifname: '{{ Ceph.net.interface }}'
      conn_name: '{{ Ceph.net.interface }}'
      ip4: '{{ Ceph.net.network.split(".")[0] }}.{{ Ceph.net.network.split(".")[1] }}.{{ Ceph.net.network.split(".")[2] }}.{{ hostvars[inventory_hostname].ansible_ssh_host.split(".")[3] }}/{{ Ceph.net.network.split("/")[1] }}'
      state: present

  - name: Перезапуск службы 'NetworkManager'
    service:
      name: NetworkManager
      state: restarted

  when:
    - interface_result.stdout == ''

...