---
- name: Чтение версии установленного ПО
  shell: cat /etc/software.conf | grep GlusterFS-client
  register: version
  ignore_errors: yes

- name: Установка необходимых пакетов
  apt:
    name:
    - glusterfs-client
    update_cache: yes
  when:
  - inventory_hostname in "{{ groups['gluster_client'] }}"
  - glserex.stat.exists == false

- name: Создание папок для развертывания glusterfs
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - /opt/GlusterFS

- name: Добавление GlusterFS в fstab и их монтирование
  mount:
    src: "10.1.20.2:/GlusterFS"
    path: "/opt/GlusterFS"
    fstype: glusterfs
    opts: rw,auto,x-systemd.automount,x-systemd.mount-timeout=30,_netdev
    state: mounted

- name: Запишем версию ПО если ее не разу не было (Install)
  become: true
  shell: "echo '{{ relis }}' >> /etc/software.conf"
  when: version.stdout == ""
  ignore_errors: yes

- name: Запишем новую версию ПО (Update)
  become: true
  shell: "sed -i 's/{{version.stdout}}/{{ relis }}/g' /etc/software.conf"
  when: version.stdout != relis
  ignore_errors: yes
