---

- name: Чтение текущего имени хоста
  shell: cat /etc/hostname
  register: current_name

- name: Меняем имя хоста
  block:

  - name: Запись нового имени хоста в файл '/etc/hosts'
    shell: echo '127.0.0.1 {{ inventory_hostname }}.{{ domain }} {{ inventory_hostname }}' >> /etc/hosts

  - name: Установка имени хоста
    template:
      src: hostname.j2
      dest: /etc/hostname
      mode: 0644
      owner: root
      group: root

  - name: Перезагрузка ОС
    reboot:
      msg: 'Reboot'

  - name: Копирование файла '/etc/hosts'
    copy:
      src: hosts.j2
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644

  - name: Заполнение файла '/etc/hosts'
    shell: |
      {% for item in ansible_play_batch %}
      echo '{{ hostvars[item].ansible_ssh_host }} {{ item }}.{{ domain }} {{ item }}' >> /etc/hosts
      {% endfor %}

  when: inventory_hostname != current_name.stdout.split('.')[0]

- name: Дописывание новых хостов в файл '/etc/hosts'
  shell: |
    {% for item in ansible_play_batch %}
    echo '{{ hostvars[item].ansible_ssh_host }} {{ item }}.{{ domain }} {{ item }}' >> /etc/hosts
    {% endfor %}
    sort -u -o /etc/hosts /etc/hosts
    sed -i '/^$/d' /etc/hosts
    sed -i 's/\r//g' /etc/hosts

...