---

# https://redos.red-soft.ru/base/redos-8_0/8_0-administation/8_0-domain-redos/8_0-installation-ipa/8_0-redos-in-ipa/

- name: Проверка наличия файла '/etc/ipa/default.conf'
  stat:
    path: /etc/ipa/default.conf
  register: freeipa_result

- name: Регистрация клиентов домена FreeIPA
  block:

    - name: Получить имя сетевого интерфейса
      shell: |
        ip -o -4 a | grep '{{ hostvars[inventory_hostname].ansible_ssh_host }}' | awk '{print $2}'
      register: interface

    - name: Настройка сетевого интерфейса '{{ interface.stdout }}'
      shell: '{{ item }}'
      loop:
        - nmcli connection modify "{{ interface.stdout }}" ipv4.dns "{{ hostvars[FreeIPA.srv].ansible_ssh_host }}"
        - nmcli connection modify "{{ interface.stdout }}" ipv4.dns-search "{{ domain }}"

    - name: Настройка сетевого интерфейса '{{ interface.stdout }}'
      shell: '{{ item }}'
      loop:
        - nmcli connection modify "{{ interface.stdout }}" ipv4.dns "{{ hostvars[FreeIPA.srv].ansible_ssh_host }},{{ hostvars[FreeIPA.repl].ansible_ssh_host }}"
      when: FreeIPA.repl is defined

    - name: Перезагрузим хост
      reboot:
        msg: 'Reboot'

    - name: Установка пакетов необходимых для подключения к контроллеру домена FreeIPA
      dnf:
        name:
          - ipa-client

    - name: Подключение к домену FreeIPA
      shell: |
        ipa-client-install \
        --unattended \
        --server={{ FreeIPA.srv }}.{{ domain }} \
        --domain={{ domain }} \
        --principal=admin \
        --password={{ FreeIPA.pass }} \
        --hostname={{ inventory_hostname }}.{{ domain }} \
        --enable-dns-updates \
        --mkhomedir

    - name: Перезагрузим хост
      reboot:
        msg: 'Reboot'

  when: not freeipa_result.stat.exists

...