---

- name: Выполняется только на клиентах FreeIPA
  block:

  - name: Проверка наличия файла '/etc/ipa/default.conf'
    stat:
      path: /etc/ipa/default.conf
    register: freeipa_result

  - name: Регистрация клиентов домена FreeIPA
    block:

    - name: Получить список сетевых интерфейсов
      shell: |
        ip link show | grep BROADCAST | awk '{print $2}' | sed 's/.$//'
      register: device_list

    - name: Создание массива сетевых интерфейсов
      set_fact:
        interfaces: "{{ device_list.stdout_lines | list }}"

    - name: Получение количества элементов в списке интерфейсов
      set_fact:
        interfaces_length: "{{ interfaces | length }}"

    - name: Настройка сетевого интерфейса '{{ interfaces[0] }}'
      shell: '{{ item }}'
      loop:
        - nmcli connection modify "{{ interfaces[0] }}" ipv4.dns "{{ hostvars[FreeIPA.srv].ansible_ssh_host }}"
        - nmcli connection modify "{{ interfaces[0] }}" ipv4.dns-search "{{ domain }}"
      when: interfaces_length == '1'

    # - name: Перезагрузим хост
      # reboot:
        # msg: 'Reboot'

    - name: Установка пакетов необходимых для подключения к контроллеру домена FreeIPA
      dnf:
        name:
          - ipa-client

    - name: Подключение к домену FreeIPA
      shell: |
        ipa-client-install \
        --unattended \
        --server={{ FreeIPA.srv }}.{{ domain }} \
        --domain={{ domain }} \
        --principal=admin \
        --password={{ FreeIPA.pass }} \
        --hostname={{ inventory_hostname }}.{{ domain }} \
        --enable-dns-updates \
        --mkhomedir

    - name: Перезагрузим хост
      reboot:
        msg: 'Reboot'

    when: not freeipa_result.stat.exists

  when: inventory_hostname != FreeIPA.srv

...
# https://redos.red-soft.ru/base/redos-8_0/8_0-administation/8_0-domain-redos/8_0-installation-ipa/8_0-redos-in-ipa/