---

# https://redos.red-soft.ru/base/redos-8_0/8_0-administation/8_0-domain-redos/8_0-installation-ipa/8_0-replica-ipa/

- name: Проверка наличия файла '/etc/ipa/dnssec/softhsm2.conf'
  stat:
    path: /etc/ipa/dnssec/softhsm2.conf
  register: dnssec_result

- name: Создание сервера реплики контроллера домена FreeIPA
  block:

  - name: Установка пакетов необходимых для создания реплики контроллера домена FreeIPA
    dnf:
      name:
      - ipa-server-dns

  - name: Удаление пакет Java OpenJDK версии 11
    shell: |
      rpm -e java-11-openjdk-headless --nodeps

  - name: Инициализация домена FreeIPA
    shell: |
      ipa-replica-install \
      --admin-password={{ FreeIPA.pass }} \
      --domain={{ domain }} \
      --setup-ca \
      --setup-dns \
      --no-host-dns \
      --server='{{ FreeIPA.srv }}.{{ domain }}' \
      --forwarder {{ net.bind[0] }} \
      --unattended \
      --skip-mem-check

  - name: Перезагрузим сервер
    reboot:
      msg: 'Reboot'

  when: not dnssec_result.stat.exists

...