global:
  storageClass: {{ k8s.rwo_sc }}
fullnameOverride: "kibana"
clusterDomain: {{k8s.subdomain }}.{{ domain }}
plugins:
  - https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/8.5.3/kibanaPrometheusExporter-8.5.3.zip
ingress:
  hostname: kibana.{{k8s.subdomain }}.{{ domain }}
  ingressClassName: "nginx"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: "5s"
elasticsearch:
  hosts:
    - elasticsearch
  port: "9200"
