---

- import_tasks: ossec_srv.yml
  when: inventory_hostname  == ossec.srv

- import_tasks: armabi_srv.yml
  when: inventory_hostname == armabi.srv

- import_tasks: armabi_arm.yml
  when: inventory_hostname in armabi.arm

- import_tasks: armdl_agent.yml
