kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: csi-cephfs
provisioner: cephfs.csi.ceph.com
parameters:
  clusterID: "{{ ceph_cluster_id }}"
  fsName: "{{ ceph_cephfs }}"

  # (optional) Comma separated string of Ceph-fuse mount options.
  # For eg:
  # fuseMountOptions: debug

  # (optional) Comma separated string of Cephfs kernel mount options.
  # Check man mount.ceph for mount options. For eg:
  # kernelMountOptions: readdir_max_bytes=1048576,norbytes

  csi.storage.k8s.io/provisioner-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: "{{ ceph_namespace }}"
  csi.storage.k8s.io/controller-expand-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: ceph
  csi.storage.k8s.io/node-stage-secret-name: csi-cephfs-secret
  csi.storage.k8s.io/node-stage-secret-namespace: "{{ ceph_namespace }}"

  # (optional) The driver can use either ceph-fuse (fuse) or
  # ceph kernelclient (kernel).
  # If omitted, default volume mounter will be used - this is
  # determined by probing for ceph-fuse and mount.ceph
  mounter: kernel

reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
