---

- name: Очистка конфигурации
  tags:
  - clear
  - never
  block:

  - name: Удаление файла '/etc/network/interfaces.d/interfaces'
    file:
      path: /etc/network/interfaces.d/interfaces
      state: absent
    tags: reconfigure

- name: Чтение статуса интерфейсов
  shell: cat /etc/network/interfaces.d/* | grep '{{ ansible_ssh_host }}'
  register: current_status
  ignore_errors: yes

- name: Настройка сетевых интерфейсов
  block:

  - name: Копирование файла '/etc/network/interfaces.d/interfaces'
    template:
      src: bond.j2
      dest: /etc/network/interfaces.d/interfaces
      owner: root
      group: root
      mode: 0644
    when: interfaces.split(',')|length != 1

  - name: Копирование файла '/etc/network/interfaces.d/interfaces'
    template:
      src: eth.j2
      dest: /etc/network/interfaces.d/interfaces
      owner: root
      group: root
      mode: 0644
    when: interfaces.split(',')|length == 1

  - name: Установка пакетов для создания bond0
    apt:
      name: ifenslave
      state: latest
    when: interfaces.split(',')|length != 1

  - name: Удаление пакетов Network-Manager
    apt:
      name: network-manager
      state: absent
      purge: yes
    ignore_errors: yes

  - name: Удаление файла '/etc/network/interfaces'
    file:
      path: /etc/network/interfaces
      state: absent

  - name: Копирование файла '/etc/network/interfaces'
    copy:
      src: interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644

  - name: Изменения файла '/etc/default/grub'
    lineinfile:
      dest: /etc/default/grub
      regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="parsec.max_ilev=63 quiet net.ifnames=0"'
      line: 'GRUB_CMDLINE_LINUX_DEFAULT="parsec.max_ilev=63 quiet net.ifnames=0 ipv6.disable=0"'

  - name: Обновление GRUB
    shell:  update-grub
    ignore_errors: yes

  - name: Внесение дополнений в файл '/etc/sysctl.d/999-astra.conf'. Выключаем IPv6
    lineinfile:
      path: /etc/sysctl.d/999-astra.conf
      line: '{{ item }}'
    with_items:
      - 'net.ipv6.conf.lo.disable_ipv6 = 0'
      - 'net.ipv6.conf.all.disable_ipv6 = 1'

  - name: Перезагрузим сервер
    reboot:
      msg: 'Reboot'

  - name: Удаление папки '/etc/NetworkManager'
    shell:  rm -rf /etc/NetworkManager
    ignore_errors: yes

  - name: Удаление файла resolv.conf
    file:
      path: /etc/resolv.conf
      state: '{{ item }}'
    with_items:
      - absent
      - touch

  - name: Создание файла resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      line: '{{ item }}'
    with_items:
      - nameserver {{ net.bind }}
      - search {{ domain }}

  when: current_status.stdout.split('.')[0] == ''

...