{
 "title": "Redis Operator",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "kubernetesResource",
    "query": {
     "query": "label_values(redis_operator_controller_ensure_resource_total{resource_name=~\".*\"}, name)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(redis_operator_controller_ensure_resource_total{resource_name=~\"$tenant\"}, namespace)"
    }
   },
   {
    "name": "redis_pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"StatefulSet\", created_by_name=~\"rfr-$tenant\"}, pod_ip)"
    }
   },
   {
    "name": "sentinel_pod_ip",
    "query": {
     "query": "label_values(kube_pod_info{ created_by_kind=\"ReplicaSet\", created_by_name=~\"rfs-$tenant-[0-9a-z]*\"}, pod_ip)"
    }
   },
   { "name": "bucket_interval", "query": "10s,15s,30s,1m,2m,5m,10m,15m" },
   {
    "name": "tenant",
    "query": {
     "query": "label_values(redis_operator_controller_cluster_ok, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Operator - Functioning Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sentinel Checks - Unhealthy",
   "type": "timeseries",
   "description": "in check and heal process, if any of the sentinel checks are failing, it is reported here.\n\n```\nIP of sentinel instance (if applicable) -> Check / Operation performed that failed\n```",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": " (rate(redis_operator_controller_sentinel_checks_total{instance=~\"$sentinel_pod_ip\",status=\"UNHEALTHY\"}[$bucket_interval]) * 60) > bool 0",
     "legendFormat": "{{instance}} -> {{indicator}}"
    }
   ]
  },
  {
   "title": "Redis Checks - Unhealthy",
   "type": "timeseries",
   "description": "in check and heal process, if any of the redis checks are failing, it is reported here.\n\n```\nIP of redis instance (if applicable) -> Check / Operation performed\n```",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": " (rate(redis_operator_controller_redis_checks_total{instance=~\"$redis_pod_ip|NA\",status=\"UNHEALTHY\"}[$bucket_interval]) * 60) > bool 0",
     "legendFormat": "{{indicator}} {{instance}} {{resource}}"
    }
   ]
  },
  {
   "title": "Sentinel Checks - Healthy",
   "type": "timeseries",
   "description": "in check and heal process, steps that have been successfully executed are reported here\n\nin check and heal process, steps that have been successfully executed are reported here\n\nreading the legend\n```\nIP of sentinel instance (if applicable) -> Check / Operation performed\n```",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(min by (indicator, instance) (rate(redis_operator_controller_sentinel_checks_total{ instance=~\"$sentinel_pod_ip\", status=\"HEALTHY\"}[$bucket_interval])) != bool 0) > 0",
     "legendFormat": "{{instance}} {{indicator}}"
    }
   ]
  },
  {
   "title": "Redis Checks - Healthy",
   "type": "timeseries",
   "description": "in check and heal process, steps that have been successfully executed are reported here\n\nreading the legend\n```\nIP of redis instance (if applicable) -> Check / Operation performed\n```\n\n```",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(min by (indicator, instance, resource) (rate(redis_operator_controller_redis_checks_total{instance=~\"$redis_pod_ip|NA\",status=\"HEALTHY\"}[$bucket_interval])) != bool 0 ) > 0",
     "legendFormat": "{{instance}} {{indicator}}"
    }
   ]
  },
  {
   "title": "k8s ops - failures / second",
   "type": "timeseries",
   "description": "kubernetes API calls that resulted in failure.\n\nreading the legend:\n```\nnamespace -> kind -> resource -> operation -> error\n```",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (namespace, kind, name, operation, err) (rate(redis_operator_controller_k8s_operations_total{name=~\"$kubernetesResource\", status=\"FAIL\"}[$bucket_interval])) > 0",
     "legendFormat": "{{namespace}} {{kind}} {{name}} {{operation}} {{err}}"
    }
   ]
  },
  {
   "title": "redis ops - failures / second",
   "type": "timeseries",
   "description": "Reading the legend\n```\nREDIS/SENTINEL -> IP address -> Operation Performed -> Error Encounted\n```",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum by (namespace, kind, operation, status, IP, err) (rate(redis_operator_controller_redis_operations_total{IP=~\"$redis_pod_ip|$sentinel_pod_ip\",status=\"FAIL\", err!=\"SENTINEL_REGEX_NOT_FOUND\"}[$bucket_interval])) > 0",
     "legendFormat": "{{kind}} {{IP}} {{operation}} {{err}} "
    }
   ]
  },
  {
   "title": "k8s ops / second ",
   "type": "timeseries",
   "description": "kubernetes API calls made\n\nreading the legend:\n```\nnamespace -> kind -> resource -> operation -> status\n```",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(redis_operator_controller_k8s_operations_total{name=~\"$kubernetesResource\", namespace=~\"$kubernetesNamespace\"}[$bucket_interval]) ",
     "legendFormat": "{{namespace}} {{kind}} {{name}} {{operation}} {{status}}"
    }
   ]
  },
  {
   "title": "redis ops  / second",
   "type": "timeseries",
   "description": "redis / sentinel calls made per second.\n\nreading the legend:\n```\nREDIS/SENTINEL -> IP address -> Operation Performed -> Status\n```",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by (kind, operation, status, IP) (rate(redis_operator_controller_redis_operations_total{IP=~\"$redis_pod_ip|$sentinel_pod_ip\"}[$bucket_interval]))  > 0",
     "legendFormat": "{{kind}} {{IP}} {{operation}} {{status}} "
    }
   ]
  },
  { "title": "Worker Queue Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Time spent by process in queue",
   "type": "timeseries",
   "description": "Time spent by an event waiting in queue to be picked up by workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(kooper_controller_event_in_queue_duration_seconds_sum{}[$bucket_interval]) / rate(kooper_controller_event_in_queue_duration_seconds_count{}[$bucket_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent by process in running",
   "type": "timeseries",
   "description": "Time spent by workers to process an event.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(kooper_controller_processed_event_duration_seconds_sum{}[$bucket_interval]) / rate(kooper_controller_processed_event_duration_seconds_count{}[$bucket_interval]))",
     "legendFormat": "success - {{success}} pod- {{pod}}"
    }
   ]
  },
  {
   "title": "Total events in queue (per second)",
   "type": "timeseries",
   "description": "Number of events waiting in queue in an average , per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (requeue, pod) (rate(kooper_controller_queued_events_total{}[$bucket_interval]))",
     "legendFormat": "pod - {{pod}}  requeued - {{requeue}}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "description": "size of the queue",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "kooper_controller_event_queue_length{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Time spent by event in worker queue",
   "type": "histogram",
   "description": "A histogram of time spent by an event waiting in queue",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(kooper_controller_event_in_queue_duration_seconds_bucket{}[$bucket_interval])) by (le))",
     "legendFormat": "time spent waiting"
    }
   ]
  },
  {
   "title": "Time spent by event being proccessed",
   "type": "histogram",
   "description": "A histogram of time spent by worker to process an event",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(kooper_controller_processed_event_duration_seconds_bucket{}[2m])) by (le))",
     "legendFormat": "time spent running"
    }
   ]
  },
  { "title": "go - system metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "rate of objects allocated [heap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "(increase(go_memstats_mallocs_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}[$bucket_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "number of live objects [heap]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"} -  go_memstats_frees_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "heap memory in use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "stack memory allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(rate(go_memstats_alloc_bytes_total{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}[$bucket_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "stack memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "number of goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "go_goroutines{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Duration [max]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\", quantile=\"1\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU throttled [%]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod, container) ((rate(container_cpu_cfs_throttled_periods_total{container=\"app\", pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}[$bucket_interval]) / rate(container_cpu_cfs_periods_total{container=\"app\", pod=~\"redisoperator-[0-9a-z]+-[0-9a-z]+\"}[$bucket_interval])) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}