---
# tasks file for init_ceph_astra
- name: Install ceph mon osd
  shell: |
     ceph-deploy --username ceph-adm install --mon --osd master01 master02 master03

#reboot

- name: Install ceph mgr
  shell: |
     ceph-deploy --username ceph-adm install --mgr master01 master02 master03

- name: Create ceph cluster
  shell: |
     ceph-deploy --username ceph-adm new master01 master02 master03

- name: Initial mon
  shell: |
     ceph-deploy --username ceph-adm mon create-initial

- name: Create mgr
  shell: |
     ceph-deploy --username ceph-adm mgr create master01 master02 master03

- name: Create osd
  shell: |
     ceph-deploy --overwrite-conf --username ceph-adm osd create --data /dev/vg0/ceph master01
     ceph-deploy --overwrite-conf --username ceph-adm osd create --data /dev/vg0/ceph master02
     ceph-deploy --overwrite-conf --username ceph-adm osd create --data /dev/vg0/ceph master03

- name: Install mds
  shell: |
     ceph-deploy --username ceph-adm install --mds master01 master02 master03
  

- name: copy ceph.client.admin.keyring
  copy:
      src: 'ceph.client.admin.keyring'
      dest: '/etc/ceph'
      owner: root
      group: root
      mode: '0644'
  become: true
  become_method: sudo

- name: Create mds
  shell: |
     ceph-deploy --overwrite-conf --username ceph-adm mds create master01 master02 master03

- name: insecure allow
  shell: |
     ceph config set mon auth_allow_insecure_global_id_reclaim false
  become: true
  become_method: sudo

- name: create poll kube
  shell: |
     ceph osd pool create kube 32
  become: true
  become_method: sudo

- name: create cephfs
  shell: |     
     ceph osd pool create cephfs_data 32
     ceph osd pool create cephfs_metadata 32
     ceph fs new cephfs cephfs_metadata cephfs_data
  become: true
  become_method: sudo
     
- name: add client kube
  shell: |     
     ceph auth add client.kube mon 'allow r' osd 'allow rwx pool=kube,allow rwx pool=cephfs_data' mds 'allow rw'
  become: true
  become_method: sudo

- name: init kube
  shell: |     
     rbd pool init kube
  become: true
  become_method: sudo