apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: "{{ registry_namespace }}"
spec:
  storageClassName: "{{ kubernetes_rwx_sc }}"
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  #volumeMode: Filesystem
  # volumeName should be same as PV name