---
# Source: csi-driver-lvm/templates/common.yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: lvm.csi.metal-stack.io
spec:
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  podInfoOnMount: true
  attachRequired: false
