---
# Source: csi-driver-lvm/templates/controller.yaml
#apiVersion: policy/v1
#kind: PodSecurityPolicy
#metadata:
#  name: csi-driver-lvm-controller
#spec:
#  allowedHostPaths:
#  - pathPrefix: /var/lib/kubelet/plugins/csi-driver-lvm
#  fsGroup:
#    rule: RunAsAny
#  privileged: true
#  runAsUser:
#    rule: RunAsAny
#  seLinux:
#    rule: RunAsAny
#  supplementalGroups:
#    rule: RunAsAny
#  volumes:
#  - secret
#  - hostPath
---
# Source: csi-driver-lvm/templates/controller.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-driver-lvm-controller
  namespace: "{{ lvm_provisioner_namespace }}"
---
# Source: csi-driver-lvm/templates/controller.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-driver-lvm-controller
  labels:
    heritage: Helm
    release: mytest
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
# Source: csi-driver-lvm/templates/controller.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-driver-lvm-controller
  labels:
    heritage: Helm
    release: mytest
subjects:
  - kind: ServiceAccount
    name: csi-driver-lvm-controller
    namespace: "{{ lvm_provisioner_namespace }}"
roleRef:
  kind: ClusterRole
  name: csi-driver-lvm-controller
  apiGroup: rbac.authorization.k8s.io
---
# Source: csi-driver-lvm/templates/controller.yaml
#apiVersion: rbac.authorization.k8s.io/v1
#kind: Role
#metadata:
#  name: csi-driver-lvm-controller
#  labels:
#    heritage: Helm
#    release: mytest
#rules:
#- apiGroups:
#  - policy
#  resourceNames:
#  - csi-driver-lvm-controller
#  resources:
#  - podsecuritypolicies
#  verbs:
#  - use
#---
# Source: csi-driver-lvm/templates/controller.yaml
#apiVersion: rbac.authorization.k8s.io/v1
#kind: RoleBinding
#metadata:
#  name: csi-driver-lvm-controller
#  labels:
#    heritage: Helm
#    release: mytest
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: Role
#  name: csi-driver-lvm-controller
#subjects:
#- kind: ServiceAccount
#  name: csi-driver-lvm-controller
#  namespace: "{{ lvm_provisioner_namespace }}"
---
# Source: csi-driver-lvm/templates/controller.yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-driver-lvm-controller
  namespace: "{{ lvm_provisioner_namespace }}"
spec:
  serviceName: csi-driver-lvm-controller
  replicas: 1
  selector:
    matchLabels:
      app: csi-driver-lvm-controller
  template:
    metadata:
      labels:
        app: csi-driver-lvm-controller
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-driver-lvm-plugin
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      serviceAccountName: csi-driver-lvm-controller
      containers:
        - name: csi-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /csi
            name: socket-dir
        - name: csi-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: csi-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - -csi-address=/csi/csi.sock
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-driver-lvm
            type: DirectoryOrCreate
          name: socket-dir
