---
### 8.1 - Firefox ###
- name: Проверка наличия файла /usr/lib/firefox/browser/defaults/preferences/kerberos.js
  stat:
    path: /usr/lib/firefox/browser/defaults/preferences/kerberos.js
  register: kerberos_result

- name: Установка и настройка Firefox
  block:
  - name: Установка пакетов Firefox
    apt:
      name:
      - firefox
      state: latest
      update_cache: yes
 
  - name: Удаление лишних пакетов
    apt:
      autoremove: yes

  - name: Добавление пользовательских настроек аутентификации по Kerberos
    copy:
      src: "kerberos.j2"
      dest: "/usr/lib/firefox/browser/defaults/preferences/kerberos.js"
      owner: "root"
      group: "root"
      mode: '644'

  when: 
  - not kerberos_result.stat.exists   
  - inventory_hostname in groups['firefox']
  
#- name: Firefox | Копирование сертификата
#  copy:
#    src: gca.crt
#    dest: /usr/local/share/ca-certificates/
#    mode: '0644'
#  when: version.stdout != relis

#- name: Firefox | Обновим список сертификатов
#  shell: sudo update-ca-certificates
#  when: version.stdout != relis

#- name: Firefox | Копирование пакетов со шрифтами
#  copy:
#    src: deb
#    dest: /tmp/Firefox
#    mode: '700'
#    force: no
#    directory_mode: yes
#  when: version.stdout != relis

#- name: Firefox | Установка шрифтов
#  shell: "{{item}}"
#  loop:
#    - 'apt --fix-broken install -y'
#    - 'apt install ibus ibus-gtk3 -y'
#    - 'dpkg -i /tmp/Firefox/deb/*.deb'
#    - 'echo "export GTK_IM_MODULE=ibus" >> ~/.bashrc'
#    - 'echo "export XMODIFIERS=@im=ibus" >> ~/.bashrc'
#    - 'echo "export QT_IM_MODULE=ibus" >> ~/.bashrc'
#    - 'echo "ibus-daemon -d -x -r" >> ~/.profile'
#    - 'echo "export GTK_IM_MODULE=ibus" >> /etc/skel/.bashrc'
#    - 'echo "export XMODIFIERS=@im=ibus" >> /etc/skel/.bashrc'
#    - 'echo "export QT_IM_MODULE=ibus" >> /etc/skel/.bashrc'
#    - 'echo "ibus-daemon -d -x -r" >> /etc/skel/.profile'
#  when: version.stdout != relis
