---

- name: Установка дополнительных служб
  block:

  - name: Инсталляция пакетов пользовательских служб '{{ item.after }}' на серверах кластера '{{ item.name }}'
    apt:
      name: '{{ item.after }}'

  - name: Останавливка пользовательских служб
    service:
      name: '{{ service }}'
      state: stopped
      enabled: no
    with_items: '{{ item.after }}'
    loop_control:
      loop_var: service

  - name: Добавление дополнительных служб в кластер
    block:

    - name: Добавление дополнительных служб в кластер
      shell: |
          pcs resource create Service_After_{{ service }} systemd:{{ service }}
          pcs constraint colocation add Service_After_{{ service }} with {{ item.name }}_IP_V4 INFINITY  
          pcs constraint order {{ item.name }}_IP_V4 then Service_After_{{ service }} 
          pcs cluster start --all
      with_items: '{{ item.after }}'
      loop_control:
        loop_var: service

    when: inventory_hostname == item.srv[0]


  when:
    - item.after is defined
    - inventory_hostname in item.srv

...