---

- name: Развертывание кластера PostgreSQL
  block:

  - name: Инсталляция пакетов 'PostgreSQL'
    apt:
      name: 
      - postgresql
      - postgresql-se-test-9.6
      - pgadmin3
      - nfs-common

  - name: Настройка 'PostgreSQL'
    shell: |
      sed -i '/Развертывание кластера PostgreSQL'/d /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '86 a host     all         postgres        127.0.0.1/32       trust    # Развертывание кластера PostgreSQL' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i '87 a host     all         postgres        {{ net.net }}/24    pam    # Развертывание кластера PostgreSQL' /etc/postgresql/9.6/main/pg_hba.conf
      sed -i 's/localhost/*/g' /etc/postgresql/9.6/main/postgresql.conf
      usermod -a -G shadow postgres
      setfacl -d -m u:postgres:r /etc/parsec/macdb
      setfacl -R -m u:postgres:r /etc/parsec/macdb
      setfacl -m u:postgres:rx /etc/parsec/macdb
      setfacl -d -m u:postgres:r /etc/parsec/capdb
      setfacl -R -m u:postgres:r /etc/parsec/capdb
      setfacl -m u:postgres:rx /etc/parsec/capdb
    ignore_errors: yes

  - name: Создание базы данных на СХД
    block:

    - name: Создание тестовых базы данных 'TestDB' и пользователя 'TestUSER (pwd:12345678)'
      shell: |
        sudo -u postgres psql -c 'DROP DATABASE IF EXISTS TestDB;'
        sudo -u postgres psql -c 'DROP ROLE IF EXISTS TestUSER;'
        sudo -u postgres psql -c 'CREATE DATABASE TestDB;'
        sudo -u postgres psql -c 'CREATE ROLE TestUSER WITH LOGIN PASSWORD $$12345678$$;'
        sudo -u postgres psql -c 'GRANT ALL ON DATABASE TestDB to TestUSER;'
      ignore_errors: yes

    - name: Останавливаем службу 'postgresql'
      service:
        name: postgresql
        state: stopped

    - name: Создание копии локальной БД на СХД
      shell: | 
        mkdir /tmp/main
        cp -rp /var/lib/postgresql/9.6/main/* /tmp/main/
        mount {{ item.postgresql.dev }} /var/lib/postgresql/9.6/main/
        rm -r /var/lib/postgresql/9.6/main/*
        cp -rp /tmp/main/* /var/lib/postgresql/9.6/main/
        chown -R postgres:postgres /var/lib/postgresql/9.6/main/
        chmod -R 700 /var/lib/postgresql/9.6/main/
        umount /var/lib/postgresql/9.6/main

    when: inventory_hostname == item.srv[0]

  - name: Инсталляция пакетов пользовательских служб '{{ item.postgresql.after }}' на серверах кластера '{{ item.name }}'
    apt:
      name: '{{ item.postgresql.after }}'

  - name: Останавливка пользовательских служб '{{ item.postgresql.after }}'
    service:
      name: '{{ service }}'
      state: stopped
      enabled: no
    with_items: '{{ item.postgresql.after }}'
    loop_control:
      loop_var: service

  # - name: Настройка слейв узлов и синхронизация их
    # block:

    #- name: Останавливаем службу postgresql
      # service:
        # name: postgresql
        # state: stopped

    # - name: Внесение изменений в /etc/postgresql/9.6/main/postgresql.conf
      # lineinfile: 
        # dest: /etc/postgresql/9.6/main/postgresql.conf
        # regexp: '^{{ item.src }}'
        # insertbefore: BOF
        # line: '{{ item.dest }}'
      # loop:
      # - { src: "#hot_standby", dest: "hot_standby = on      # Развертывание кластера PostgreSQL" }

    # - name: Удаление содержимого кластера СУБД
      # shell: sudo -u postgres sh -c "rm -Rf {{ cluster_postgresql.data }}/*"
      # ignore_errors: yes

    # - name: Создание реплики
      # shell: sudo -u postgres pg_basebackup -h {{ cluster.ip[0] }} -D {{ cluster_postgresql.data }} -R -P --xlog-method=stream

    # - name: Запускаем службу postgresql
      # service:
        # name: postgresql
        # state: started

    # when: inventory_hostname == cluster.srv[1]

  - name: Создание кластерных ресурсов
    block:

    - name: Инициализация кластерной службы pgsql
      shell: pcs resource delete PostgreSQL_9.6
      ignore_errors: yes

    - name: Создание ресурса с именем 'PostgreSQL_9.6'
      shell: |
        pcs resource create PostgreSQL_9.6 ocf:astra:pgsql pgversion="9.6"  master_ip="{{ item.ip }}" node_list="{{ item.srv | join(' ') }}"

    - name: Добавление дискового ресурса кластера расположенного на '{{ item.postgresql.dev }}' как ресурс 'Postgre_Data'
      shell: |
        pcs resource create PostgreSQL_Data ocf:heartbeat:Filesystem directory=/var/lib/postgresql/9.6/main device={{ item.postgresql.dev }} fstype=ext4

    - name: Объявление зависимости 'PostgreSQL_Data' от '{{ item.name }}_IP_V4'
      shell: |
        pcs constraint colocation add PostgreSQL_Data with {{ item.name }}_IP_V4 INFINITY 
        pcs constraint order {{ item.name }}_IP_V4 then PostgreSQL_Data 
        pcs cluster start --all

    - name: Объявление зависимости 'PostgreSQL_9.6' от 'PostgreSQL_Data'
      shell: |
        pcs constraint colocation add PostgreSQL_9.6 with PostgreSQL_Data INFINITY 
        pcs constraint order PostgreSQL_Data then PostgreSQL_9.6 
        pcs cluster start --all

    - name: Добавление пользовательских ресурсов 'Service_{{ item.postgresql.after }}' в кластер '{{ item.name }}'
      shell: |
          pcs resource create Service_{{ service }} systemd:{{ service }}
          pcs constraint colocation add Service_{{ service }} with PostgreSQL_9.6 INFINITY 
          pcs constraint order PostgreSQL_9.6 then Service_{{ service }} 
          pcs cluster start --all
      with_items: '{{ item.postgresql.after }}'
      loop_control:
        loop_var: service

    when: inventory_hostname == item.srv[0]

  when:
  - item.postgresql is defined
  - inventory_hostname in item.srv

...